
/*
Auto-generated by CVXPYgen on September 21, 2025 at 13:18:33.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 70> x_ref;
    std::array<double, 20> u_ref;
    std::array<double, 196> Ak_0;
    std::array<double, 56> Bk_minus_0;
    std::array<double, 56> Bk_plus_0;
    std::array<double, 56> ck;
    std::array<double, 196> Ak_1;
    std::array<double, 56> Bk_minus_1;
    std::array<double, 56> Bk_plus_1;
    std::array<double, 196> Ak_2;
    std::array<double, 56> Bk_minus_2;
    std::array<double, 56> Bk_plus_2;
    std::array<double, 196> Ak_3;
    std::array<double, 56> Bk_minus_3;
    std::array<double, 56> Bk_plus_3;
    std::array<double, 14> x_0;
    std::array<double, 13> x_f;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool x_ref;
    bool u_ref;
    bool Ak_0;
    bool Bk_minus_0;
    bool Bk_plus_0;
    bool ck;
    bool Ak_1;
    bool Bk_minus_1;
    bool Bk_plus_1;
    bool Ak_2;
    bool Bk_minus_2;
    bool Bk_plus_2;
    bool Ak_3;
    bool Bk_minus_3;
    bool Bk_plus_3;
    bool x_0;
    bool x_f;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 70> X;
    std::array<double, 20> U;
    std::array<double, 56> V;
    std::array<double, 14> v_0;
    std::array<double, 13> v_N;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 14> d0;
    std::array<double, 14> d1;
    std::array<double, 14> d2;
    std::array<double, 14> d3;
    std::array<double, 5> d4;
    std::array<double, 5> d5;
    std::array<double, 5> d6;
    std::array<double, 5> d7;
    std::array<double, 5> d8;
    double d9;
    std::array<double, 3> d10;
    std::array<double, 196> d11;
    std::array<double, 169> d12;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    int status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
