function xdot = SymDynamics3DoF_linear(t,in2,in3,tf,alpha,g)
%SymDynamics3DoF_linear
%    XDOT = SymDynamics3DoF_linear(T,IN2,IN3,TF,ALPHA,G)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    14-Aug-2025 10:51:39

thrust1 = in3(1,:);
thrust2 = in3(2,:);
thrust3 = in3(3,:);
thrust_mag1 = in3(4,:);
v1 = in2(4,:);
v2 = in2(5,:);
v3 = in2(6,:);
xdot = [tf.*v1;tf.*v2;tf.*v3;tf.*thrust1;tf.*thrust2;-tf.*(g-thrust3);-alpha.*tf.*thrust_mag1];
end
