function x_dot = SymDynamics6DoF_q(in1,in2,in3)
%SymDynamics6DoF_q
%    X_DOT = SymDynamics6DoF_q(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Feb-2025 19:01:23

I1 = in3(4);
I2 = in3(5);
I3 = in3(6);
L = in3(3);
T1 = in2(1);
T2 = in2(2);
T3 = in2(3);
g = in3(1);
gamma1 = in2(4);
mass = in3(2);
q1 = in1(7);
q2 = in1(8);
q3 = in1(9);
q4 = in1(10);
v1 = in1(4);
v2 = in1(5);
v3 = in1(6);
w1 = in1(11);
w2 = in1(12);
w3 = in1(13);
t2 = cos(gamma1);
t3 = q1.^2;
t4 = q2.^2;
t5 = q3.^2;
t6 = q4.^2;
t7 = q1.*q2.*2.0;
t8 = q1.*q3.*2.0;
t9 = q1.*q4.*2.0;
t10 = q2.*q3.*2.0;
t11 = q2.*q4.*2.0;
t12 = q3.*q4.*2.0;
t13 = -I3;
t14 = 1.0./mass;
t15 = -t4;
t16 = -t5;
t17 = -t6;
mt1 = [v1;v2;v3;t2.*t14.*(-T3.*(t8-t11)+T1.*(t3+t4+t16+t17)+T2.*(t9+t10));t2.*t14.*(-T1.*(t9-t10)+T2.*(t3+t5+t15+t17)+T3.*(t7+t12));-g+t2.*t14.*(-T2.*(t7-t12)+T3.*(t3+t6+t15+t16)+T1.*(t8+t11));q2.*w1.*(-1.0./2.0)-(q3.*w2)./2.0-(q4.*w3)./2.0;(q1.*w1)./2.0-(q3.*w3)./2.0+(q4.*w2)./2.0;(q1.*w2)./2.0+(q2.*w3)./2.0-(q4.*w1)./2.0;(q1.*w3)./2.0-(q2.*w2)./2.0+(q3.*w1)./2.0;(sin(gamma1).*sqrt(T1.^2+T2.^2+T3.^2)+w2.*w3.*(I2+t13))./I1];
mt2 = [-(w1.*w3.*(I1+t13)-L.*T3.*t2)./I2;-(L.*T2.*t2-w1.*w2.*(I1-I2))./I3];
x_dot = [mt1;mt2];
end
