function x_dot = SymDynamicsQuat6DoF_localrot_alphabeta_disturbed(in1,in2,L,in4,alpha_T,g,in7)
%SymDynamicsQuat6DoF_localrot_alphabeta_disturbed
%    X_DOT = SymDynamicsQuat6DoF_localrot_alphabeta_disturbed(IN1,IN2,L,IN4,alpha_T,G,IN7)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    31-Aug-2025 02:44:46

I1 = in4(1,:);
I2 = in4(2,:);
I3 = in4(3,:);
T1 = in2(1,:);
alpha1 = in2(2,:);
beta1 = in2(3,:);
d_T = in7(1,:);
d_a1 = in7(2,:);
d_a2 = in7(3,:);
d_a3 = in7(4,:);
m1 = in1(14,:);
tau1 = in2(4,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
theta4 = in1(10,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
w1 = in1(11,:);
w2 = in1(12,:);
w3 = in1(13,:);
t2 = conj(T1);
t3 = conj(alpha1);
t4 = cos(alpha1);
t5 = conj(beta1);
t6 = cos(beta1);
t7 = conj(d_T);
t8 = sin(alpha1);
t9 = sin(beta1);
t14 = -I3;
t15 = 1.0./m1;
t10 = cos(t3);
t11 = cos(t5);
t12 = sin(t3);
t13 = sin(t5);
t16 = T1.*d_T.*t8.*theta1;
t17 = T1.*d_T.*t8.*theta3;
t18 = T1.*d_T.*t8.*theta4;
t19 = T1.*d_T.*t9.*theta1;
t20 = T1.*d_T.*t9.*theta2;
t21 = T1.*d_T.*t9.*theta4;
t22 = T1.*d_T.*t4.*t6.*theta2;
t23 = T1.*d_T.*t4.*t6.*theta3;
t24 = T1.*d_T.*t4.*t6.*theta4;
t25 = -t17;
t26 = -t19;
t27 = t2.*t7.*t12.*theta2;
t28 = t2.*t7.*t13.*theta3;
t29 = -t22;
t30 = t2.*t7.*t10.*t11.*theta1;
t31 = t16+t21+t29;
t32 = t18+t23+t26;
t33 = t20+t24+t25;
t34 = t27+t28+t30;
mt1 = [v1;v2;v3;d_a1+t15.*(t31.*theta2-t32.*theta3+t34.*theta1+t33.*theta4);d_a2+t15.*(-t31.*theta1+t32.*theta4+t33.*theta3+t34.*theta2);d_a3-g+t15.*(t32.*theta1+t31.*theta4-t33.*theta2+t34.*theta3);(theta2.*w3)./2.0-(theta3.*w2)./2.0+(theta4.*w1)./2.0;theta1.*w3.*(-1.0./2.0)+(theta3.*w1)./2.0+(theta4.*w2)./2.0;(theta1.*w2)./2.0-(theta2.*w1)./2.0+(theta4.*w3)./2.0;w1.*conj(theta1).*(-1.0./2.0)-(w2.*conj(theta2))./2.0-(w3.*conj(theta3))./2.0;(tau1+w2.*w3.*(I2+t14))./I1;-(w1.*w3.*(I1+t14)-L.*T1.*d_T.*t9)./I2];
mt2 = [(w1.*w2.*(I1-I2)-L.*T1.*d_T.*t8)./I3;-alpha_T.*tau1-T1.*alpha_T.*d_T];
x_dot = [mt1;mt2];
end
