function x_dot = SymDynamicsEuler6DoF_mass(in1,in2,L,in4,alpha)
%SymDynamicsEuler6DoF_mass
%    X_DOT = SymDynamicsEuler6DoF_mass(IN1,IN2,L,IN4,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    13-Aug-2025 02:52:10

I1 = in4(1,:);
I2 = in4(2,:);
I3 = in4(3,:);
T1 = in2(1,:);
T2 = in2(2,:);
T3 = in2(3,:);
gamma1 = in2(5,:);
m1 = in1(13,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
thrust_mag1 = in2(4,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
w1 = in1(10,:);
w2 = in1(11,:);
w3 = in1(12,:);
t2 = cos(gamma1);
t3 = cos(theta1);
t4 = cos(theta2);
t5 = cos(theta3);
t6 = sin(theta1);
t7 = sin(theta2);
t8 = sin(theta3);
t9 = -I3;
t10 = 1.0./m1;
t11 = 1.0./t7;
x_dot = [v1;v2;v3;t2.*t10.*(T1.*t4+T3.*t5.*t7+T2.*t7.*t8);t2.*t10.*(T2.*(t3.*t5-t4.*t6.*t8)-T3.*(t3.*t8+t4.*t5.*t6)+T1.*t6.*t7);-t2.*t10.*(-T2.*(t5.*t6+t3.*t4.*t8)+T3.*(t6.*t8-t3.*t4.*t5)+T1.*t3.*t7)-1.62e-3;t5.*t11.*w3+t8.*t11.*w2;t5.*w2-t8.*w3;w1-t4.*t5.*t11.*w3-t4.*t8.*t11.*w2;(thrust_mag1.*sin(gamma1)+w2.*w3.*(I2+t9))./I1;-(w1.*w3.*(I1+t9)-L.*T3.*t2)./I2;-(L.*T2.*t2-w1.*w2.*(I1-I2))./I3;-alpha.*thrust_mag1];
end
