function x_dot = SymDynamicsDualQuat6DoF(in1,in2,tf,g,L,in6,alpha_ME,alpha_RCS)
%SymDynamicsDualQuat6DoF
%    X_DOT = SymDynamicsDualQuat6DoF(IN1,IN2,TF,G,L,IN6,alpha_ME,alpha_RCS)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    28-Jun-2025 02:53:43

I1 = in6(1,:);
I2 = in6(2,:);
I3 = in6(3,:);
T1 = in2(1,:);
delta1 = in2(2,:);
gamma1 = in2(4,:);
gamma2 = in2(5,:);
gamma3 = in2(6,:);
m = in1(1,:);
qq1 = in1(2,:);
qq2 = in1(3,:);
qq3 = in1(4,:);
qq4 = in1(5,:);
qq5 = in1(6,:);
qq6 = in1(7,:);
qq7 = in1(8,:);
qq8 = in1(9,:);
v_B1 = in1(13,:);
v_B2 = in1(14,:);
v_B3 = in1(15,:);
w_B1 = in1(10,:);
w_B2 = in1(11,:);
w_B3 = in1(12,:);
t2 = cos(delta1);
t3 = conj(g);
t4 = conj(qq1);
t5 = conj(qq2);
t6 = conj(qq3);
t7 = sin(delta1);
t9 = 1.0./m;
t8 = t7.^2;
mt1 = [-tf.*(T1.*alpha_ME+(alpha_RCS.*sqrt(gamma1.^2+gamma2.^2+gamma3.^2))./L);tf.*((qq2.*w_B3)./2.0-(qq3.*w_B2)./2.0+(qq4.*w_B1)./2.0);tf.*(qq1.*w_B3.*(-1.0./2.0)+(qq3.*w_B1)./2.0+(qq4.*w_B2)./2.0);tf.*((qq1.*w_B2)./2.0-(qq2.*w_B1)./2.0+(qq4.*w_B3)./2.0);-tf.*((t4.*w_B1)./2.0+(t5.*w_B2)./2.0+(t6.*w_B3)./2.0);tf.*((qq2.*v_B3)./2.0-(qq3.*v_B2)./2.0+(qq4.*v_B1)./2.0+(qq6.*w_B3)./2.0-(qq7.*w_B2)./2.0+(qq8.*w_B1)./2.0);tf.*(qq1.*v_B3.*(-1.0./2.0)+(qq3.*v_B1)./2.0+(qq4.*v_B2)./2.0-(qq5.*w_B3)./2.0+(qq7.*w_B1)./2.0+(qq8.*w_B2)./2.0)];
mt2 = [tf.*((qq1.*v_B2)./2.0-(qq2.*v_B1)./2.0+(qq4.*v_B3)./2.0+(qq5.*w_B2)./2.0-(qq6.*w_B1)./2.0+(qq8.*w_B3)./2.0);-tf.*((t4.*v_B1)./2.0+(t5.*v_B2)./2.0+(t6.*v_B3)./2.0+(w_B1.*conj(qq5))./2.0+(w_B2.*conj(qq6))./2.0+(w_B3.*conj(qq7))./2.0);(t9.*tf.*(gamma1+L.*T1.*t8+I2.*m.*w_B2.*w_B3-I3.*m.*w_B2.*w_B3))./I1;(t9.*tf.*(gamma2-I1.*m.*w_B1.*w_B3+I3.*m.*w_B1.*w_B3-L.*T1.*t2.*t7))./I2;(t9.*tf.*(gamma3+I1.*m.*w_B1.*w_B2-I2.*m.*w_B1.*w_B2))./I3;tf.*(t9.*(T1.*t2.*t7+m.*v_B2.*w_B3-m.*v_B3.*w_B2)-g.*qq1.*qq3+g.*qq2.*qq4.*2.0-qq1.*qq3.*t3)];
mt3 = [-tf.*(-t9.*(T1.*t8-m.*v_B1.*w_B3+m.*v_B3.*w_B1)+g.*qq1.*qq4.*2.0+g.*qq2.*qq3+qq2.*qq3.*t3);tf.*(g.*qq1.^2+g.*qq2.^2-g.*qq4.^2-qq3.^2.*t3+t9.*(T1.*t2+m.*v_B1.*w_B2-m.*v_B2.*w_B1))];
x_dot = [mt1;mt2;mt3];
end
