function x_dot = SymDynamicsQuat6DoF_localrot_alphabeta(in1,in2,L,in4,alpha_T,g)
%SymDynamicsQuat6DoF_localrot_alphabeta
%    X_DOT = SymDynamicsQuat6DoF_localrot_alphabeta(IN1,IN2,L,IN4,alpha_T,G)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    07-Sep-2025 14:31:41

I1 = in4(1,:);
I2 = in4(2,:);
I3 = in4(3,:);
T1 = in2(1,:);
alpha1 = in2(2,:);
beta1 = in2(3,:);
m1 = in1(14,:);
tau1 = in2(4,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
theta4 = in1(10,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
w1 = in1(11,:);
w2 = in1(12,:);
w3 = in1(13,:);
t2 = conj(T1);
t3 = conj(alpha1);
t4 = conj(beta1);
t5 = sin(alpha1);
t6 = sin(beta1);
t11 = -I3;
t12 = 1.0./m1;
t7 = sin(t3);
t8 = sin(t4);
t9 = t5.^2;
t10 = t6.^2;
t13 = T1.*t5.*theta1;
t14 = T1.*t5.*theta3;
t15 = T1.*t5.*theta4;
t16 = T1.*t6.*theta1;
t17 = T1.*t6.*theta2;
t18 = T1.*t6.*theta4;
t19 = -t9;
t20 = -t10;
t21 = t2.*t7.*theta2;
t22 = t2.*t8.*theta3;
t23 = -t14;
t24 = -t16;
t25 = t19+t20+1.0;
t26 = sqrt(t25);
t27 = conj(t26);
t28 = T1.*t26.*theta2;
t29 = T1.*t26.*theta3;
t30 = T1.*t26.*theta4;
t31 = -t28;
t32 = t2.*t27.*theta1;
t34 = t15+t24+t29;
t35 = t17+t23+t30;
t33 = t13+t18+t31;
t36 = t21+t22+t32;
mt1 = [v1;v2;v3;t12.*(t33.*theta2-t34.*theta3+t36.*theta1+t35.*theta4);t12.*(-t33.*theta1+t34.*theta4+t35.*theta3+t36.*theta2);-g+t12.*(t34.*theta1+t33.*theta4-t35.*theta2+t36.*theta3);(theta2.*w3)./2.0-(theta3.*w2)./2.0+(theta4.*w1)./2.0;theta1.*w3.*(-1.0./2.0)+(theta3.*w1)./2.0+(theta4.*w2)./2.0;(theta1.*w2)./2.0-(theta2.*w1)./2.0+(theta4.*w3)./2.0;w1.*conj(theta1).*(-1.0./2.0)-(w2.*conj(theta2))./2.0-(w3.*conj(theta3))./2.0;(tau1+w2.*w3.*(I2+t11))./I1;-(w1.*w3.*(I1+t11)-L.*T1.*t6)./I2;-(L.*T1.*t5-w1.*w2.*(I1-I2))./I3];
mt2 = [-T1.*alpha_T-alpha_T.*tau1];
x_dot = [mt1;mt2];
end
