
/*
Auto-generated by CVXPYgen on September 21, 2025 at 13:18:33.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_x_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_u_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+70] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+90] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+286] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+342] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_ck(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+398] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+454] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+650] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+706] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+762] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+958] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1014] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1070] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1266] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1322] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_x_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1378] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_x_f(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1392] = val;
  Canon_Outdated.b = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<2254; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<511; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.X[0] = qoco_solver->sol->x[0];
  CPG_Prim.X[1] = qoco_solver->sol->x[1];
  CPG_Prim.X[2] = qoco_solver->sol->x[2];
  CPG_Prim.X[3] = qoco_solver->sol->x[3];
  CPG_Prim.X[4] = qoco_solver->sol->x[4];
  CPG_Prim.X[5] = qoco_solver->sol->x[5];
  CPG_Prim.X[6] = qoco_solver->sol->x[6];
  CPG_Prim.X[7] = qoco_solver->sol->x[7];
  CPG_Prim.X[8] = qoco_solver->sol->x[8];
  CPG_Prim.X[9] = qoco_solver->sol->x[9];
  CPG_Prim.X[10] = qoco_solver->sol->x[10];
  CPG_Prim.X[11] = qoco_solver->sol->x[11];
  CPG_Prim.X[12] = qoco_solver->sol->x[12];
  CPG_Prim.X[13] = qoco_solver->sol->x[13];
  CPG_Prim.X[14] = qoco_solver->sol->x[14];
  CPG_Prim.X[15] = qoco_solver->sol->x[15];
  CPG_Prim.X[16] = qoco_solver->sol->x[16];
  CPG_Prim.X[17] = qoco_solver->sol->x[17];
  CPG_Prim.X[18] = qoco_solver->sol->x[18];
  CPG_Prim.X[19] = qoco_solver->sol->x[19];
  CPG_Prim.X[20] = qoco_solver->sol->x[20];
  CPG_Prim.X[21] = qoco_solver->sol->x[21];
  CPG_Prim.X[22] = qoco_solver->sol->x[22];
  CPG_Prim.X[23] = qoco_solver->sol->x[23];
  CPG_Prim.X[24] = qoco_solver->sol->x[24];
  CPG_Prim.X[25] = qoco_solver->sol->x[25];
  CPG_Prim.X[26] = qoco_solver->sol->x[26];
  CPG_Prim.X[27] = qoco_solver->sol->x[27];
  CPG_Prim.X[28] = qoco_solver->sol->x[28];
  CPG_Prim.X[29] = qoco_solver->sol->x[29];
  CPG_Prim.X[30] = qoco_solver->sol->x[30];
  CPG_Prim.X[31] = qoco_solver->sol->x[31];
  CPG_Prim.X[32] = qoco_solver->sol->x[32];
  CPG_Prim.X[33] = qoco_solver->sol->x[33];
  CPG_Prim.X[34] = qoco_solver->sol->x[34];
  CPG_Prim.X[35] = qoco_solver->sol->x[35];
  CPG_Prim.X[36] = qoco_solver->sol->x[36];
  CPG_Prim.X[37] = qoco_solver->sol->x[37];
  CPG_Prim.X[38] = qoco_solver->sol->x[38];
  CPG_Prim.X[39] = qoco_solver->sol->x[39];
  CPG_Prim.X[40] = qoco_solver->sol->x[40];
  CPG_Prim.X[41] = qoco_solver->sol->x[41];
  CPG_Prim.X[42] = qoco_solver->sol->x[42];
  CPG_Prim.X[43] = qoco_solver->sol->x[43];
  CPG_Prim.X[44] = qoco_solver->sol->x[44];
  CPG_Prim.X[45] = qoco_solver->sol->x[45];
  CPG_Prim.X[46] = qoco_solver->sol->x[46];
  CPG_Prim.X[47] = qoco_solver->sol->x[47];
  CPG_Prim.X[48] = qoco_solver->sol->x[48];
  CPG_Prim.X[49] = qoco_solver->sol->x[49];
  CPG_Prim.X[50] = qoco_solver->sol->x[50];
  CPG_Prim.X[51] = qoco_solver->sol->x[51];
  CPG_Prim.X[52] = qoco_solver->sol->x[52];
  CPG_Prim.X[53] = qoco_solver->sol->x[53];
  CPG_Prim.X[54] = qoco_solver->sol->x[54];
  CPG_Prim.X[55] = qoco_solver->sol->x[55];
  CPG_Prim.X[56] = qoco_solver->sol->x[56];
  CPG_Prim.X[57] = qoco_solver->sol->x[57];
  CPG_Prim.X[58] = qoco_solver->sol->x[58];
  CPG_Prim.X[59] = qoco_solver->sol->x[59];
  CPG_Prim.X[60] = qoco_solver->sol->x[60];
  CPG_Prim.X[61] = qoco_solver->sol->x[61];
  CPG_Prim.X[62] = qoco_solver->sol->x[62];
  CPG_Prim.X[63] = qoco_solver->sol->x[63];
  CPG_Prim.X[64] = qoco_solver->sol->x[64];
  CPG_Prim.X[65] = qoco_solver->sol->x[65];
  CPG_Prim.X[66] = qoco_solver->sol->x[66];
  CPG_Prim.X[67] = qoco_solver->sol->x[67];
  CPG_Prim.X[68] = qoco_solver->sol->x[68];
  CPG_Prim.X[69] = qoco_solver->sol->x[69];
  CPG_Prim.U[0] = qoco_solver->sol->x[223];
  CPG_Prim.U[1] = qoco_solver->sol->x[224];
  CPG_Prim.U[2] = qoco_solver->sol->x[225];
  CPG_Prim.U[3] = qoco_solver->sol->x[226];
  CPG_Prim.U[4] = qoco_solver->sol->x[227];
  CPG_Prim.U[5] = qoco_solver->sol->x[228];
  CPG_Prim.U[6] = qoco_solver->sol->x[229];
  CPG_Prim.U[7] = qoco_solver->sol->x[230];
  CPG_Prim.U[8] = qoco_solver->sol->x[231];
  CPG_Prim.U[9] = qoco_solver->sol->x[232];
  CPG_Prim.U[10] = qoco_solver->sol->x[233];
  CPG_Prim.U[11] = qoco_solver->sol->x[234];
  CPG_Prim.U[12] = qoco_solver->sol->x[235];
  CPG_Prim.U[13] = qoco_solver->sol->x[236];
  CPG_Prim.U[14] = qoco_solver->sol->x[237];
  CPG_Prim.U[15] = qoco_solver->sol->x[238];
  CPG_Prim.U[16] = qoco_solver->sol->x[239];
  CPG_Prim.U[17] = qoco_solver->sol->x[240];
  CPG_Prim.U[18] = qoco_solver->sol->x[241];
  CPG_Prim.U[19] = qoco_solver->sol->x[242];
  CPG_Prim.V[0] = qoco_solver->sol->x[243];
  CPG_Prim.V[1] = qoco_solver->sol->x[244];
  CPG_Prim.V[2] = qoco_solver->sol->x[245];
  CPG_Prim.V[3] = qoco_solver->sol->x[246];
  CPG_Prim.V[4] = qoco_solver->sol->x[247];
  CPG_Prim.V[5] = qoco_solver->sol->x[248];
  CPG_Prim.V[6] = qoco_solver->sol->x[249];
  CPG_Prim.V[7] = qoco_solver->sol->x[250];
  CPG_Prim.V[8] = qoco_solver->sol->x[251];
  CPG_Prim.V[9] = qoco_solver->sol->x[252];
  CPG_Prim.V[10] = qoco_solver->sol->x[253];
  CPG_Prim.V[11] = qoco_solver->sol->x[254];
  CPG_Prim.V[12] = qoco_solver->sol->x[255];
  CPG_Prim.V[13] = qoco_solver->sol->x[256];
  CPG_Prim.V[14] = qoco_solver->sol->x[257];
  CPG_Prim.V[15] = qoco_solver->sol->x[258];
  CPG_Prim.V[16] = qoco_solver->sol->x[259];
  CPG_Prim.V[17] = qoco_solver->sol->x[260];
  CPG_Prim.V[18] = qoco_solver->sol->x[261];
  CPG_Prim.V[19] = qoco_solver->sol->x[262];
  CPG_Prim.V[20] = qoco_solver->sol->x[263];
  CPG_Prim.V[21] = qoco_solver->sol->x[264];
  CPG_Prim.V[22] = qoco_solver->sol->x[265];
  CPG_Prim.V[23] = qoco_solver->sol->x[266];
  CPG_Prim.V[24] = qoco_solver->sol->x[267];
  CPG_Prim.V[25] = qoco_solver->sol->x[268];
  CPG_Prim.V[26] = qoco_solver->sol->x[269];
  CPG_Prim.V[27] = qoco_solver->sol->x[270];
  CPG_Prim.V[28] = qoco_solver->sol->x[271];
  CPG_Prim.V[29] = qoco_solver->sol->x[272];
  CPG_Prim.V[30] = qoco_solver->sol->x[273];
  CPG_Prim.V[31] = qoco_solver->sol->x[274];
  CPG_Prim.V[32] = qoco_solver->sol->x[275];
  CPG_Prim.V[33] = qoco_solver->sol->x[276];
  CPG_Prim.V[34] = qoco_solver->sol->x[277];
  CPG_Prim.V[35] = qoco_solver->sol->x[278];
  CPG_Prim.V[36] = qoco_solver->sol->x[279];
  CPG_Prim.V[37] = qoco_solver->sol->x[280];
  CPG_Prim.V[38] = qoco_solver->sol->x[281];
  CPG_Prim.V[39] = qoco_solver->sol->x[282];
  CPG_Prim.V[40] = qoco_solver->sol->x[283];
  CPG_Prim.V[41] = qoco_solver->sol->x[284];
  CPG_Prim.V[42] = qoco_solver->sol->x[285];
  CPG_Prim.V[43] = qoco_solver->sol->x[286];
  CPG_Prim.V[44] = qoco_solver->sol->x[287];
  CPG_Prim.V[45] = qoco_solver->sol->x[288];
  CPG_Prim.V[46] = qoco_solver->sol->x[289];
  CPG_Prim.V[47] = qoco_solver->sol->x[290];
  CPG_Prim.V[48] = qoco_solver->sol->x[291];
  CPG_Prim.V[49] = qoco_solver->sol->x[292];
  CPG_Prim.V[50] = qoco_solver->sol->x[293];
  CPG_Prim.V[51] = qoco_solver->sol->x[294];
  CPG_Prim.V[52] = qoco_solver->sol->x[295];
  CPG_Prim.V[53] = qoco_solver->sol->x[296];
  CPG_Prim.V[54] = qoco_solver->sol->x[297];
  CPG_Prim.V[55] = qoco_solver->sol->x[298];
  CPG_Prim.v_0[0] = qoco_solver->sol->x[299];
  CPG_Prim.v_0[1] = qoco_solver->sol->x[300];
  CPG_Prim.v_0[2] = qoco_solver->sol->x[301];
  CPG_Prim.v_0[3] = qoco_solver->sol->x[302];
  CPG_Prim.v_0[4] = qoco_solver->sol->x[303];
  CPG_Prim.v_0[5] = qoco_solver->sol->x[304];
  CPG_Prim.v_0[6] = qoco_solver->sol->x[305];
  CPG_Prim.v_0[7] = qoco_solver->sol->x[306];
  CPG_Prim.v_0[8] = qoco_solver->sol->x[307];
  CPG_Prim.v_0[9] = qoco_solver->sol->x[308];
  CPG_Prim.v_0[10] = qoco_solver->sol->x[309];
  CPG_Prim.v_0[11] = qoco_solver->sol->x[310];
  CPG_Prim.v_0[12] = qoco_solver->sol->x[311];
  CPG_Prim.v_0[13] = qoco_solver->sol->x[312];
  CPG_Prim.v_N[0] = qoco_solver->sol->x[327];
  CPG_Prim.v_N[1] = qoco_solver->sol->x[328];
  CPG_Prim.v_N[2] = qoco_solver->sol->x[329];
  CPG_Prim.v_N[3] = qoco_solver->sol->x[330];
  CPG_Prim.v_N[4] = qoco_solver->sol->x[331];
  CPG_Prim.v_N[5] = qoco_solver->sol->x[332];
  CPG_Prim.v_N[6] = qoco_solver->sol->x[333];
  CPG_Prim.v_N[7] = qoco_solver->sol->x[334];
  CPG_Prim.v_N[8] = qoco_solver->sol->x[335];
  CPG_Prim.v_N[9] = qoco_solver->sol->x[336];
  CPG_Prim.v_N[10] = qoco_solver->sol->x[337];
  CPG_Prim.v_N[11] = qoco_solver->sol->x[338];
  CPG_Prim.v_N[12] = qoco_solver->sol->x[339];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = qoco_solver->sol->y[90];
  CPG_Dual.d0[1] = qoco_solver->sol->y[91];
  CPG_Dual.d0[2] = qoco_solver->sol->y[92];
  CPG_Dual.d0[3] = qoco_solver->sol->y[93];
  CPG_Dual.d0[4] = qoco_solver->sol->y[94];
  CPG_Dual.d0[5] = qoco_solver->sol->y[95];
  CPG_Dual.d0[6] = qoco_solver->sol->y[96];
  CPG_Dual.d0[7] = qoco_solver->sol->y[97];
  CPG_Dual.d0[8] = qoco_solver->sol->y[98];
  CPG_Dual.d0[9] = qoco_solver->sol->y[99];
  CPG_Dual.d0[10] = qoco_solver->sol->y[100];
  CPG_Dual.d0[11] = qoco_solver->sol->y[101];
  CPG_Dual.d0[12] = qoco_solver->sol->y[102];
  CPG_Dual.d0[13] = qoco_solver->sol->y[103];
  CPG_Dual.d1[0] = qoco_solver->sol->y[104];
  CPG_Dual.d1[1] = qoco_solver->sol->y[105];
  CPG_Dual.d1[2] = qoco_solver->sol->y[106];
  CPG_Dual.d1[3] = qoco_solver->sol->y[107];
  CPG_Dual.d1[4] = qoco_solver->sol->y[108];
  CPG_Dual.d1[5] = qoco_solver->sol->y[109];
  CPG_Dual.d1[6] = qoco_solver->sol->y[110];
  CPG_Dual.d1[7] = qoco_solver->sol->y[111];
  CPG_Dual.d1[8] = qoco_solver->sol->y[112];
  CPG_Dual.d1[9] = qoco_solver->sol->y[113];
  CPG_Dual.d1[10] = qoco_solver->sol->y[114];
  CPG_Dual.d1[11] = qoco_solver->sol->y[115];
  CPG_Dual.d1[12] = qoco_solver->sol->y[116];
  CPG_Dual.d1[13] = qoco_solver->sol->y[117];
  CPG_Dual.d2[0] = qoco_solver->sol->y[118];
  CPG_Dual.d2[1] = qoco_solver->sol->y[119];
  CPG_Dual.d2[2] = qoco_solver->sol->y[120];
  CPG_Dual.d2[3] = qoco_solver->sol->y[121];
  CPG_Dual.d2[4] = qoco_solver->sol->y[122];
  CPG_Dual.d2[5] = qoco_solver->sol->y[123];
  CPG_Dual.d2[6] = qoco_solver->sol->y[124];
  CPG_Dual.d2[7] = qoco_solver->sol->y[125];
  CPG_Dual.d2[8] = qoco_solver->sol->y[126];
  CPG_Dual.d2[9] = qoco_solver->sol->y[127];
  CPG_Dual.d2[10] = qoco_solver->sol->y[128];
  CPG_Dual.d2[11] = qoco_solver->sol->y[129];
  CPG_Dual.d2[12] = qoco_solver->sol->y[130];
  CPG_Dual.d2[13] = qoco_solver->sol->y[131];
  CPG_Dual.d3[0] = qoco_solver->sol->y[132];
  CPG_Dual.d3[1] = qoco_solver->sol->y[133];
  CPG_Dual.d3[2] = qoco_solver->sol->y[134];
  CPG_Dual.d3[3] = qoco_solver->sol->y[135];
  CPG_Dual.d3[4] = qoco_solver->sol->y[136];
  CPG_Dual.d3[5] = qoco_solver->sol->y[137];
  CPG_Dual.d3[6] = qoco_solver->sol->y[138];
  CPG_Dual.d3[7] = qoco_solver->sol->y[139];
  CPG_Dual.d3[8] = qoco_solver->sol->y[140];
  CPG_Dual.d3[9] = qoco_solver->sol->y[141];
  CPG_Dual.d3[10] = qoco_solver->sol->y[142];
  CPG_Dual.d3[11] = qoco_solver->sol->y[143];
  CPG_Dual.d3[12] = qoco_solver->sol->y[144];
  CPG_Dual.d3[13] = qoco_solver->sol->y[145];
  CPG_Dual.d4[0] = qoco_solver->sol->z[178];
  CPG_Dual.d4[1] = qoco_solver->sol->z[179];
  CPG_Dual.d4[2] = qoco_solver->sol->z[180];
  CPG_Dual.d4[3] = qoco_solver->sol->z[181];
  CPG_Dual.d4[4] = qoco_solver->sol->z[182];
  CPG_Dual.d5[0] = qoco_solver->sol->z[183];
  CPG_Dual.d5[1] = qoco_solver->sol->z[184];
  CPG_Dual.d5[2] = qoco_solver->sol->z[185];
  CPG_Dual.d5[3] = qoco_solver->sol->z[186];
  CPG_Dual.d5[4] = qoco_solver->sol->z[187];
  CPG_Dual.d6[0] = qoco_solver->sol->z[188];
  CPG_Dual.d6[1] = qoco_solver->sol->z[189];
  CPG_Dual.d6[2] = qoco_solver->sol->z[190];
  CPG_Dual.d6[3] = qoco_solver->sol->z[191];
  CPG_Dual.d6[4] = qoco_solver->sol->z[192];
  CPG_Dual.d7[0] = qoco_solver->sol->z[193];
  CPG_Dual.d7[1] = qoco_solver->sol->z[194];
  CPG_Dual.d7[2] = qoco_solver->sol->z[195];
  CPG_Dual.d7[3] = qoco_solver->sol->z[196];
  CPG_Dual.d7[4] = qoco_solver->sol->z[197];
  CPG_Dual.d8[0] = qoco_solver->sol->z[208];
  CPG_Dual.d8[1] = qoco_solver->sol->z[209];
  CPG_Dual.d8[2] = qoco_solver->sol->z[210];
  CPG_Dual.d8[3] = qoco_solver->sol->z[211];
  CPG_Dual.d8[4] = qoco_solver->sol->z[212];
  CPG_Dual.d9 = qoco_solver->sol->z[243];
  CPG_Dual.d10[0] = qoco_solver->sol->z[250];
  CPG_Dual.d10[1] = qoco_solver->sol->z[251];
  CPG_Dual.d10[2] = qoco_solver->sol->z[252];
  CPG_Dual.d11[0] = qoco_solver->sol->y[146];
  CPG_Dual.d11[1] = qoco_solver->sol->y[147];
  CPG_Dual.d11[2] = qoco_solver->sol->y[148];
  CPG_Dual.d11[3] = qoco_solver->sol->y[149];
  CPG_Dual.d11[4] = qoco_solver->sol->y[150];
  CPG_Dual.d11[5] = qoco_solver->sol->y[151];
  CPG_Dual.d11[6] = qoco_solver->sol->y[152];
  CPG_Dual.d11[7] = qoco_solver->sol->y[153];
  CPG_Dual.d11[8] = qoco_solver->sol->y[154];
  CPG_Dual.d11[9] = qoco_solver->sol->y[155];
  CPG_Dual.d11[10] = qoco_solver->sol->y[156];
  CPG_Dual.d11[11] = qoco_solver->sol->y[157];
  CPG_Dual.d11[12] = qoco_solver->sol->y[158];
  CPG_Dual.d11[13] = qoco_solver->sol->y[159];
  CPG_Dual.d11[14] = qoco_solver->sol->y[160];
  CPG_Dual.d11[15] = qoco_solver->sol->y[161];
  CPG_Dual.d11[16] = qoco_solver->sol->y[162];
  CPG_Dual.d11[17] = qoco_solver->sol->y[163];
  CPG_Dual.d11[18] = qoco_solver->sol->y[164];
  CPG_Dual.d11[19] = qoco_solver->sol->y[165];
  CPG_Dual.d11[20] = qoco_solver->sol->y[166];
  CPG_Dual.d11[21] = qoco_solver->sol->y[167];
  CPG_Dual.d11[22] = qoco_solver->sol->y[168];
  CPG_Dual.d11[23] = qoco_solver->sol->y[169];
  CPG_Dual.d11[24] = qoco_solver->sol->y[170];
  CPG_Dual.d11[25] = qoco_solver->sol->y[171];
  CPG_Dual.d11[26] = qoco_solver->sol->y[172];
  CPG_Dual.d11[27] = qoco_solver->sol->y[173];
  CPG_Dual.d11[28] = qoco_solver->sol->y[174];
  CPG_Dual.d11[29] = qoco_solver->sol->y[175];
  CPG_Dual.d11[30] = qoco_solver->sol->y[176];
  CPG_Dual.d11[31] = qoco_solver->sol->y[177];
  CPG_Dual.d11[32] = qoco_solver->sol->y[178];
  CPG_Dual.d11[33] = qoco_solver->sol->y[179];
  CPG_Dual.d11[34] = qoco_solver->sol->y[180];
  CPG_Dual.d11[35] = qoco_solver->sol->y[181];
  CPG_Dual.d11[36] = qoco_solver->sol->y[182];
  CPG_Dual.d11[37] = qoco_solver->sol->y[183];
  CPG_Dual.d11[38] = qoco_solver->sol->y[184];
  CPG_Dual.d11[39] = qoco_solver->sol->y[185];
  CPG_Dual.d11[40] = qoco_solver->sol->y[186];
  CPG_Dual.d11[41] = qoco_solver->sol->y[187];
  CPG_Dual.d11[42] = qoco_solver->sol->y[188];
  CPG_Dual.d11[43] = qoco_solver->sol->y[189];
  CPG_Dual.d11[44] = qoco_solver->sol->y[190];
  CPG_Dual.d11[45] = qoco_solver->sol->y[191];
  CPG_Dual.d11[46] = qoco_solver->sol->y[192];
  CPG_Dual.d11[47] = qoco_solver->sol->y[193];
  CPG_Dual.d11[48] = qoco_solver->sol->y[194];
  CPG_Dual.d11[49] = qoco_solver->sol->y[195];
  CPG_Dual.d11[50] = qoco_solver->sol->y[196];
  CPG_Dual.d11[51] = qoco_solver->sol->y[197];
  CPG_Dual.d11[52] = qoco_solver->sol->y[198];
  CPG_Dual.d11[53] = qoco_solver->sol->y[199];
  CPG_Dual.d11[54] = qoco_solver->sol->y[200];
  CPG_Dual.d11[55] = qoco_solver->sol->y[201];
  CPG_Dual.d11[56] = qoco_solver->sol->y[202];
  CPG_Dual.d11[57] = qoco_solver->sol->y[203];
  CPG_Dual.d11[58] = qoco_solver->sol->y[204];
  CPG_Dual.d11[59] = qoco_solver->sol->y[205];
  CPG_Dual.d11[60] = qoco_solver->sol->y[206];
  CPG_Dual.d11[61] = qoco_solver->sol->y[207];
  CPG_Dual.d11[62] = qoco_solver->sol->y[208];
  CPG_Dual.d11[63] = qoco_solver->sol->y[209];
  CPG_Dual.d11[64] = qoco_solver->sol->y[210];
  CPG_Dual.d11[65] = qoco_solver->sol->y[211];
  CPG_Dual.d11[66] = qoco_solver->sol->y[212];
  CPG_Dual.d11[67] = qoco_solver->sol->y[213];
  CPG_Dual.d11[68] = qoco_solver->sol->y[214];
  CPG_Dual.d11[69] = qoco_solver->sol->y[215];
  CPG_Dual.d11[70] = qoco_solver->sol->y[216];
  CPG_Dual.d11[71] = qoco_solver->sol->y[217];
  CPG_Dual.d11[72] = qoco_solver->sol->y[218];
  CPG_Dual.d11[73] = qoco_solver->sol->y[219];
  CPG_Dual.d11[74] = qoco_solver->sol->y[220];
  CPG_Dual.d11[75] = qoco_solver->sol->y[221];
  CPG_Dual.d11[76] = qoco_solver->sol->y[222];
  CPG_Dual.d11[77] = qoco_solver->sol->y[223];
  CPG_Dual.d11[78] = qoco_solver->sol->y[224];
  CPG_Dual.d11[79] = qoco_solver->sol->y[225];
  CPG_Dual.d11[80] = qoco_solver->sol->y[226];
  CPG_Dual.d11[81] = qoco_solver->sol->y[227];
  CPG_Dual.d11[82] = qoco_solver->sol->y[228];
  CPG_Dual.d11[83] = qoco_solver->sol->y[229];
  CPG_Dual.d11[84] = qoco_solver->sol->y[230];
  CPG_Dual.d11[85] = qoco_solver->sol->y[231];
  CPG_Dual.d11[86] = qoco_solver->sol->y[232];
  CPG_Dual.d11[87] = qoco_solver->sol->y[233];
  CPG_Dual.d11[88] = qoco_solver->sol->y[234];
  CPG_Dual.d11[89] = qoco_solver->sol->y[235];
  CPG_Dual.d11[90] = qoco_solver->sol->y[236];
  CPG_Dual.d11[91] = qoco_solver->sol->y[237];
  CPG_Dual.d11[92] = qoco_solver->sol->y[238];
  CPG_Dual.d11[93] = qoco_solver->sol->y[239];
  CPG_Dual.d11[94] = qoco_solver->sol->y[240];
  CPG_Dual.d11[95] = qoco_solver->sol->y[241];
  CPG_Dual.d11[96] = qoco_solver->sol->y[242];
  CPG_Dual.d11[97] = qoco_solver->sol->y[243];
  CPG_Dual.d11[98] = qoco_solver->sol->y[244];
  CPG_Dual.d11[99] = qoco_solver->sol->y[245];
  CPG_Dual.d11[100] = qoco_solver->sol->y[246];
  CPG_Dual.d11[101] = qoco_solver->sol->y[247];
  CPG_Dual.d11[102] = qoco_solver->sol->y[248];
  CPG_Dual.d11[103] = qoco_solver->sol->y[249];
  CPG_Dual.d11[104] = qoco_solver->sol->y[250];
  CPG_Dual.d11[105] = qoco_solver->sol->y[251];
  CPG_Dual.d11[106] = qoco_solver->sol->y[252];
  CPG_Dual.d11[107] = qoco_solver->sol->y[253];
  CPG_Dual.d11[108] = qoco_solver->sol->y[254];
  CPG_Dual.d11[109] = qoco_solver->sol->y[255];
  CPG_Dual.d11[110] = qoco_solver->sol->y[256];
  CPG_Dual.d11[111] = qoco_solver->sol->y[257];
  CPG_Dual.d11[112] = qoco_solver->sol->y[258];
  CPG_Dual.d11[113] = qoco_solver->sol->y[259];
  CPG_Dual.d11[114] = qoco_solver->sol->y[260];
  CPG_Dual.d11[115] = qoco_solver->sol->y[261];
  CPG_Dual.d11[116] = qoco_solver->sol->y[262];
  CPG_Dual.d11[117] = qoco_solver->sol->y[263];
  CPG_Dual.d11[118] = qoco_solver->sol->y[264];
  CPG_Dual.d11[119] = qoco_solver->sol->y[265];
  CPG_Dual.d11[120] = qoco_solver->sol->y[266];
  CPG_Dual.d11[121] = qoco_solver->sol->y[267];
  CPG_Dual.d11[122] = qoco_solver->sol->y[268];
  CPG_Dual.d11[123] = qoco_solver->sol->y[269];
  CPG_Dual.d11[124] = qoco_solver->sol->y[270];
  CPG_Dual.d11[125] = qoco_solver->sol->y[271];
  CPG_Dual.d11[126] = qoco_solver->sol->y[272];
  CPG_Dual.d11[127] = qoco_solver->sol->y[273];
  CPG_Dual.d11[128] = qoco_solver->sol->y[274];
  CPG_Dual.d11[129] = qoco_solver->sol->y[275];
  CPG_Dual.d11[130] = qoco_solver->sol->y[276];
  CPG_Dual.d11[131] = qoco_solver->sol->y[277];
  CPG_Dual.d11[132] = qoco_solver->sol->y[278];
  CPG_Dual.d11[133] = qoco_solver->sol->y[279];
  CPG_Dual.d11[134] = qoco_solver->sol->y[280];
  CPG_Dual.d11[135] = qoco_solver->sol->y[281];
  CPG_Dual.d11[136] = qoco_solver->sol->y[282];
  CPG_Dual.d11[137] = qoco_solver->sol->y[283];
  CPG_Dual.d11[138] = qoco_solver->sol->y[284];
  CPG_Dual.d11[139] = qoco_solver->sol->y[285];
  CPG_Dual.d11[140] = qoco_solver->sol->y[286];
  CPG_Dual.d11[141] = qoco_solver->sol->y[287];
  CPG_Dual.d11[142] = qoco_solver->sol->y[288];
  CPG_Dual.d11[143] = qoco_solver->sol->y[289];
  CPG_Dual.d11[144] = qoco_solver->sol->y[290];
  CPG_Dual.d11[145] = qoco_solver->sol->y[291];
  CPG_Dual.d11[146] = qoco_solver->sol->y[292];
  CPG_Dual.d11[147] = qoco_solver->sol->y[293];
  CPG_Dual.d11[148] = qoco_solver->sol->y[294];
  CPG_Dual.d11[149] = qoco_solver->sol->y[295];
  CPG_Dual.d11[150] = qoco_solver->sol->y[296];
  CPG_Dual.d11[151] = qoco_solver->sol->y[297];
  CPG_Dual.d11[152] = qoco_solver->sol->y[298];
  CPG_Dual.d11[153] = qoco_solver->sol->y[299];
  CPG_Dual.d11[154] = qoco_solver->sol->y[300];
  CPG_Dual.d11[155] = qoco_solver->sol->y[301];
  CPG_Dual.d11[156] = qoco_solver->sol->y[302];
  CPG_Dual.d11[157] = qoco_solver->sol->y[303];
  CPG_Dual.d11[158] = qoco_solver->sol->y[304];
  CPG_Dual.d11[159] = qoco_solver->sol->y[305];
  CPG_Dual.d11[160] = qoco_solver->sol->y[306];
  CPG_Dual.d11[161] = qoco_solver->sol->y[307];
  CPG_Dual.d11[162] = qoco_solver->sol->y[308];
  CPG_Dual.d11[163] = qoco_solver->sol->y[309];
  CPG_Dual.d11[164] = qoco_solver->sol->y[310];
  CPG_Dual.d11[165] = qoco_solver->sol->y[311];
  CPG_Dual.d11[166] = qoco_solver->sol->y[312];
  CPG_Dual.d11[167] = qoco_solver->sol->y[313];
  CPG_Dual.d11[168] = qoco_solver->sol->y[314];
  CPG_Dual.d11[169] = qoco_solver->sol->y[315];
  CPG_Dual.d11[170] = qoco_solver->sol->y[316];
  CPG_Dual.d11[171] = qoco_solver->sol->y[317];
  CPG_Dual.d11[172] = qoco_solver->sol->y[318];
  CPG_Dual.d11[173] = qoco_solver->sol->y[319];
  CPG_Dual.d11[174] = qoco_solver->sol->y[320];
  CPG_Dual.d11[175] = qoco_solver->sol->y[321];
  CPG_Dual.d11[176] = qoco_solver->sol->y[322];
  CPG_Dual.d11[177] = qoco_solver->sol->y[323];
  CPG_Dual.d11[178] = qoco_solver->sol->y[324];
  CPG_Dual.d11[179] = qoco_solver->sol->y[325];
  CPG_Dual.d11[180] = qoco_solver->sol->y[326];
  CPG_Dual.d11[181] = qoco_solver->sol->y[327];
  CPG_Dual.d11[182] = qoco_solver->sol->y[328];
  CPG_Dual.d11[183] = qoco_solver->sol->y[329];
  CPG_Dual.d11[184] = qoco_solver->sol->y[330];
  CPG_Dual.d11[185] = qoco_solver->sol->y[331];
  CPG_Dual.d11[186] = qoco_solver->sol->y[332];
  CPG_Dual.d11[187] = qoco_solver->sol->y[333];
  CPG_Dual.d11[188] = qoco_solver->sol->y[334];
  CPG_Dual.d11[189] = qoco_solver->sol->y[335];
  CPG_Dual.d11[190] = qoco_solver->sol->y[336];
  CPG_Dual.d11[191] = qoco_solver->sol->y[337];
  CPG_Dual.d11[192] = qoco_solver->sol->y[338];
  CPG_Dual.d11[193] = qoco_solver->sol->y[339];
  CPG_Dual.d11[194] = qoco_solver->sol->y[340];
  CPG_Dual.d11[195] = qoco_solver->sol->y[341];
  CPG_Dual.d12[0] = qoco_solver->sol->y[342];
  CPG_Dual.d12[1] = qoco_solver->sol->y[343];
  CPG_Dual.d12[2] = qoco_solver->sol->y[344];
  CPG_Dual.d12[3] = qoco_solver->sol->y[345];
  CPG_Dual.d12[4] = qoco_solver->sol->y[346];
  CPG_Dual.d12[5] = qoco_solver->sol->y[347];
  CPG_Dual.d12[6] = qoco_solver->sol->y[348];
  CPG_Dual.d12[7] = qoco_solver->sol->y[349];
  CPG_Dual.d12[8] = qoco_solver->sol->y[350];
  CPG_Dual.d12[9] = qoco_solver->sol->y[351];
  CPG_Dual.d12[10] = qoco_solver->sol->y[352];
  CPG_Dual.d12[11] = qoco_solver->sol->y[353];
  CPG_Dual.d12[12] = qoco_solver->sol->y[354];
  CPG_Dual.d12[13] = qoco_solver->sol->y[355];
  CPG_Dual.d12[14] = qoco_solver->sol->y[356];
  CPG_Dual.d12[15] = qoco_solver->sol->y[357];
  CPG_Dual.d12[16] = qoco_solver->sol->y[358];
  CPG_Dual.d12[17] = qoco_solver->sol->y[359];
  CPG_Dual.d12[18] = qoco_solver->sol->y[360];
  CPG_Dual.d12[19] = qoco_solver->sol->y[361];
  CPG_Dual.d12[20] = qoco_solver->sol->y[362];
  CPG_Dual.d12[21] = qoco_solver->sol->y[363];
  CPG_Dual.d12[22] = qoco_solver->sol->y[364];
  CPG_Dual.d12[23] = qoco_solver->sol->y[365];
  CPG_Dual.d12[24] = qoco_solver->sol->y[366];
  CPG_Dual.d12[25] = qoco_solver->sol->y[367];
  CPG_Dual.d12[26] = qoco_solver->sol->y[368];
  CPG_Dual.d12[27] = qoco_solver->sol->y[369];
  CPG_Dual.d12[28] = qoco_solver->sol->y[370];
  CPG_Dual.d12[29] = qoco_solver->sol->y[371];
  CPG_Dual.d12[30] = qoco_solver->sol->y[372];
  CPG_Dual.d12[31] = qoco_solver->sol->y[373];
  CPG_Dual.d12[32] = qoco_solver->sol->y[374];
  CPG_Dual.d12[33] = qoco_solver->sol->y[375];
  CPG_Dual.d12[34] = qoco_solver->sol->y[376];
  CPG_Dual.d12[35] = qoco_solver->sol->y[377];
  CPG_Dual.d12[36] = qoco_solver->sol->y[378];
  CPG_Dual.d12[37] = qoco_solver->sol->y[379];
  CPG_Dual.d12[38] = qoco_solver->sol->y[380];
  CPG_Dual.d12[39] = qoco_solver->sol->y[381];
  CPG_Dual.d12[40] = qoco_solver->sol->y[382];
  CPG_Dual.d12[41] = qoco_solver->sol->y[383];
  CPG_Dual.d12[42] = qoco_solver->sol->y[384];
  CPG_Dual.d12[43] = qoco_solver->sol->y[385];
  CPG_Dual.d12[44] = qoco_solver->sol->y[386];
  CPG_Dual.d12[45] = qoco_solver->sol->y[387];
  CPG_Dual.d12[46] = qoco_solver->sol->y[388];
  CPG_Dual.d12[47] = qoco_solver->sol->y[389];
  CPG_Dual.d12[48] = qoco_solver->sol->y[390];
  CPG_Dual.d12[49] = qoco_solver->sol->y[391];
  CPG_Dual.d12[50] = qoco_solver->sol->y[392];
  CPG_Dual.d12[51] = qoco_solver->sol->y[393];
  CPG_Dual.d12[52] = qoco_solver->sol->y[394];
  CPG_Dual.d12[53] = qoco_solver->sol->y[395];
  CPG_Dual.d12[54] = qoco_solver->sol->y[396];
  CPG_Dual.d12[55] = qoco_solver->sol->y[397];
  CPG_Dual.d12[56] = qoco_solver->sol->y[398];
  CPG_Dual.d12[57] = qoco_solver->sol->y[399];
  CPG_Dual.d12[58] = qoco_solver->sol->y[400];
  CPG_Dual.d12[59] = qoco_solver->sol->y[401];
  CPG_Dual.d12[60] = qoco_solver->sol->y[402];
  CPG_Dual.d12[61] = qoco_solver->sol->y[403];
  CPG_Dual.d12[62] = qoco_solver->sol->y[404];
  CPG_Dual.d12[63] = qoco_solver->sol->y[405];
  CPG_Dual.d12[64] = qoco_solver->sol->y[406];
  CPG_Dual.d12[65] = qoco_solver->sol->y[407];
  CPG_Dual.d12[66] = qoco_solver->sol->y[408];
  CPG_Dual.d12[67] = qoco_solver->sol->y[409];
  CPG_Dual.d12[68] = qoco_solver->sol->y[410];
  CPG_Dual.d12[69] = qoco_solver->sol->y[411];
  CPG_Dual.d12[70] = qoco_solver->sol->y[412];
  CPG_Dual.d12[71] = qoco_solver->sol->y[413];
  CPG_Dual.d12[72] = qoco_solver->sol->y[414];
  CPG_Dual.d12[73] = qoco_solver->sol->y[415];
  CPG_Dual.d12[74] = qoco_solver->sol->y[416];
  CPG_Dual.d12[75] = qoco_solver->sol->y[417];
  CPG_Dual.d12[76] = qoco_solver->sol->y[418];
  CPG_Dual.d12[77] = qoco_solver->sol->y[419];
  CPG_Dual.d12[78] = qoco_solver->sol->y[420];
  CPG_Dual.d12[79] = qoco_solver->sol->y[421];
  CPG_Dual.d12[80] = qoco_solver->sol->y[422];
  CPG_Dual.d12[81] = qoco_solver->sol->y[423];
  CPG_Dual.d12[82] = qoco_solver->sol->y[424];
  CPG_Dual.d12[83] = qoco_solver->sol->y[425];
  CPG_Dual.d12[84] = qoco_solver->sol->y[426];
  CPG_Dual.d12[85] = qoco_solver->sol->y[427];
  CPG_Dual.d12[86] = qoco_solver->sol->y[428];
  CPG_Dual.d12[87] = qoco_solver->sol->y[429];
  CPG_Dual.d12[88] = qoco_solver->sol->y[430];
  CPG_Dual.d12[89] = qoco_solver->sol->y[431];
  CPG_Dual.d12[90] = qoco_solver->sol->y[432];
  CPG_Dual.d12[91] = qoco_solver->sol->y[433];
  CPG_Dual.d12[92] = qoco_solver->sol->y[434];
  CPG_Dual.d12[93] = qoco_solver->sol->y[435];
  CPG_Dual.d12[94] = qoco_solver->sol->y[436];
  CPG_Dual.d12[95] = qoco_solver->sol->y[437];
  CPG_Dual.d12[96] = qoco_solver->sol->y[438];
  CPG_Dual.d12[97] = qoco_solver->sol->y[439];
  CPG_Dual.d12[98] = qoco_solver->sol->y[440];
  CPG_Dual.d12[99] = qoco_solver->sol->y[441];
  CPG_Dual.d12[100] = qoco_solver->sol->y[442];
  CPG_Dual.d12[101] = qoco_solver->sol->y[443];
  CPG_Dual.d12[102] = qoco_solver->sol->y[444];
  CPG_Dual.d12[103] = qoco_solver->sol->y[445];
  CPG_Dual.d12[104] = qoco_solver->sol->y[446];
  CPG_Dual.d12[105] = qoco_solver->sol->y[447];
  CPG_Dual.d12[106] = qoco_solver->sol->y[448];
  CPG_Dual.d12[107] = qoco_solver->sol->y[449];
  CPG_Dual.d12[108] = qoco_solver->sol->y[450];
  CPG_Dual.d12[109] = qoco_solver->sol->y[451];
  CPG_Dual.d12[110] = qoco_solver->sol->y[452];
  CPG_Dual.d12[111] = qoco_solver->sol->y[453];
  CPG_Dual.d12[112] = qoco_solver->sol->y[454];
  CPG_Dual.d12[113] = qoco_solver->sol->y[455];
  CPG_Dual.d12[114] = qoco_solver->sol->y[456];
  CPG_Dual.d12[115] = qoco_solver->sol->y[457];
  CPG_Dual.d12[116] = qoco_solver->sol->y[458];
  CPG_Dual.d12[117] = qoco_solver->sol->y[459];
  CPG_Dual.d12[118] = qoco_solver->sol->y[460];
  CPG_Dual.d12[119] = qoco_solver->sol->y[461];
  CPG_Dual.d12[120] = qoco_solver->sol->y[462];
  CPG_Dual.d12[121] = qoco_solver->sol->y[463];
  CPG_Dual.d12[122] = qoco_solver->sol->y[464];
  CPG_Dual.d12[123] = qoco_solver->sol->y[465];
  CPG_Dual.d12[124] = qoco_solver->sol->y[466];
  CPG_Dual.d12[125] = qoco_solver->sol->y[467];
  CPG_Dual.d12[126] = qoco_solver->sol->y[468];
  CPG_Dual.d12[127] = qoco_solver->sol->y[469];
  CPG_Dual.d12[128] = qoco_solver->sol->y[470];
  CPG_Dual.d12[129] = qoco_solver->sol->y[471];
  CPG_Dual.d12[130] = qoco_solver->sol->y[472];
  CPG_Dual.d12[131] = qoco_solver->sol->y[473];
  CPG_Dual.d12[132] = qoco_solver->sol->y[474];
  CPG_Dual.d12[133] = qoco_solver->sol->y[475];
  CPG_Dual.d12[134] = qoco_solver->sol->y[476];
  CPG_Dual.d12[135] = qoco_solver->sol->y[477];
  CPG_Dual.d12[136] = qoco_solver->sol->y[478];
  CPG_Dual.d12[137] = qoco_solver->sol->y[479];
  CPG_Dual.d12[138] = qoco_solver->sol->y[480];
  CPG_Dual.d12[139] = qoco_solver->sol->y[481];
  CPG_Dual.d12[140] = qoco_solver->sol->y[482];
  CPG_Dual.d12[141] = qoco_solver->sol->y[483];
  CPG_Dual.d12[142] = qoco_solver->sol->y[484];
  CPG_Dual.d12[143] = qoco_solver->sol->y[485];
  CPG_Dual.d12[144] = qoco_solver->sol->y[486];
  CPG_Dual.d12[145] = qoco_solver->sol->y[487];
  CPG_Dual.d12[146] = qoco_solver->sol->y[488];
  CPG_Dual.d12[147] = qoco_solver->sol->y[489];
  CPG_Dual.d12[148] = qoco_solver->sol->y[490];
  CPG_Dual.d12[149] = qoco_solver->sol->y[491];
  CPG_Dual.d12[150] = qoco_solver->sol->y[492];
  CPG_Dual.d12[151] = qoco_solver->sol->y[493];
  CPG_Dual.d12[152] = qoco_solver->sol->y[494];
  CPG_Dual.d12[153] = qoco_solver->sol->y[495];
  CPG_Dual.d12[154] = qoco_solver->sol->y[496];
  CPG_Dual.d12[155] = qoco_solver->sol->y[497];
  CPG_Dual.d12[156] = qoco_solver->sol->y[498];
  CPG_Dual.d12[157] = qoco_solver->sol->y[499];
  CPG_Dual.d12[158] = qoco_solver->sol->y[500];
  CPG_Dual.d12[159] = qoco_solver->sol->y[501];
  CPG_Dual.d12[160] = qoco_solver->sol->y[502];
  CPG_Dual.d12[161] = qoco_solver->sol->y[503];
  CPG_Dual.d12[162] = qoco_solver->sol->y[504];
  CPG_Dual.d12[163] = qoco_solver->sol->y[505];
  CPG_Dual.d12[164] = qoco_solver->sol->y[506];
  CPG_Dual.d12[165] = qoco_solver->sol->y[507];
  CPG_Dual.d12[166] = qoco_solver->sol->y[508];
  CPG_Dual.d12[167] = qoco_solver->sol->y[509];
  CPG_Dual.d12[168] = qoco_solver->sol->y[510];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_solver->sol->obj + Canon_Params.d);
  CPG_Info.iter = qoco_solver->sol->iters;
  CPG_Info.status = qoco_solver->sol->status;
  CPG_Info.pri_res = qoco_solver->sol->pres;
  CPG_Info.dua_res = qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_P(){
  for (i=0; i<90; i++){
    Canon_Params_conditioning.P->x[i] = Canon_Params.P->x[i];
  }
}

void cpg_copy_c(){
  for (i=0; i<372; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<2254; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<511; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<544; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<288; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_P();
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (!qoco_solver ) {
    cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   qoco_set_csc(P, 372, 372, Canon_Params.P->nnz, Canon_Params.P->x, Canon_Params.P->p, Canon_Params.P->i);
   qoco_set_csc(A, 511, 372, Canon_Params.A->nnz, Canon_Params.A->x, Canon_Params.A->p, Canon_Params.A->i);
   qoco_set_csc(G, 288, 372, Canon_Params.G->nnz, Canon_Params.G->x, Canon_Params.G->p, Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(qoco_solver, 372, 288, 511, P, Canon_Params.c, A, Canon_Params.b, G, Canon_Params.h, 253, 10, (int *) &qoco_q, qoco_settings);
  }
  if (Canon_Outdated.b) {
    update_vector_data(qoco_solver, NULL, Canon_Params.b, NULL);
  }
  if (Canon_Outdated.A) {
    update_matrix_data(qoco_solver, NULL, Canon_Params.A->x, NULL);
  }
  qoco_solver->settings->max_iters = Canon_Settings.max_iters;
  qoco_solver->settings->bisect_iters = Canon_Settings.bisect_iters;
  qoco_solver->settings->ruiz_iters = Canon_Settings.ruiz_iters;
  qoco_solver->settings->iter_ref_iters = Canon_Settings.iter_ref_iters;
  qoco_solver->settings->kkt_static_reg = Canon_Settings.kkt_static_reg;
  qoco_solver->settings->kkt_dynamic_reg = Canon_Settings.kkt_dynamic_reg;
  qoco_solver->settings->abstol = Canon_Settings.abstol;
  qoco_solver->settings->reltol = Canon_Settings.reltol;
  qoco_solver->settings->abstol_inacc = Canon_Settings.abstol_inacc;
  qoco_solver->settings->reltol_inacc = Canon_Settings.reltol_inacc;
  qoco_solver->settings->verbose = Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(qoco_solver);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.max_iters = 200;
  Canon_Settings.bisect_iters = 5;
  Canon_Settings.ruiz_iters = 0;
  Canon_Settings.iter_ref_iters = 1;
  Canon_Settings.kkt_static_reg = 1e-8;
  Canon_Settings.kkt_dynamic_reg = 1e-8;
  Canon_Settings.abstol = 1e-7;
  Canon_Settings.reltol = 1e-7;
  Canon_Settings.abstol_inacc = 1e-5;
  Canon_Settings.reltol_inacc = 1e-5;
  Canon_Settings.verbose = 0;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  Canon_Settings.bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}
