
/*
Auto-generated by CVXPYgen on September 21, 2025 at 13:18:33.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_x_ref(0, 0.78868360277136262404);
  cpg_update_u_ref(0, 0.07272727272727881609);
  cpg_update_Ak_0(0, 1.00000000000000000000);
  cpg_update_Bk_minus_0(0, 0.00000000000000042245);
  cpg_update_Bk_plus_0(0, 0.00000000000000043242);
  cpg_update_ck(0, -0.00000000000009237056);
  cpg_update_Ak_1(0, 1.00000000000000000000);
  cpg_update_Bk_minus_1(0, 0.00000000000000136236);
  cpg_update_Bk_plus_1(0, 0.00000000000000134169);
  cpg_update_Ak_2(0, 1.00000000000000000000);
  cpg_update_Bk_minus_2(0, 0.00000000000000232261);
  cpg_update_Bk_plus_2(0, 0.00000000000000229044);
  cpg_update_Ak_3(0, 1.00000000000000000000);
  cpg_update_Bk_minus_3(0, 0.00000000000000330054);
  cpg_update_Bk_plus_3(0, 0.00000000000000326417);
  cpg_update_x_0(0, 0.25000000000000000000);
  cpg_update_x_f(0, 0.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<70; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<20; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }
  for(i=0; i<56; i++) {
    printf("V[%d] = %f\n", i, CPG_Result.prim->V[i]);
  }
  for(i=0; i<14; i++) {
    printf("v_0[%d] = %f\n", i, CPG_Result.prim->v_0[i]);
  }
  for(i=0; i<13; i++) {
    printf("v_N[%d] = %f\n", i, CPG_Result.prim->v_N[i]);
  }

  // Print dual solution
  for(i=0; i<14; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<14; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<14; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<14; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<5; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<5; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<5; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<5; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<5; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  printf("d9 = %f\n", CPG_Result.dual->d9);
  for(i=0; i<3; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<196; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<169; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }

  return 0;

}
