
/*
Auto-generated by CVXPYgen on September 21, 2025 at 13:04:36.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_x_ref(0, 0.78868360277136262404);
  cpg_update_u_ref(0, 0.07272727272727881609);
  cpg_update_Ak_0(0, 1.00000000000000000000);
  cpg_update_Bk_minus_0(0, -0.00000000000000013961);
  cpg_update_Bk_plus_0(0, -0.00000000000000007715);
  cpg_update_ck(0, 0.00000000000000141553);
  cpg_update_Ak_1(0, 1.00000000000000000000);
  cpg_update_Bk_minus_1(0, -0.00000000000000024926);
  cpg_update_Bk_plus_1(0, -0.00000000000000012487);
  cpg_update_Ak_2(0, 1.00000000000000000000);
  cpg_update_Bk_minus_2(0, -0.00000000000000036017);
  cpg_update_Bk_plus_2(0, -0.00000000000000017281);
  cpg_update_Ak_3(0, 1.00000000000000000000);
  cpg_update_Bk_minus_3(0, -0.00000000000000047117);
  cpg_update_Bk_plus_3(0, -0.00000000000000021666);
  cpg_update_Ak_4(0, 1.00000000000000000000);
  cpg_update_Bk_minus_4(0, -0.00000000000000058412);
  cpg_update_Bk_plus_4(0, -0.00000000000000027208);
  cpg_update_Ak_5(0, 1.00000000000000000000);
  cpg_update_Bk_minus_5(0, -0.00000000000000069731);
  cpg_update_Bk_plus_5(0, -0.00000000000000031856);
  cpg_update_Ak_6(0, 1.00000000000000000000);
  cpg_update_Bk_minus_6(0, -0.00000000000000081129);
  cpg_update_Bk_plus_6(0, -0.00000000000000036624);
  cpg_update_Ak_7(0, 1.00000000000000000000);
  cpg_update_Bk_minus_7(0, -0.00000000000000092673);
  cpg_update_Bk_plus_7(0, -0.00000000000000042068);
  cpg_update_Ak_8(0, 1.00000000000000000000);
  cpg_update_Bk_minus_8(0, -0.00000000000000104236);
  cpg_update_Bk_plus_8(0, -0.00000000000000046447);
  cpg_update_x_0(0, 0.25000000000000000000);
  cpg_update_x_f(0, 0.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<140; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<40; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }
  for(i=0; i<126; i++) {
    printf("V[%d] = %f\n", i, CPG_Result.prim->V[i]);
  }
  for(i=0; i<14; i++) {
    printf("v_0[%d] = %f\n", i, CPG_Result.prim->v_0[i]);
  }
  for(i=0; i<13; i++) {
    printf("v_N[%d] = %f\n", i, CPG_Result.prim->v_N[i]);
  }

  // Print dual solution
  for(i=0; i<14; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<14; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<14; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<14; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<14; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<14; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<14; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<14; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<14; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<10; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<10; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<10; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<10; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<10; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  printf("d14 = %f\n", CPG_Result.dual->d14);
  for(i=0; i<8; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<196; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<169; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }

  return 0;

}
