
/*
Auto-generated by CVXPYgen on September 21, 2025 at 13:04:36.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_x_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_u_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+140] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+180] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+376] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+432] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_ck(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+488] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+614] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+810] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+866] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+922] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1118] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1174] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1230] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1426] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1482] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1538] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1734] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1790] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1846] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2042] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2098] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2154] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2350] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2406] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2462] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2658] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2714] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2770] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2966] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3022] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_x_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3078] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_x_f(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3092] = val;
  Canon_Outdated.b = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<4114; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<671; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.X[0] = qoco_solver->sol->x[0];
  CPG_Prim.X[1] = qoco_solver->sol->x[1];
  CPG_Prim.X[2] = qoco_solver->sol->x[2];
  CPG_Prim.X[3] = qoco_solver->sol->x[3];
  CPG_Prim.X[4] = qoco_solver->sol->x[4];
  CPG_Prim.X[5] = qoco_solver->sol->x[5];
  CPG_Prim.X[6] = qoco_solver->sol->x[6];
  CPG_Prim.X[7] = qoco_solver->sol->x[7];
  CPG_Prim.X[8] = qoco_solver->sol->x[8];
  CPG_Prim.X[9] = qoco_solver->sol->x[9];
  CPG_Prim.X[10] = qoco_solver->sol->x[10];
  CPG_Prim.X[11] = qoco_solver->sol->x[11];
  CPG_Prim.X[12] = qoco_solver->sol->x[12];
  CPG_Prim.X[13] = qoco_solver->sol->x[13];
  CPG_Prim.X[14] = qoco_solver->sol->x[14];
  CPG_Prim.X[15] = qoco_solver->sol->x[15];
  CPG_Prim.X[16] = qoco_solver->sol->x[16];
  CPG_Prim.X[17] = qoco_solver->sol->x[17];
  CPG_Prim.X[18] = qoco_solver->sol->x[18];
  CPG_Prim.X[19] = qoco_solver->sol->x[19];
  CPG_Prim.X[20] = qoco_solver->sol->x[20];
  CPG_Prim.X[21] = qoco_solver->sol->x[21];
  CPG_Prim.X[22] = qoco_solver->sol->x[22];
  CPG_Prim.X[23] = qoco_solver->sol->x[23];
  CPG_Prim.X[24] = qoco_solver->sol->x[24];
  CPG_Prim.X[25] = qoco_solver->sol->x[25];
  CPG_Prim.X[26] = qoco_solver->sol->x[26];
  CPG_Prim.X[27] = qoco_solver->sol->x[27];
  CPG_Prim.X[28] = qoco_solver->sol->x[28];
  CPG_Prim.X[29] = qoco_solver->sol->x[29];
  CPG_Prim.X[30] = qoco_solver->sol->x[30];
  CPG_Prim.X[31] = qoco_solver->sol->x[31];
  CPG_Prim.X[32] = qoco_solver->sol->x[32];
  CPG_Prim.X[33] = qoco_solver->sol->x[33];
  CPG_Prim.X[34] = qoco_solver->sol->x[34];
  CPG_Prim.X[35] = qoco_solver->sol->x[35];
  CPG_Prim.X[36] = qoco_solver->sol->x[36];
  CPG_Prim.X[37] = qoco_solver->sol->x[37];
  CPG_Prim.X[38] = qoco_solver->sol->x[38];
  CPG_Prim.X[39] = qoco_solver->sol->x[39];
  CPG_Prim.X[40] = qoco_solver->sol->x[40];
  CPG_Prim.X[41] = qoco_solver->sol->x[41];
  CPG_Prim.X[42] = qoco_solver->sol->x[42];
  CPG_Prim.X[43] = qoco_solver->sol->x[43];
  CPG_Prim.X[44] = qoco_solver->sol->x[44];
  CPG_Prim.X[45] = qoco_solver->sol->x[45];
  CPG_Prim.X[46] = qoco_solver->sol->x[46];
  CPG_Prim.X[47] = qoco_solver->sol->x[47];
  CPG_Prim.X[48] = qoco_solver->sol->x[48];
  CPG_Prim.X[49] = qoco_solver->sol->x[49];
  CPG_Prim.X[50] = qoco_solver->sol->x[50];
  CPG_Prim.X[51] = qoco_solver->sol->x[51];
  CPG_Prim.X[52] = qoco_solver->sol->x[52];
  CPG_Prim.X[53] = qoco_solver->sol->x[53];
  CPG_Prim.X[54] = qoco_solver->sol->x[54];
  CPG_Prim.X[55] = qoco_solver->sol->x[55];
  CPG_Prim.X[56] = qoco_solver->sol->x[56];
  CPG_Prim.X[57] = qoco_solver->sol->x[57];
  CPG_Prim.X[58] = qoco_solver->sol->x[58];
  CPG_Prim.X[59] = qoco_solver->sol->x[59];
  CPG_Prim.X[60] = qoco_solver->sol->x[60];
  CPG_Prim.X[61] = qoco_solver->sol->x[61];
  CPG_Prim.X[62] = qoco_solver->sol->x[62];
  CPG_Prim.X[63] = qoco_solver->sol->x[63];
  CPG_Prim.X[64] = qoco_solver->sol->x[64];
  CPG_Prim.X[65] = qoco_solver->sol->x[65];
  CPG_Prim.X[66] = qoco_solver->sol->x[66];
  CPG_Prim.X[67] = qoco_solver->sol->x[67];
  CPG_Prim.X[68] = qoco_solver->sol->x[68];
  CPG_Prim.X[69] = qoco_solver->sol->x[69];
  CPG_Prim.X[70] = qoco_solver->sol->x[70];
  CPG_Prim.X[71] = qoco_solver->sol->x[71];
  CPG_Prim.X[72] = qoco_solver->sol->x[72];
  CPG_Prim.X[73] = qoco_solver->sol->x[73];
  CPG_Prim.X[74] = qoco_solver->sol->x[74];
  CPG_Prim.X[75] = qoco_solver->sol->x[75];
  CPG_Prim.X[76] = qoco_solver->sol->x[76];
  CPG_Prim.X[77] = qoco_solver->sol->x[77];
  CPG_Prim.X[78] = qoco_solver->sol->x[78];
  CPG_Prim.X[79] = qoco_solver->sol->x[79];
  CPG_Prim.X[80] = qoco_solver->sol->x[80];
  CPG_Prim.X[81] = qoco_solver->sol->x[81];
  CPG_Prim.X[82] = qoco_solver->sol->x[82];
  CPG_Prim.X[83] = qoco_solver->sol->x[83];
  CPG_Prim.X[84] = qoco_solver->sol->x[84];
  CPG_Prim.X[85] = qoco_solver->sol->x[85];
  CPG_Prim.X[86] = qoco_solver->sol->x[86];
  CPG_Prim.X[87] = qoco_solver->sol->x[87];
  CPG_Prim.X[88] = qoco_solver->sol->x[88];
  CPG_Prim.X[89] = qoco_solver->sol->x[89];
  CPG_Prim.X[90] = qoco_solver->sol->x[90];
  CPG_Prim.X[91] = qoco_solver->sol->x[91];
  CPG_Prim.X[92] = qoco_solver->sol->x[92];
  CPG_Prim.X[93] = qoco_solver->sol->x[93];
  CPG_Prim.X[94] = qoco_solver->sol->x[94];
  CPG_Prim.X[95] = qoco_solver->sol->x[95];
  CPG_Prim.X[96] = qoco_solver->sol->x[96];
  CPG_Prim.X[97] = qoco_solver->sol->x[97];
  CPG_Prim.X[98] = qoco_solver->sol->x[98];
  CPG_Prim.X[99] = qoco_solver->sol->x[99];
  CPG_Prim.X[100] = qoco_solver->sol->x[100];
  CPG_Prim.X[101] = qoco_solver->sol->x[101];
  CPG_Prim.X[102] = qoco_solver->sol->x[102];
  CPG_Prim.X[103] = qoco_solver->sol->x[103];
  CPG_Prim.X[104] = qoco_solver->sol->x[104];
  CPG_Prim.X[105] = qoco_solver->sol->x[105];
  CPG_Prim.X[106] = qoco_solver->sol->x[106];
  CPG_Prim.X[107] = qoco_solver->sol->x[107];
  CPG_Prim.X[108] = qoco_solver->sol->x[108];
  CPG_Prim.X[109] = qoco_solver->sol->x[109];
  CPG_Prim.X[110] = qoco_solver->sol->x[110];
  CPG_Prim.X[111] = qoco_solver->sol->x[111];
  CPG_Prim.X[112] = qoco_solver->sol->x[112];
  CPG_Prim.X[113] = qoco_solver->sol->x[113];
  CPG_Prim.X[114] = qoco_solver->sol->x[114];
  CPG_Prim.X[115] = qoco_solver->sol->x[115];
  CPG_Prim.X[116] = qoco_solver->sol->x[116];
  CPG_Prim.X[117] = qoco_solver->sol->x[117];
  CPG_Prim.X[118] = qoco_solver->sol->x[118];
  CPG_Prim.X[119] = qoco_solver->sol->x[119];
  CPG_Prim.X[120] = qoco_solver->sol->x[120];
  CPG_Prim.X[121] = qoco_solver->sol->x[121];
  CPG_Prim.X[122] = qoco_solver->sol->x[122];
  CPG_Prim.X[123] = qoco_solver->sol->x[123];
  CPG_Prim.X[124] = qoco_solver->sol->x[124];
  CPG_Prim.X[125] = qoco_solver->sol->x[125];
  CPG_Prim.X[126] = qoco_solver->sol->x[126];
  CPG_Prim.X[127] = qoco_solver->sol->x[127];
  CPG_Prim.X[128] = qoco_solver->sol->x[128];
  CPG_Prim.X[129] = qoco_solver->sol->x[129];
  CPG_Prim.X[130] = qoco_solver->sol->x[130];
  CPG_Prim.X[131] = qoco_solver->sol->x[131];
  CPG_Prim.X[132] = qoco_solver->sol->x[132];
  CPG_Prim.X[133] = qoco_solver->sol->x[133];
  CPG_Prim.X[134] = qoco_solver->sol->x[134];
  CPG_Prim.X[135] = qoco_solver->sol->x[135];
  CPG_Prim.X[136] = qoco_solver->sol->x[136];
  CPG_Prim.X[137] = qoco_solver->sol->x[137];
  CPG_Prim.X[138] = qoco_solver->sol->x[138];
  CPG_Prim.X[139] = qoco_solver->sol->x[139];
  CPG_Prim.U[0] = qoco_solver->sol->x[458];
  CPG_Prim.U[1] = qoco_solver->sol->x[459];
  CPG_Prim.U[2] = qoco_solver->sol->x[460];
  CPG_Prim.U[3] = qoco_solver->sol->x[461];
  CPG_Prim.U[4] = qoco_solver->sol->x[462];
  CPG_Prim.U[5] = qoco_solver->sol->x[463];
  CPG_Prim.U[6] = qoco_solver->sol->x[464];
  CPG_Prim.U[7] = qoco_solver->sol->x[465];
  CPG_Prim.U[8] = qoco_solver->sol->x[466];
  CPG_Prim.U[9] = qoco_solver->sol->x[467];
  CPG_Prim.U[10] = qoco_solver->sol->x[468];
  CPG_Prim.U[11] = qoco_solver->sol->x[469];
  CPG_Prim.U[12] = qoco_solver->sol->x[470];
  CPG_Prim.U[13] = qoco_solver->sol->x[471];
  CPG_Prim.U[14] = qoco_solver->sol->x[472];
  CPG_Prim.U[15] = qoco_solver->sol->x[473];
  CPG_Prim.U[16] = qoco_solver->sol->x[474];
  CPG_Prim.U[17] = qoco_solver->sol->x[475];
  CPG_Prim.U[18] = qoco_solver->sol->x[476];
  CPG_Prim.U[19] = qoco_solver->sol->x[477];
  CPG_Prim.U[20] = qoco_solver->sol->x[478];
  CPG_Prim.U[21] = qoco_solver->sol->x[479];
  CPG_Prim.U[22] = qoco_solver->sol->x[480];
  CPG_Prim.U[23] = qoco_solver->sol->x[481];
  CPG_Prim.U[24] = qoco_solver->sol->x[482];
  CPG_Prim.U[25] = qoco_solver->sol->x[483];
  CPG_Prim.U[26] = qoco_solver->sol->x[484];
  CPG_Prim.U[27] = qoco_solver->sol->x[485];
  CPG_Prim.U[28] = qoco_solver->sol->x[486];
  CPG_Prim.U[29] = qoco_solver->sol->x[487];
  CPG_Prim.U[30] = qoco_solver->sol->x[488];
  CPG_Prim.U[31] = qoco_solver->sol->x[489];
  CPG_Prim.U[32] = qoco_solver->sol->x[490];
  CPG_Prim.U[33] = qoco_solver->sol->x[491];
  CPG_Prim.U[34] = qoco_solver->sol->x[492];
  CPG_Prim.U[35] = qoco_solver->sol->x[493];
  CPG_Prim.U[36] = qoco_solver->sol->x[494];
  CPG_Prim.U[37] = qoco_solver->sol->x[495];
  CPG_Prim.U[38] = qoco_solver->sol->x[496];
  CPG_Prim.U[39] = qoco_solver->sol->x[497];
  CPG_Prim.V[0] = qoco_solver->sol->x[498];
  CPG_Prim.V[1] = qoco_solver->sol->x[499];
  CPG_Prim.V[2] = qoco_solver->sol->x[500];
  CPG_Prim.V[3] = qoco_solver->sol->x[501];
  CPG_Prim.V[4] = qoco_solver->sol->x[502];
  CPG_Prim.V[5] = qoco_solver->sol->x[503];
  CPG_Prim.V[6] = qoco_solver->sol->x[504];
  CPG_Prim.V[7] = qoco_solver->sol->x[505];
  CPG_Prim.V[8] = qoco_solver->sol->x[506];
  CPG_Prim.V[9] = qoco_solver->sol->x[507];
  CPG_Prim.V[10] = qoco_solver->sol->x[508];
  CPG_Prim.V[11] = qoco_solver->sol->x[509];
  CPG_Prim.V[12] = qoco_solver->sol->x[510];
  CPG_Prim.V[13] = qoco_solver->sol->x[511];
  CPG_Prim.V[14] = qoco_solver->sol->x[512];
  CPG_Prim.V[15] = qoco_solver->sol->x[513];
  CPG_Prim.V[16] = qoco_solver->sol->x[514];
  CPG_Prim.V[17] = qoco_solver->sol->x[515];
  CPG_Prim.V[18] = qoco_solver->sol->x[516];
  CPG_Prim.V[19] = qoco_solver->sol->x[517];
  CPG_Prim.V[20] = qoco_solver->sol->x[518];
  CPG_Prim.V[21] = qoco_solver->sol->x[519];
  CPG_Prim.V[22] = qoco_solver->sol->x[520];
  CPG_Prim.V[23] = qoco_solver->sol->x[521];
  CPG_Prim.V[24] = qoco_solver->sol->x[522];
  CPG_Prim.V[25] = qoco_solver->sol->x[523];
  CPG_Prim.V[26] = qoco_solver->sol->x[524];
  CPG_Prim.V[27] = qoco_solver->sol->x[525];
  CPG_Prim.V[28] = qoco_solver->sol->x[526];
  CPG_Prim.V[29] = qoco_solver->sol->x[527];
  CPG_Prim.V[30] = qoco_solver->sol->x[528];
  CPG_Prim.V[31] = qoco_solver->sol->x[529];
  CPG_Prim.V[32] = qoco_solver->sol->x[530];
  CPG_Prim.V[33] = qoco_solver->sol->x[531];
  CPG_Prim.V[34] = qoco_solver->sol->x[532];
  CPG_Prim.V[35] = qoco_solver->sol->x[533];
  CPG_Prim.V[36] = qoco_solver->sol->x[534];
  CPG_Prim.V[37] = qoco_solver->sol->x[535];
  CPG_Prim.V[38] = qoco_solver->sol->x[536];
  CPG_Prim.V[39] = qoco_solver->sol->x[537];
  CPG_Prim.V[40] = qoco_solver->sol->x[538];
  CPG_Prim.V[41] = qoco_solver->sol->x[539];
  CPG_Prim.V[42] = qoco_solver->sol->x[540];
  CPG_Prim.V[43] = qoco_solver->sol->x[541];
  CPG_Prim.V[44] = qoco_solver->sol->x[542];
  CPG_Prim.V[45] = qoco_solver->sol->x[543];
  CPG_Prim.V[46] = qoco_solver->sol->x[544];
  CPG_Prim.V[47] = qoco_solver->sol->x[545];
  CPG_Prim.V[48] = qoco_solver->sol->x[546];
  CPG_Prim.V[49] = qoco_solver->sol->x[547];
  CPG_Prim.V[50] = qoco_solver->sol->x[548];
  CPG_Prim.V[51] = qoco_solver->sol->x[549];
  CPG_Prim.V[52] = qoco_solver->sol->x[550];
  CPG_Prim.V[53] = qoco_solver->sol->x[551];
  CPG_Prim.V[54] = qoco_solver->sol->x[552];
  CPG_Prim.V[55] = qoco_solver->sol->x[553];
  CPG_Prim.V[56] = qoco_solver->sol->x[554];
  CPG_Prim.V[57] = qoco_solver->sol->x[555];
  CPG_Prim.V[58] = qoco_solver->sol->x[556];
  CPG_Prim.V[59] = qoco_solver->sol->x[557];
  CPG_Prim.V[60] = qoco_solver->sol->x[558];
  CPG_Prim.V[61] = qoco_solver->sol->x[559];
  CPG_Prim.V[62] = qoco_solver->sol->x[560];
  CPG_Prim.V[63] = qoco_solver->sol->x[561];
  CPG_Prim.V[64] = qoco_solver->sol->x[562];
  CPG_Prim.V[65] = qoco_solver->sol->x[563];
  CPG_Prim.V[66] = qoco_solver->sol->x[564];
  CPG_Prim.V[67] = qoco_solver->sol->x[565];
  CPG_Prim.V[68] = qoco_solver->sol->x[566];
  CPG_Prim.V[69] = qoco_solver->sol->x[567];
  CPG_Prim.V[70] = qoco_solver->sol->x[568];
  CPG_Prim.V[71] = qoco_solver->sol->x[569];
  CPG_Prim.V[72] = qoco_solver->sol->x[570];
  CPG_Prim.V[73] = qoco_solver->sol->x[571];
  CPG_Prim.V[74] = qoco_solver->sol->x[572];
  CPG_Prim.V[75] = qoco_solver->sol->x[573];
  CPG_Prim.V[76] = qoco_solver->sol->x[574];
  CPG_Prim.V[77] = qoco_solver->sol->x[575];
  CPG_Prim.V[78] = qoco_solver->sol->x[576];
  CPG_Prim.V[79] = qoco_solver->sol->x[577];
  CPG_Prim.V[80] = qoco_solver->sol->x[578];
  CPG_Prim.V[81] = qoco_solver->sol->x[579];
  CPG_Prim.V[82] = qoco_solver->sol->x[580];
  CPG_Prim.V[83] = qoco_solver->sol->x[581];
  CPG_Prim.V[84] = qoco_solver->sol->x[582];
  CPG_Prim.V[85] = qoco_solver->sol->x[583];
  CPG_Prim.V[86] = qoco_solver->sol->x[584];
  CPG_Prim.V[87] = qoco_solver->sol->x[585];
  CPG_Prim.V[88] = qoco_solver->sol->x[586];
  CPG_Prim.V[89] = qoco_solver->sol->x[587];
  CPG_Prim.V[90] = qoco_solver->sol->x[588];
  CPG_Prim.V[91] = qoco_solver->sol->x[589];
  CPG_Prim.V[92] = qoco_solver->sol->x[590];
  CPG_Prim.V[93] = qoco_solver->sol->x[591];
  CPG_Prim.V[94] = qoco_solver->sol->x[592];
  CPG_Prim.V[95] = qoco_solver->sol->x[593];
  CPG_Prim.V[96] = qoco_solver->sol->x[594];
  CPG_Prim.V[97] = qoco_solver->sol->x[595];
  CPG_Prim.V[98] = qoco_solver->sol->x[596];
  CPG_Prim.V[99] = qoco_solver->sol->x[597];
  CPG_Prim.V[100] = qoco_solver->sol->x[598];
  CPG_Prim.V[101] = qoco_solver->sol->x[599];
  CPG_Prim.V[102] = qoco_solver->sol->x[600];
  CPG_Prim.V[103] = qoco_solver->sol->x[601];
  CPG_Prim.V[104] = qoco_solver->sol->x[602];
  CPG_Prim.V[105] = qoco_solver->sol->x[603];
  CPG_Prim.V[106] = qoco_solver->sol->x[604];
  CPG_Prim.V[107] = qoco_solver->sol->x[605];
  CPG_Prim.V[108] = qoco_solver->sol->x[606];
  CPG_Prim.V[109] = qoco_solver->sol->x[607];
  CPG_Prim.V[110] = qoco_solver->sol->x[608];
  CPG_Prim.V[111] = qoco_solver->sol->x[609];
  CPG_Prim.V[112] = qoco_solver->sol->x[610];
  CPG_Prim.V[113] = qoco_solver->sol->x[611];
  CPG_Prim.V[114] = qoco_solver->sol->x[612];
  CPG_Prim.V[115] = qoco_solver->sol->x[613];
  CPG_Prim.V[116] = qoco_solver->sol->x[614];
  CPG_Prim.V[117] = qoco_solver->sol->x[615];
  CPG_Prim.V[118] = qoco_solver->sol->x[616];
  CPG_Prim.V[119] = qoco_solver->sol->x[617];
  CPG_Prim.V[120] = qoco_solver->sol->x[618];
  CPG_Prim.V[121] = qoco_solver->sol->x[619];
  CPG_Prim.V[122] = qoco_solver->sol->x[620];
  CPG_Prim.V[123] = qoco_solver->sol->x[621];
  CPG_Prim.V[124] = qoco_solver->sol->x[622];
  CPG_Prim.V[125] = qoco_solver->sol->x[623];
  CPG_Prim.v_0[0] = qoco_solver->sol->x[624];
  CPG_Prim.v_0[1] = qoco_solver->sol->x[625];
  CPG_Prim.v_0[2] = qoco_solver->sol->x[626];
  CPG_Prim.v_0[3] = qoco_solver->sol->x[627];
  CPG_Prim.v_0[4] = qoco_solver->sol->x[628];
  CPG_Prim.v_0[5] = qoco_solver->sol->x[629];
  CPG_Prim.v_0[6] = qoco_solver->sol->x[630];
  CPG_Prim.v_0[7] = qoco_solver->sol->x[631];
  CPG_Prim.v_0[8] = qoco_solver->sol->x[632];
  CPG_Prim.v_0[9] = qoco_solver->sol->x[633];
  CPG_Prim.v_0[10] = qoco_solver->sol->x[634];
  CPG_Prim.v_0[11] = qoco_solver->sol->x[635];
  CPG_Prim.v_0[12] = qoco_solver->sol->x[636];
  CPG_Prim.v_0[13] = qoco_solver->sol->x[637];
  CPG_Prim.v_N[0] = qoco_solver->sol->x[652];
  CPG_Prim.v_N[1] = qoco_solver->sol->x[653];
  CPG_Prim.v_N[2] = qoco_solver->sol->x[654];
  CPG_Prim.v_N[3] = qoco_solver->sol->x[655];
  CPG_Prim.v_N[4] = qoco_solver->sol->x[656];
  CPG_Prim.v_N[5] = qoco_solver->sol->x[657];
  CPG_Prim.v_N[6] = qoco_solver->sol->x[658];
  CPG_Prim.v_N[7] = qoco_solver->sol->x[659];
  CPG_Prim.v_N[8] = qoco_solver->sol->x[660];
  CPG_Prim.v_N[9] = qoco_solver->sol->x[661];
  CPG_Prim.v_N[10] = qoco_solver->sol->x[662];
  CPG_Prim.v_N[11] = qoco_solver->sol->x[663];
  CPG_Prim.v_N[12] = qoco_solver->sol->x[664];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = qoco_solver->sol->y[180];
  CPG_Dual.d0[1] = qoco_solver->sol->y[181];
  CPG_Dual.d0[2] = qoco_solver->sol->y[182];
  CPG_Dual.d0[3] = qoco_solver->sol->y[183];
  CPG_Dual.d0[4] = qoco_solver->sol->y[184];
  CPG_Dual.d0[5] = qoco_solver->sol->y[185];
  CPG_Dual.d0[6] = qoco_solver->sol->y[186];
  CPG_Dual.d0[7] = qoco_solver->sol->y[187];
  CPG_Dual.d0[8] = qoco_solver->sol->y[188];
  CPG_Dual.d0[9] = qoco_solver->sol->y[189];
  CPG_Dual.d0[10] = qoco_solver->sol->y[190];
  CPG_Dual.d0[11] = qoco_solver->sol->y[191];
  CPG_Dual.d0[12] = qoco_solver->sol->y[192];
  CPG_Dual.d0[13] = qoco_solver->sol->y[193];
  CPG_Dual.d1[0] = qoco_solver->sol->y[194];
  CPG_Dual.d1[1] = qoco_solver->sol->y[195];
  CPG_Dual.d1[2] = qoco_solver->sol->y[196];
  CPG_Dual.d1[3] = qoco_solver->sol->y[197];
  CPG_Dual.d1[4] = qoco_solver->sol->y[198];
  CPG_Dual.d1[5] = qoco_solver->sol->y[199];
  CPG_Dual.d1[6] = qoco_solver->sol->y[200];
  CPG_Dual.d1[7] = qoco_solver->sol->y[201];
  CPG_Dual.d1[8] = qoco_solver->sol->y[202];
  CPG_Dual.d1[9] = qoco_solver->sol->y[203];
  CPG_Dual.d1[10] = qoco_solver->sol->y[204];
  CPG_Dual.d1[11] = qoco_solver->sol->y[205];
  CPG_Dual.d1[12] = qoco_solver->sol->y[206];
  CPG_Dual.d1[13] = qoco_solver->sol->y[207];
  CPG_Dual.d2[0] = qoco_solver->sol->y[208];
  CPG_Dual.d2[1] = qoco_solver->sol->y[209];
  CPG_Dual.d2[2] = qoco_solver->sol->y[210];
  CPG_Dual.d2[3] = qoco_solver->sol->y[211];
  CPG_Dual.d2[4] = qoco_solver->sol->y[212];
  CPG_Dual.d2[5] = qoco_solver->sol->y[213];
  CPG_Dual.d2[6] = qoco_solver->sol->y[214];
  CPG_Dual.d2[7] = qoco_solver->sol->y[215];
  CPG_Dual.d2[8] = qoco_solver->sol->y[216];
  CPG_Dual.d2[9] = qoco_solver->sol->y[217];
  CPG_Dual.d2[10] = qoco_solver->sol->y[218];
  CPG_Dual.d2[11] = qoco_solver->sol->y[219];
  CPG_Dual.d2[12] = qoco_solver->sol->y[220];
  CPG_Dual.d2[13] = qoco_solver->sol->y[221];
  CPG_Dual.d3[0] = qoco_solver->sol->y[222];
  CPG_Dual.d3[1] = qoco_solver->sol->y[223];
  CPG_Dual.d3[2] = qoco_solver->sol->y[224];
  CPG_Dual.d3[3] = qoco_solver->sol->y[225];
  CPG_Dual.d3[4] = qoco_solver->sol->y[226];
  CPG_Dual.d3[5] = qoco_solver->sol->y[227];
  CPG_Dual.d3[6] = qoco_solver->sol->y[228];
  CPG_Dual.d3[7] = qoco_solver->sol->y[229];
  CPG_Dual.d3[8] = qoco_solver->sol->y[230];
  CPG_Dual.d3[9] = qoco_solver->sol->y[231];
  CPG_Dual.d3[10] = qoco_solver->sol->y[232];
  CPG_Dual.d3[11] = qoco_solver->sol->y[233];
  CPG_Dual.d3[12] = qoco_solver->sol->y[234];
  CPG_Dual.d3[13] = qoco_solver->sol->y[235];
  CPG_Dual.d4[0] = qoco_solver->sol->y[236];
  CPG_Dual.d4[1] = qoco_solver->sol->y[237];
  CPG_Dual.d4[2] = qoco_solver->sol->y[238];
  CPG_Dual.d4[3] = qoco_solver->sol->y[239];
  CPG_Dual.d4[4] = qoco_solver->sol->y[240];
  CPG_Dual.d4[5] = qoco_solver->sol->y[241];
  CPG_Dual.d4[6] = qoco_solver->sol->y[242];
  CPG_Dual.d4[7] = qoco_solver->sol->y[243];
  CPG_Dual.d4[8] = qoco_solver->sol->y[244];
  CPG_Dual.d4[9] = qoco_solver->sol->y[245];
  CPG_Dual.d4[10] = qoco_solver->sol->y[246];
  CPG_Dual.d4[11] = qoco_solver->sol->y[247];
  CPG_Dual.d4[12] = qoco_solver->sol->y[248];
  CPG_Dual.d4[13] = qoco_solver->sol->y[249];
  CPG_Dual.d5[0] = qoco_solver->sol->y[250];
  CPG_Dual.d5[1] = qoco_solver->sol->y[251];
  CPG_Dual.d5[2] = qoco_solver->sol->y[252];
  CPG_Dual.d5[3] = qoco_solver->sol->y[253];
  CPG_Dual.d5[4] = qoco_solver->sol->y[254];
  CPG_Dual.d5[5] = qoco_solver->sol->y[255];
  CPG_Dual.d5[6] = qoco_solver->sol->y[256];
  CPG_Dual.d5[7] = qoco_solver->sol->y[257];
  CPG_Dual.d5[8] = qoco_solver->sol->y[258];
  CPG_Dual.d5[9] = qoco_solver->sol->y[259];
  CPG_Dual.d5[10] = qoco_solver->sol->y[260];
  CPG_Dual.d5[11] = qoco_solver->sol->y[261];
  CPG_Dual.d5[12] = qoco_solver->sol->y[262];
  CPG_Dual.d5[13] = qoco_solver->sol->y[263];
  CPG_Dual.d6[0] = qoco_solver->sol->y[264];
  CPG_Dual.d6[1] = qoco_solver->sol->y[265];
  CPG_Dual.d6[2] = qoco_solver->sol->y[266];
  CPG_Dual.d6[3] = qoco_solver->sol->y[267];
  CPG_Dual.d6[4] = qoco_solver->sol->y[268];
  CPG_Dual.d6[5] = qoco_solver->sol->y[269];
  CPG_Dual.d6[6] = qoco_solver->sol->y[270];
  CPG_Dual.d6[7] = qoco_solver->sol->y[271];
  CPG_Dual.d6[8] = qoco_solver->sol->y[272];
  CPG_Dual.d6[9] = qoco_solver->sol->y[273];
  CPG_Dual.d6[10] = qoco_solver->sol->y[274];
  CPG_Dual.d6[11] = qoco_solver->sol->y[275];
  CPG_Dual.d6[12] = qoco_solver->sol->y[276];
  CPG_Dual.d6[13] = qoco_solver->sol->y[277];
  CPG_Dual.d7[0] = qoco_solver->sol->y[278];
  CPG_Dual.d7[1] = qoco_solver->sol->y[279];
  CPG_Dual.d7[2] = qoco_solver->sol->y[280];
  CPG_Dual.d7[3] = qoco_solver->sol->y[281];
  CPG_Dual.d7[4] = qoco_solver->sol->y[282];
  CPG_Dual.d7[5] = qoco_solver->sol->y[283];
  CPG_Dual.d7[6] = qoco_solver->sol->y[284];
  CPG_Dual.d7[7] = qoco_solver->sol->y[285];
  CPG_Dual.d7[8] = qoco_solver->sol->y[286];
  CPG_Dual.d7[9] = qoco_solver->sol->y[287];
  CPG_Dual.d7[10] = qoco_solver->sol->y[288];
  CPG_Dual.d7[11] = qoco_solver->sol->y[289];
  CPG_Dual.d7[12] = qoco_solver->sol->y[290];
  CPG_Dual.d7[13] = qoco_solver->sol->y[291];
  CPG_Dual.d8[0] = qoco_solver->sol->y[292];
  CPG_Dual.d8[1] = qoco_solver->sol->y[293];
  CPG_Dual.d8[2] = qoco_solver->sol->y[294];
  CPG_Dual.d8[3] = qoco_solver->sol->y[295];
  CPG_Dual.d8[4] = qoco_solver->sol->y[296];
  CPG_Dual.d8[5] = qoco_solver->sol->y[297];
  CPG_Dual.d8[6] = qoco_solver->sol->y[298];
  CPG_Dual.d8[7] = qoco_solver->sol->y[299];
  CPG_Dual.d8[8] = qoco_solver->sol->y[300];
  CPG_Dual.d8[9] = qoco_solver->sol->y[301];
  CPG_Dual.d8[10] = qoco_solver->sol->y[302];
  CPG_Dual.d8[11] = qoco_solver->sol->y[303];
  CPG_Dual.d8[12] = qoco_solver->sol->y[304];
  CPG_Dual.d8[13] = qoco_solver->sol->y[305];
  CPG_Dual.d9[0] = qoco_solver->sol->z[328];
  CPG_Dual.d9[1] = qoco_solver->sol->z[329];
  CPG_Dual.d9[2] = qoco_solver->sol->z[330];
  CPG_Dual.d9[3] = qoco_solver->sol->z[331];
  CPG_Dual.d9[4] = qoco_solver->sol->z[332];
  CPG_Dual.d9[5] = qoco_solver->sol->z[333];
  CPG_Dual.d9[6] = qoco_solver->sol->z[334];
  CPG_Dual.d9[7] = qoco_solver->sol->z[335];
  CPG_Dual.d9[8] = qoco_solver->sol->z[336];
  CPG_Dual.d9[9] = qoco_solver->sol->z[337];
  CPG_Dual.d10[0] = qoco_solver->sol->z[338];
  CPG_Dual.d10[1] = qoco_solver->sol->z[339];
  CPG_Dual.d10[2] = qoco_solver->sol->z[340];
  CPG_Dual.d10[3] = qoco_solver->sol->z[341];
  CPG_Dual.d10[4] = qoco_solver->sol->z[342];
  CPG_Dual.d10[5] = qoco_solver->sol->z[343];
  CPG_Dual.d10[6] = qoco_solver->sol->z[344];
  CPG_Dual.d10[7] = qoco_solver->sol->z[345];
  CPG_Dual.d10[8] = qoco_solver->sol->z[346];
  CPG_Dual.d10[9] = qoco_solver->sol->z[347];
  CPG_Dual.d11[0] = qoco_solver->sol->z[348];
  CPG_Dual.d11[1] = qoco_solver->sol->z[349];
  CPG_Dual.d11[2] = qoco_solver->sol->z[350];
  CPG_Dual.d11[3] = qoco_solver->sol->z[351];
  CPG_Dual.d11[4] = qoco_solver->sol->z[352];
  CPG_Dual.d11[5] = qoco_solver->sol->z[353];
  CPG_Dual.d11[6] = qoco_solver->sol->z[354];
  CPG_Dual.d11[7] = qoco_solver->sol->z[355];
  CPG_Dual.d11[8] = qoco_solver->sol->z[356];
  CPG_Dual.d11[9] = qoco_solver->sol->z[357];
  CPG_Dual.d12[0] = qoco_solver->sol->z[358];
  CPG_Dual.d12[1] = qoco_solver->sol->z[359];
  CPG_Dual.d12[2] = qoco_solver->sol->z[360];
  CPG_Dual.d12[3] = qoco_solver->sol->z[361];
  CPG_Dual.d12[4] = qoco_solver->sol->z[362];
  CPG_Dual.d12[5] = qoco_solver->sol->z[363];
  CPG_Dual.d12[6] = qoco_solver->sol->z[364];
  CPG_Dual.d12[7] = qoco_solver->sol->z[365];
  CPG_Dual.d12[8] = qoco_solver->sol->z[366];
  CPG_Dual.d12[9] = qoco_solver->sol->z[367];
  CPG_Dual.d13[0] = qoco_solver->sol->z[388];
  CPG_Dual.d13[1] = qoco_solver->sol->z[389];
  CPG_Dual.d13[2] = qoco_solver->sol->z[390];
  CPG_Dual.d13[3] = qoco_solver->sol->z[391];
  CPG_Dual.d13[4] = qoco_solver->sol->z[392];
  CPG_Dual.d13[5] = qoco_solver->sol->z[393];
  CPG_Dual.d13[6] = qoco_solver->sol->z[394];
  CPG_Dual.d13[7] = qoco_solver->sol->z[395];
  CPG_Dual.d13[8] = qoco_solver->sol->z[396];
  CPG_Dual.d13[9] = qoco_solver->sol->z[397];
  CPG_Dual.d14 = qoco_solver->sol->z[458];
  CPG_Dual.d15[0] = qoco_solver->sol->z[475];
  CPG_Dual.d15[1] = qoco_solver->sol->z[476];
  CPG_Dual.d15[2] = qoco_solver->sol->z[477];
  CPG_Dual.d15[3] = qoco_solver->sol->z[478];
  CPG_Dual.d15[4] = qoco_solver->sol->z[479];
  CPG_Dual.d15[5] = qoco_solver->sol->z[480];
  CPG_Dual.d15[6] = qoco_solver->sol->z[481];
  CPG_Dual.d15[7] = qoco_solver->sol->z[482];
  CPG_Dual.d16[0] = qoco_solver->sol->y[306];
  CPG_Dual.d16[1] = qoco_solver->sol->y[307];
  CPG_Dual.d16[2] = qoco_solver->sol->y[308];
  CPG_Dual.d16[3] = qoco_solver->sol->y[309];
  CPG_Dual.d16[4] = qoco_solver->sol->y[310];
  CPG_Dual.d16[5] = qoco_solver->sol->y[311];
  CPG_Dual.d16[6] = qoco_solver->sol->y[312];
  CPG_Dual.d16[7] = qoco_solver->sol->y[313];
  CPG_Dual.d16[8] = qoco_solver->sol->y[314];
  CPG_Dual.d16[9] = qoco_solver->sol->y[315];
  CPG_Dual.d16[10] = qoco_solver->sol->y[316];
  CPG_Dual.d16[11] = qoco_solver->sol->y[317];
  CPG_Dual.d16[12] = qoco_solver->sol->y[318];
  CPG_Dual.d16[13] = qoco_solver->sol->y[319];
  CPG_Dual.d16[14] = qoco_solver->sol->y[320];
  CPG_Dual.d16[15] = qoco_solver->sol->y[321];
  CPG_Dual.d16[16] = qoco_solver->sol->y[322];
  CPG_Dual.d16[17] = qoco_solver->sol->y[323];
  CPG_Dual.d16[18] = qoco_solver->sol->y[324];
  CPG_Dual.d16[19] = qoco_solver->sol->y[325];
  CPG_Dual.d16[20] = qoco_solver->sol->y[326];
  CPG_Dual.d16[21] = qoco_solver->sol->y[327];
  CPG_Dual.d16[22] = qoco_solver->sol->y[328];
  CPG_Dual.d16[23] = qoco_solver->sol->y[329];
  CPG_Dual.d16[24] = qoco_solver->sol->y[330];
  CPG_Dual.d16[25] = qoco_solver->sol->y[331];
  CPG_Dual.d16[26] = qoco_solver->sol->y[332];
  CPG_Dual.d16[27] = qoco_solver->sol->y[333];
  CPG_Dual.d16[28] = qoco_solver->sol->y[334];
  CPG_Dual.d16[29] = qoco_solver->sol->y[335];
  CPG_Dual.d16[30] = qoco_solver->sol->y[336];
  CPG_Dual.d16[31] = qoco_solver->sol->y[337];
  CPG_Dual.d16[32] = qoco_solver->sol->y[338];
  CPG_Dual.d16[33] = qoco_solver->sol->y[339];
  CPG_Dual.d16[34] = qoco_solver->sol->y[340];
  CPG_Dual.d16[35] = qoco_solver->sol->y[341];
  CPG_Dual.d16[36] = qoco_solver->sol->y[342];
  CPG_Dual.d16[37] = qoco_solver->sol->y[343];
  CPG_Dual.d16[38] = qoco_solver->sol->y[344];
  CPG_Dual.d16[39] = qoco_solver->sol->y[345];
  CPG_Dual.d16[40] = qoco_solver->sol->y[346];
  CPG_Dual.d16[41] = qoco_solver->sol->y[347];
  CPG_Dual.d16[42] = qoco_solver->sol->y[348];
  CPG_Dual.d16[43] = qoco_solver->sol->y[349];
  CPG_Dual.d16[44] = qoco_solver->sol->y[350];
  CPG_Dual.d16[45] = qoco_solver->sol->y[351];
  CPG_Dual.d16[46] = qoco_solver->sol->y[352];
  CPG_Dual.d16[47] = qoco_solver->sol->y[353];
  CPG_Dual.d16[48] = qoco_solver->sol->y[354];
  CPG_Dual.d16[49] = qoco_solver->sol->y[355];
  CPG_Dual.d16[50] = qoco_solver->sol->y[356];
  CPG_Dual.d16[51] = qoco_solver->sol->y[357];
  CPG_Dual.d16[52] = qoco_solver->sol->y[358];
  CPG_Dual.d16[53] = qoco_solver->sol->y[359];
  CPG_Dual.d16[54] = qoco_solver->sol->y[360];
  CPG_Dual.d16[55] = qoco_solver->sol->y[361];
  CPG_Dual.d16[56] = qoco_solver->sol->y[362];
  CPG_Dual.d16[57] = qoco_solver->sol->y[363];
  CPG_Dual.d16[58] = qoco_solver->sol->y[364];
  CPG_Dual.d16[59] = qoco_solver->sol->y[365];
  CPG_Dual.d16[60] = qoco_solver->sol->y[366];
  CPG_Dual.d16[61] = qoco_solver->sol->y[367];
  CPG_Dual.d16[62] = qoco_solver->sol->y[368];
  CPG_Dual.d16[63] = qoco_solver->sol->y[369];
  CPG_Dual.d16[64] = qoco_solver->sol->y[370];
  CPG_Dual.d16[65] = qoco_solver->sol->y[371];
  CPG_Dual.d16[66] = qoco_solver->sol->y[372];
  CPG_Dual.d16[67] = qoco_solver->sol->y[373];
  CPG_Dual.d16[68] = qoco_solver->sol->y[374];
  CPG_Dual.d16[69] = qoco_solver->sol->y[375];
  CPG_Dual.d16[70] = qoco_solver->sol->y[376];
  CPG_Dual.d16[71] = qoco_solver->sol->y[377];
  CPG_Dual.d16[72] = qoco_solver->sol->y[378];
  CPG_Dual.d16[73] = qoco_solver->sol->y[379];
  CPG_Dual.d16[74] = qoco_solver->sol->y[380];
  CPG_Dual.d16[75] = qoco_solver->sol->y[381];
  CPG_Dual.d16[76] = qoco_solver->sol->y[382];
  CPG_Dual.d16[77] = qoco_solver->sol->y[383];
  CPG_Dual.d16[78] = qoco_solver->sol->y[384];
  CPG_Dual.d16[79] = qoco_solver->sol->y[385];
  CPG_Dual.d16[80] = qoco_solver->sol->y[386];
  CPG_Dual.d16[81] = qoco_solver->sol->y[387];
  CPG_Dual.d16[82] = qoco_solver->sol->y[388];
  CPG_Dual.d16[83] = qoco_solver->sol->y[389];
  CPG_Dual.d16[84] = qoco_solver->sol->y[390];
  CPG_Dual.d16[85] = qoco_solver->sol->y[391];
  CPG_Dual.d16[86] = qoco_solver->sol->y[392];
  CPG_Dual.d16[87] = qoco_solver->sol->y[393];
  CPG_Dual.d16[88] = qoco_solver->sol->y[394];
  CPG_Dual.d16[89] = qoco_solver->sol->y[395];
  CPG_Dual.d16[90] = qoco_solver->sol->y[396];
  CPG_Dual.d16[91] = qoco_solver->sol->y[397];
  CPG_Dual.d16[92] = qoco_solver->sol->y[398];
  CPG_Dual.d16[93] = qoco_solver->sol->y[399];
  CPG_Dual.d16[94] = qoco_solver->sol->y[400];
  CPG_Dual.d16[95] = qoco_solver->sol->y[401];
  CPG_Dual.d16[96] = qoco_solver->sol->y[402];
  CPG_Dual.d16[97] = qoco_solver->sol->y[403];
  CPG_Dual.d16[98] = qoco_solver->sol->y[404];
  CPG_Dual.d16[99] = qoco_solver->sol->y[405];
  CPG_Dual.d16[100] = qoco_solver->sol->y[406];
  CPG_Dual.d16[101] = qoco_solver->sol->y[407];
  CPG_Dual.d16[102] = qoco_solver->sol->y[408];
  CPG_Dual.d16[103] = qoco_solver->sol->y[409];
  CPG_Dual.d16[104] = qoco_solver->sol->y[410];
  CPG_Dual.d16[105] = qoco_solver->sol->y[411];
  CPG_Dual.d16[106] = qoco_solver->sol->y[412];
  CPG_Dual.d16[107] = qoco_solver->sol->y[413];
  CPG_Dual.d16[108] = qoco_solver->sol->y[414];
  CPG_Dual.d16[109] = qoco_solver->sol->y[415];
  CPG_Dual.d16[110] = qoco_solver->sol->y[416];
  CPG_Dual.d16[111] = qoco_solver->sol->y[417];
  CPG_Dual.d16[112] = qoco_solver->sol->y[418];
  CPG_Dual.d16[113] = qoco_solver->sol->y[419];
  CPG_Dual.d16[114] = qoco_solver->sol->y[420];
  CPG_Dual.d16[115] = qoco_solver->sol->y[421];
  CPG_Dual.d16[116] = qoco_solver->sol->y[422];
  CPG_Dual.d16[117] = qoco_solver->sol->y[423];
  CPG_Dual.d16[118] = qoco_solver->sol->y[424];
  CPG_Dual.d16[119] = qoco_solver->sol->y[425];
  CPG_Dual.d16[120] = qoco_solver->sol->y[426];
  CPG_Dual.d16[121] = qoco_solver->sol->y[427];
  CPG_Dual.d16[122] = qoco_solver->sol->y[428];
  CPG_Dual.d16[123] = qoco_solver->sol->y[429];
  CPG_Dual.d16[124] = qoco_solver->sol->y[430];
  CPG_Dual.d16[125] = qoco_solver->sol->y[431];
  CPG_Dual.d16[126] = qoco_solver->sol->y[432];
  CPG_Dual.d16[127] = qoco_solver->sol->y[433];
  CPG_Dual.d16[128] = qoco_solver->sol->y[434];
  CPG_Dual.d16[129] = qoco_solver->sol->y[435];
  CPG_Dual.d16[130] = qoco_solver->sol->y[436];
  CPG_Dual.d16[131] = qoco_solver->sol->y[437];
  CPG_Dual.d16[132] = qoco_solver->sol->y[438];
  CPG_Dual.d16[133] = qoco_solver->sol->y[439];
  CPG_Dual.d16[134] = qoco_solver->sol->y[440];
  CPG_Dual.d16[135] = qoco_solver->sol->y[441];
  CPG_Dual.d16[136] = qoco_solver->sol->y[442];
  CPG_Dual.d16[137] = qoco_solver->sol->y[443];
  CPG_Dual.d16[138] = qoco_solver->sol->y[444];
  CPG_Dual.d16[139] = qoco_solver->sol->y[445];
  CPG_Dual.d16[140] = qoco_solver->sol->y[446];
  CPG_Dual.d16[141] = qoco_solver->sol->y[447];
  CPG_Dual.d16[142] = qoco_solver->sol->y[448];
  CPG_Dual.d16[143] = qoco_solver->sol->y[449];
  CPG_Dual.d16[144] = qoco_solver->sol->y[450];
  CPG_Dual.d16[145] = qoco_solver->sol->y[451];
  CPG_Dual.d16[146] = qoco_solver->sol->y[452];
  CPG_Dual.d16[147] = qoco_solver->sol->y[453];
  CPG_Dual.d16[148] = qoco_solver->sol->y[454];
  CPG_Dual.d16[149] = qoco_solver->sol->y[455];
  CPG_Dual.d16[150] = qoco_solver->sol->y[456];
  CPG_Dual.d16[151] = qoco_solver->sol->y[457];
  CPG_Dual.d16[152] = qoco_solver->sol->y[458];
  CPG_Dual.d16[153] = qoco_solver->sol->y[459];
  CPG_Dual.d16[154] = qoco_solver->sol->y[460];
  CPG_Dual.d16[155] = qoco_solver->sol->y[461];
  CPG_Dual.d16[156] = qoco_solver->sol->y[462];
  CPG_Dual.d16[157] = qoco_solver->sol->y[463];
  CPG_Dual.d16[158] = qoco_solver->sol->y[464];
  CPG_Dual.d16[159] = qoco_solver->sol->y[465];
  CPG_Dual.d16[160] = qoco_solver->sol->y[466];
  CPG_Dual.d16[161] = qoco_solver->sol->y[467];
  CPG_Dual.d16[162] = qoco_solver->sol->y[468];
  CPG_Dual.d16[163] = qoco_solver->sol->y[469];
  CPG_Dual.d16[164] = qoco_solver->sol->y[470];
  CPG_Dual.d16[165] = qoco_solver->sol->y[471];
  CPG_Dual.d16[166] = qoco_solver->sol->y[472];
  CPG_Dual.d16[167] = qoco_solver->sol->y[473];
  CPG_Dual.d16[168] = qoco_solver->sol->y[474];
  CPG_Dual.d16[169] = qoco_solver->sol->y[475];
  CPG_Dual.d16[170] = qoco_solver->sol->y[476];
  CPG_Dual.d16[171] = qoco_solver->sol->y[477];
  CPG_Dual.d16[172] = qoco_solver->sol->y[478];
  CPG_Dual.d16[173] = qoco_solver->sol->y[479];
  CPG_Dual.d16[174] = qoco_solver->sol->y[480];
  CPG_Dual.d16[175] = qoco_solver->sol->y[481];
  CPG_Dual.d16[176] = qoco_solver->sol->y[482];
  CPG_Dual.d16[177] = qoco_solver->sol->y[483];
  CPG_Dual.d16[178] = qoco_solver->sol->y[484];
  CPG_Dual.d16[179] = qoco_solver->sol->y[485];
  CPG_Dual.d16[180] = qoco_solver->sol->y[486];
  CPG_Dual.d16[181] = qoco_solver->sol->y[487];
  CPG_Dual.d16[182] = qoco_solver->sol->y[488];
  CPG_Dual.d16[183] = qoco_solver->sol->y[489];
  CPG_Dual.d16[184] = qoco_solver->sol->y[490];
  CPG_Dual.d16[185] = qoco_solver->sol->y[491];
  CPG_Dual.d16[186] = qoco_solver->sol->y[492];
  CPG_Dual.d16[187] = qoco_solver->sol->y[493];
  CPG_Dual.d16[188] = qoco_solver->sol->y[494];
  CPG_Dual.d16[189] = qoco_solver->sol->y[495];
  CPG_Dual.d16[190] = qoco_solver->sol->y[496];
  CPG_Dual.d16[191] = qoco_solver->sol->y[497];
  CPG_Dual.d16[192] = qoco_solver->sol->y[498];
  CPG_Dual.d16[193] = qoco_solver->sol->y[499];
  CPG_Dual.d16[194] = qoco_solver->sol->y[500];
  CPG_Dual.d16[195] = qoco_solver->sol->y[501];
  CPG_Dual.d17[0] = qoco_solver->sol->y[502];
  CPG_Dual.d17[1] = qoco_solver->sol->y[503];
  CPG_Dual.d17[2] = qoco_solver->sol->y[504];
  CPG_Dual.d17[3] = qoco_solver->sol->y[505];
  CPG_Dual.d17[4] = qoco_solver->sol->y[506];
  CPG_Dual.d17[5] = qoco_solver->sol->y[507];
  CPG_Dual.d17[6] = qoco_solver->sol->y[508];
  CPG_Dual.d17[7] = qoco_solver->sol->y[509];
  CPG_Dual.d17[8] = qoco_solver->sol->y[510];
  CPG_Dual.d17[9] = qoco_solver->sol->y[511];
  CPG_Dual.d17[10] = qoco_solver->sol->y[512];
  CPG_Dual.d17[11] = qoco_solver->sol->y[513];
  CPG_Dual.d17[12] = qoco_solver->sol->y[514];
  CPG_Dual.d17[13] = qoco_solver->sol->y[515];
  CPG_Dual.d17[14] = qoco_solver->sol->y[516];
  CPG_Dual.d17[15] = qoco_solver->sol->y[517];
  CPG_Dual.d17[16] = qoco_solver->sol->y[518];
  CPG_Dual.d17[17] = qoco_solver->sol->y[519];
  CPG_Dual.d17[18] = qoco_solver->sol->y[520];
  CPG_Dual.d17[19] = qoco_solver->sol->y[521];
  CPG_Dual.d17[20] = qoco_solver->sol->y[522];
  CPG_Dual.d17[21] = qoco_solver->sol->y[523];
  CPG_Dual.d17[22] = qoco_solver->sol->y[524];
  CPG_Dual.d17[23] = qoco_solver->sol->y[525];
  CPG_Dual.d17[24] = qoco_solver->sol->y[526];
  CPG_Dual.d17[25] = qoco_solver->sol->y[527];
  CPG_Dual.d17[26] = qoco_solver->sol->y[528];
  CPG_Dual.d17[27] = qoco_solver->sol->y[529];
  CPG_Dual.d17[28] = qoco_solver->sol->y[530];
  CPG_Dual.d17[29] = qoco_solver->sol->y[531];
  CPG_Dual.d17[30] = qoco_solver->sol->y[532];
  CPG_Dual.d17[31] = qoco_solver->sol->y[533];
  CPG_Dual.d17[32] = qoco_solver->sol->y[534];
  CPG_Dual.d17[33] = qoco_solver->sol->y[535];
  CPG_Dual.d17[34] = qoco_solver->sol->y[536];
  CPG_Dual.d17[35] = qoco_solver->sol->y[537];
  CPG_Dual.d17[36] = qoco_solver->sol->y[538];
  CPG_Dual.d17[37] = qoco_solver->sol->y[539];
  CPG_Dual.d17[38] = qoco_solver->sol->y[540];
  CPG_Dual.d17[39] = qoco_solver->sol->y[541];
  CPG_Dual.d17[40] = qoco_solver->sol->y[542];
  CPG_Dual.d17[41] = qoco_solver->sol->y[543];
  CPG_Dual.d17[42] = qoco_solver->sol->y[544];
  CPG_Dual.d17[43] = qoco_solver->sol->y[545];
  CPG_Dual.d17[44] = qoco_solver->sol->y[546];
  CPG_Dual.d17[45] = qoco_solver->sol->y[547];
  CPG_Dual.d17[46] = qoco_solver->sol->y[548];
  CPG_Dual.d17[47] = qoco_solver->sol->y[549];
  CPG_Dual.d17[48] = qoco_solver->sol->y[550];
  CPG_Dual.d17[49] = qoco_solver->sol->y[551];
  CPG_Dual.d17[50] = qoco_solver->sol->y[552];
  CPG_Dual.d17[51] = qoco_solver->sol->y[553];
  CPG_Dual.d17[52] = qoco_solver->sol->y[554];
  CPG_Dual.d17[53] = qoco_solver->sol->y[555];
  CPG_Dual.d17[54] = qoco_solver->sol->y[556];
  CPG_Dual.d17[55] = qoco_solver->sol->y[557];
  CPG_Dual.d17[56] = qoco_solver->sol->y[558];
  CPG_Dual.d17[57] = qoco_solver->sol->y[559];
  CPG_Dual.d17[58] = qoco_solver->sol->y[560];
  CPG_Dual.d17[59] = qoco_solver->sol->y[561];
  CPG_Dual.d17[60] = qoco_solver->sol->y[562];
  CPG_Dual.d17[61] = qoco_solver->sol->y[563];
  CPG_Dual.d17[62] = qoco_solver->sol->y[564];
  CPG_Dual.d17[63] = qoco_solver->sol->y[565];
  CPG_Dual.d17[64] = qoco_solver->sol->y[566];
  CPG_Dual.d17[65] = qoco_solver->sol->y[567];
  CPG_Dual.d17[66] = qoco_solver->sol->y[568];
  CPG_Dual.d17[67] = qoco_solver->sol->y[569];
  CPG_Dual.d17[68] = qoco_solver->sol->y[570];
  CPG_Dual.d17[69] = qoco_solver->sol->y[571];
  CPG_Dual.d17[70] = qoco_solver->sol->y[572];
  CPG_Dual.d17[71] = qoco_solver->sol->y[573];
  CPG_Dual.d17[72] = qoco_solver->sol->y[574];
  CPG_Dual.d17[73] = qoco_solver->sol->y[575];
  CPG_Dual.d17[74] = qoco_solver->sol->y[576];
  CPG_Dual.d17[75] = qoco_solver->sol->y[577];
  CPG_Dual.d17[76] = qoco_solver->sol->y[578];
  CPG_Dual.d17[77] = qoco_solver->sol->y[579];
  CPG_Dual.d17[78] = qoco_solver->sol->y[580];
  CPG_Dual.d17[79] = qoco_solver->sol->y[581];
  CPG_Dual.d17[80] = qoco_solver->sol->y[582];
  CPG_Dual.d17[81] = qoco_solver->sol->y[583];
  CPG_Dual.d17[82] = qoco_solver->sol->y[584];
  CPG_Dual.d17[83] = qoco_solver->sol->y[585];
  CPG_Dual.d17[84] = qoco_solver->sol->y[586];
  CPG_Dual.d17[85] = qoco_solver->sol->y[587];
  CPG_Dual.d17[86] = qoco_solver->sol->y[588];
  CPG_Dual.d17[87] = qoco_solver->sol->y[589];
  CPG_Dual.d17[88] = qoco_solver->sol->y[590];
  CPG_Dual.d17[89] = qoco_solver->sol->y[591];
  CPG_Dual.d17[90] = qoco_solver->sol->y[592];
  CPG_Dual.d17[91] = qoco_solver->sol->y[593];
  CPG_Dual.d17[92] = qoco_solver->sol->y[594];
  CPG_Dual.d17[93] = qoco_solver->sol->y[595];
  CPG_Dual.d17[94] = qoco_solver->sol->y[596];
  CPG_Dual.d17[95] = qoco_solver->sol->y[597];
  CPG_Dual.d17[96] = qoco_solver->sol->y[598];
  CPG_Dual.d17[97] = qoco_solver->sol->y[599];
  CPG_Dual.d17[98] = qoco_solver->sol->y[600];
  CPG_Dual.d17[99] = qoco_solver->sol->y[601];
  CPG_Dual.d17[100] = qoco_solver->sol->y[602];
  CPG_Dual.d17[101] = qoco_solver->sol->y[603];
  CPG_Dual.d17[102] = qoco_solver->sol->y[604];
  CPG_Dual.d17[103] = qoco_solver->sol->y[605];
  CPG_Dual.d17[104] = qoco_solver->sol->y[606];
  CPG_Dual.d17[105] = qoco_solver->sol->y[607];
  CPG_Dual.d17[106] = qoco_solver->sol->y[608];
  CPG_Dual.d17[107] = qoco_solver->sol->y[609];
  CPG_Dual.d17[108] = qoco_solver->sol->y[610];
  CPG_Dual.d17[109] = qoco_solver->sol->y[611];
  CPG_Dual.d17[110] = qoco_solver->sol->y[612];
  CPG_Dual.d17[111] = qoco_solver->sol->y[613];
  CPG_Dual.d17[112] = qoco_solver->sol->y[614];
  CPG_Dual.d17[113] = qoco_solver->sol->y[615];
  CPG_Dual.d17[114] = qoco_solver->sol->y[616];
  CPG_Dual.d17[115] = qoco_solver->sol->y[617];
  CPG_Dual.d17[116] = qoco_solver->sol->y[618];
  CPG_Dual.d17[117] = qoco_solver->sol->y[619];
  CPG_Dual.d17[118] = qoco_solver->sol->y[620];
  CPG_Dual.d17[119] = qoco_solver->sol->y[621];
  CPG_Dual.d17[120] = qoco_solver->sol->y[622];
  CPG_Dual.d17[121] = qoco_solver->sol->y[623];
  CPG_Dual.d17[122] = qoco_solver->sol->y[624];
  CPG_Dual.d17[123] = qoco_solver->sol->y[625];
  CPG_Dual.d17[124] = qoco_solver->sol->y[626];
  CPG_Dual.d17[125] = qoco_solver->sol->y[627];
  CPG_Dual.d17[126] = qoco_solver->sol->y[628];
  CPG_Dual.d17[127] = qoco_solver->sol->y[629];
  CPG_Dual.d17[128] = qoco_solver->sol->y[630];
  CPG_Dual.d17[129] = qoco_solver->sol->y[631];
  CPG_Dual.d17[130] = qoco_solver->sol->y[632];
  CPG_Dual.d17[131] = qoco_solver->sol->y[633];
  CPG_Dual.d17[132] = qoco_solver->sol->y[634];
  CPG_Dual.d17[133] = qoco_solver->sol->y[635];
  CPG_Dual.d17[134] = qoco_solver->sol->y[636];
  CPG_Dual.d17[135] = qoco_solver->sol->y[637];
  CPG_Dual.d17[136] = qoco_solver->sol->y[638];
  CPG_Dual.d17[137] = qoco_solver->sol->y[639];
  CPG_Dual.d17[138] = qoco_solver->sol->y[640];
  CPG_Dual.d17[139] = qoco_solver->sol->y[641];
  CPG_Dual.d17[140] = qoco_solver->sol->y[642];
  CPG_Dual.d17[141] = qoco_solver->sol->y[643];
  CPG_Dual.d17[142] = qoco_solver->sol->y[644];
  CPG_Dual.d17[143] = qoco_solver->sol->y[645];
  CPG_Dual.d17[144] = qoco_solver->sol->y[646];
  CPG_Dual.d17[145] = qoco_solver->sol->y[647];
  CPG_Dual.d17[146] = qoco_solver->sol->y[648];
  CPG_Dual.d17[147] = qoco_solver->sol->y[649];
  CPG_Dual.d17[148] = qoco_solver->sol->y[650];
  CPG_Dual.d17[149] = qoco_solver->sol->y[651];
  CPG_Dual.d17[150] = qoco_solver->sol->y[652];
  CPG_Dual.d17[151] = qoco_solver->sol->y[653];
  CPG_Dual.d17[152] = qoco_solver->sol->y[654];
  CPG_Dual.d17[153] = qoco_solver->sol->y[655];
  CPG_Dual.d17[154] = qoco_solver->sol->y[656];
  CPG_Dual.d17[155] = qoco_solver->sol->y[657];
  CPG_Dual.d17[156] = qoco_solver->sol->y[658];
  CPG_Dual.d17[157] = qoco_solver->sol->y[659];
  CPG_Dual.d17[158] = qoco_solver->sol->y[660];
  CPG_Dual.d17[159] = qoco_solver->sol->y[661];
  CPG_Dual.d17[160] = qoco_solver->sol->y[662];
  CPG_Dual.d17[161] = qoco_solver->sol->y[663];
  CPG_Dual.d17[162] = qoco_solver->sol->y[664];
  CPG_Dual.d17[163] = qoco_solver->sol->y[665];
  CPG_Dual.d17[164] = qoco_solver->sol->y[666];
  CPG_Dual.d17[165] = qoco_solver->sol->y[667];
  CPG_Dual.d17[166] = qoco_solver->sol->y[668];
  CPG_Dual.d17[167] = qoco_solver->sol->y[669];
  CPG_Dual.d17[168] = qoco_solver->sol->y[670];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_solver->sol->obj + Canon_Params.d);
  CPG_Info.iter = qoco_solver->sol->iters;
  CPG_Info.status = qoco_solver->sol->status;
  CPG_Info.pri_res = qoco_solver->sol->pres;
  CPG_Info.dua_res = qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_P(){
  for (i=0; i<180; i++){
    Canon_Params_conditioning.P->x[i] = Canon_Params.P->x[i];
  }
}

void cpg_copy_c(){
  for (i=0; i<717; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<4114; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<671; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<1024; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<553; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_P();
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (!qoco_solver ) {
    cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   qoco_set_csc(P, 717, 717, Canon_Params.P->nnz, Canon_Params.P->x, Canon_Params.P->p, Canon_Params.P->i);
   qoco_set_csc(A, 671, 717, Canon_Params.A->nnz, Canon_Params.A->x, Canon_Params.A->p, Canon_Params.A->i);
   qoco_set_csc(G, 553, 717, Canon_Params.G->nnz, Canon_Params.G->x, Canon_Params.G->p, Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(qoco_solver, 717, 553, 671, P, Canon_Params.c, A, Canon_Params.b, G, Canon_Params.h, 483, 20, (int *) &qoco_q, qoco_settings);
  }
  if (Canon_Outdated.b) {
    update_vector_data(qoco_solver, NULL, Canon_Params.b, NULL);
  }
  if (Canon_Outdated.A) {
    update_matrix_data(qoco_solver, NULL, Canon_Params.A->x, NULL);
  }
  qoco_solver->settings->max_iters = Canon_Settings.max_iters;
  qoco_solver->settings->bisect_iters = Canon_Settings.bisect_iters;
  qoco_solver->settings->ruiz_iters = Canon_Settings.ruiz_iters;
  qoco_solver->settings->iter_ref_iters = Canon_Settings.iter_ref_iters;
  qoco_solver->settings->kkt_static_reg = Canon_Settings.kkt_static_reg;
  qoco_solver->settings->kkt_dynamic_reg = Canon_Settings.kkt_dynamic_reg;
  qoco_solver->settings->abstol = Canon_Settings.abstol;
  qoco_solver->settings->reltol = Canon_Settings.reltol;
  qoco_solver->settings->abstol_inacc = Canon_Settings.abstol_inacc;
  qoco_solver->settings->reltol_inacc = Canon_Settings.reltol_inacc;
  qoco_solver->settings->verbose = Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(qoco_solver);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.max_iters = 200;
  Canon_Settings.bisect_iters = 5;
  Canon_Settings.ruiz_iters = 0;
  Canon_Settings.iter_ref_iters = 1;
  Canon_Settings.kkt_static_reg = 1e-8;
  Canon_Settings.kkt_dynamic_reg = 1e-8;
  Canon_Settings.abstol = 1e-7;
  Canon_Settings.reltol = 1e-7;
  Canon_Settings.abstol_inacc = 1e-5;
  Canon_Settings.reltol_inacc = 1e-5;
  Canon_Settings.verbose = 0;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  Canon_Settings.bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}
