function j_a = A_3DoF(t,in2,in3,L,I,alpha)
%A_3DoF
%    J_A = A_3DoF(T,IN2,IN3,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Jun-2025 01:33:53

T = in3(1,:);
delta = in3(2,:);
m1 = in2(7,:);
theta1 = in2(5,:);
t2 = cos(delta);
t3 = sin(delta);
t4 = cos(theta1);
t5 = sin(theta1);
t6 = 1.0./m1;
t7 = t6.^2;
t8 = T.*t2.*t4;
t9 = T.*t2.*t5;
t10 = T.*t3.*t4;
t11 = T.*t3.*t5;
t12 = -t11;
t13 = t9+t10;
t14 = t8+t12;
j_a = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t6.*t13,t6.*t14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-t7.*t14,-t7.*t13,0.0,0.0,0.0],[7,7]);
end
