function j_b = B_3DoF(t,in2,in3,L,I,alpha)
%B_3DoF
%    J_B = B_3DoF(T,IN2,IN3,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Jun-2025 01:33:53

T = in3(1,:);
delta = in3(2,:);
m1 = in2(7,:);
theta1 = in2(5,:);
t2 = cos(delta);
t3 = sin(delta);
t4 = cos(theta1);
t5 = sin(theta1);
t6 = 1.0./I;
t7 = 1.0./m1;
j_b = reshape([0.0,0.0,t7.*(t2.*t4-t3.*t5),t7.*(t2.*t5+t3.*t4),0.0,-L.*t3.*t6,-alpha,0.0,0.0,-t7.*(T.*t2.*t5+T.*t3.*t4),t7.*(T.*t2.*t4-T.*t3.*t5),0.0,-L.*T.*t2.*t6,0.0],[7,2]);
end
