function xdot = dynamics_asteroidmining(t,in2,in3,tf)
%DYNAMICS_ASTEROIDMINING
%    XDOT = DYNAMICS_ASTEROIDMINING(T,IN2,IN3,TF)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    26-Jun-2025 16:26:41

r1 = in2(1,:);
r2 = in2(2,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
v1 = in2(3,:);
v2 = in2(4,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = t2+t3;
t5 = 1.0./t4.^(3.0./2.0);
xdot = [tf.*v1;tf.*v2;tf.*(thrust_accel1-r1.*t5);tf.*(thrust_accel2-r2.*t5)];
end
