function j_p = S_3DoF(t,in2,in3,L,I,alpha)
%S_3DoF
%    J_P = S_3DoF(T,IN2,IN3,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Jun-2025 01:33:53

j_p = [0.0;0.0;0.0;0.0;0.0;0.0;0.0];
end
