function force = SymDynamics3DoF_mass_convexified_Force(t,in2,in3,L,I,alpha)
%SymDynamics3DoF_mass_convexified_Force
%    FORCE = SymDynamics3DoF_mass_convexified_Force(T,IN2,IN3,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-Jun-2025 13:00:31

theta1 = in2(5,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
z1 = in2(7,:);
t2 = cos(theta1);
t3 = exp(z1);
t4 = sin(theta1);
force = [t3.*(t2.*thrust_accel1-t4.*thrust_accel2);t3.*(t2.*thrust_accel2+t4.*thrust_accel1)];
end
