function xdot = SymDynamics3DoF_mass_polar(t,in2,in3,L,I,alpha)
%SymDynamics3DoF_mass_polar
%    XDOT = SymDynamics3DoF_mass_polar(T,IN2,IN3,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    06-Jun-2025 01:33:53

T = in3(1,:);
delta = in3(2,:);
m1 = in2(7,:);
theta1 = in2(5,:);
v1 = in2(3,:);
v2 = in2(4,:);
w1 = in2(6,:);
t2 = cos(delta);
t3 = sin(delta);
t4 = cos(theta1);
t5 = sin(theta1);
t6 = 1.0./m1;
xdot = [v1;v2;t6.*(T.*t2.*t4-T.*t3.*t5);t6.*(T.*t2.*t5+T.*t3.*t4)-3.7114e-3;w1;-(L.*T.*t3)./I;-T.*alpha];
end
