function M = SymDynamics3DoF_mass_convexified_Moment(t,in2,in3,L,I,alpha)
%SymDynamics3DoF_mass_convexified_Moment
%    M = SymDynamics3DoF_mass_convexified_Moment(T,IN2,IN3,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-Jun-2025 13:00:31

thrust_accel2 = in3(2,:);
z1 = in2(7,:);
M = [0.0;0.0;-L.*thrust_accel2.*exp(z1)];
end
