function mdot = SymDynamics3DoF_mass_convexified_MassRate(t,in2,in3,L,I,alpha)
%SymDynamics3DoF_mass_convexified_MassRate
%    MDOT = SymDynamics3DoF_mass_convexified_MassRate(T,IN2,IN3,L,I,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-Jun-2025 13:00:31

thrust_accel_mag1 = in3(3,:);
z1 = in2(7,:);
mdot = -alpha.*thrust_accel_mag1.*exp(z1);
end
