
/*
Auto-generated by CVXPYgen on September 18, 2025 at 16:08:39.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_x_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_u_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+210] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+270] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+466] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+522] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_ck(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+578] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+774] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+970] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1026] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1082] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1278] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1334] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1390] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1586] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1642] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1698] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1894] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1950] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2006] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2202] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2258] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2314] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2510] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2566] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2622] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2818] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2874] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+2930] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3126] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3182] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3238] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3434] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3490] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3546] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3742] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3798] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3854] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4050] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4106] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4162] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4358] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4414] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4470] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_minus_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4666] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_Bk_plus_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4722] = val;
  Canon_Outdated.A = 1;
  Canon_Outdated.b = 1;
}

void cpg_update_x_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4778] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_x_f(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+4792] = val;
  Canon_Outdated.b = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<5974; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<831; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.X[0] = qoco_solver->sol->x[0];
  CPG_Prim.X[1] = qoco_solver->sol->x[1];
  CPG_Prim.X[2] = qoco_solver->sol->x[2];
  CPG_Prim.X[3] = qoco_solver->sol->x[3];
  CPG_Prim.X[4] = qoco_solver->sol->x[4];
  CPG_Prim.X[5] = qoco_solver->sol->x[5];
  CPG_Prim.X[6] = qoco_solver->sol->x[6];
  CPG_Prim.X[7] = qoco_solver->sol->x[7];
  CPG_Prim.X[8] = qoco_solver->sol->x[8];
  CPG_Prim.X[9] = qoco_solver->sol->x[9];
  CPG_Prim.X[10] = qoco_solver->sol->x[10];
  CPG_Prim.X[11] = qoco_solver->sol->x[11];
  CPG_Prim.X[12] = qoco_solver->sol->x[12];
  CPG_Prim.X[13] = qoco_solver->sol->x[13];
  CPG_Prim.X[14] = qoco_solver->sol->x[14];
  CPG_Prim.X[15] = qoco_solver->sol->x[15];
  CPG_Prim.X[16] = qoco_solver->sol->x[16];
  CPG_Prim.X[17] = qoco_solver->sol->x[17];
  CPG_Prim.X[18] = qoco_solver->sol->x[18];
  CPG_Prim.X[19] = qoco_solver->sol->x[19];
  CPG_Prim.X[20] = qoco_solver->sol->x[20];
  CPG_Prim.X[21] = qoco_solver->sol->x[21];
  CPG_Prim.X[22] = qoco_solver->sol->x[22];
  CPG_Prim.X[23] = qoco_solver->sol->x[23];
  CPG_Prim.X[24] = qoco_solver->sol->x[24];
  CPG_Prim.X[25] = qoco_solver->sol->x[25];
  CPG_Prim.X[26] = qoco_solver->sol->x[26];
  CPG_Prim.X[27] = qoco_solver->sol->x[27];
  CPG_Prim.X[28] = qoco_solver->sol->x[28];
  CPG_Prim.X[29] = qoco_solver->sol->x[29];
  CPG_Prim.X[30] = qoco_solver->sol->x[30];
  CPG_Prim.X[31] = qoco_solver->sol->x[31];
  CPG_Prim.X[32] = qoco_solver->sol->x[32];
  CPG_Prim.X[33] = qoco_solver->sol->x[33];
  CPG_Prim.X[34] = qoco_solver->sol->x[34];
  CPG_Prim.X[35] = qoco_solver->sol->x[35];
  CPG_Prim.X[36] = qoco_solver->sol->x[36];
  CPG_Prim.X[37] = qoco_solver->sol->x[37];
  CPG_Prim.X[38] = qoco_solver->sol->x[38];
  CPG_Prim.X[39] = qoco_solver->sol->x[39];
  CPG_Prim.X[40] = qoco_solver->sol->x[40];
  CPG_Prim.X[41] = qoco_solver->sol->x[41];
  CPG_Prim.X[42] = qoco_solver->sol->x[42];
  CPG_Prim.X[43] = qoco_solver->sol->x[43];
  CPG_Prim.X[44] = qoco_solver->sol->x[44];
  CPG_Prim.X[45] = qoco_solver->sol->x[45];
  CPG_Prim.X[46] = qoco_solver->sol->x[46];
  CPG_Prim.X[47] = qoco_solver->sol->x[47];
  CPG_Prim.X[48] = qoco_solver->sol->x[48];
  CPG_Prim.X[49] = qoco_solver->sol->x[49];
  CPG_Prim.X[50] = qoco_solver->sol->x[50];
  CPG_Prim.X[51] = qoco_solver->sol->x[51];
  CPG_Prim.X[52] = qoco_solver->sol->x[52];
  CPG_Prim.X[53] = qoco_solver->sol->x[53];
  CPG_Prim.X[54] = qoco_solver->sol->x[54];
  CPG_Prim.X[55] = qoco_solver->sol->x[55];
  CPG_Prim.X[56] = qoco_solver->sol->x[56];
  CPG_Prim.X[57] = qoco_solver->sol->x[57];
  CPG_Prim.X[58] = qoco_solver->sol->x[58];
  CPG_Prim.X[59] = qoco_solver->sol->x[59];
  CPG_Prim.X[60] = qoco_solver->sol->x[60];
  CPG_Prim.X[61] = qoco_solver->sol->x[61];
  CPG_Prim.X[62] = qoco_solver->sol->x[62];
  CPG_Prim.X[63] = qoco_solver->sol->x[63];
  CPG_Prim.X[64] = qoco_solver->sol->x[64];
  CPG_Prim.X[65] = qoco_solver->sol->x[65];
  CPG_Prim.X[66] = qoco_solver->sol->x[66];
  CPG_Prim.X[67] = qoco_solver->sol->x[67];
  CPG_Prim.X[68] = qoco_solver->sol->x[68];
  CPG_Prim.X[69] = qoco_solver->sol->x[69];
  CPG_Prim.X[70] = qoco_solver->sol->x[70];
  CPG_Prim.X[71] = qoco_solver->sol->x[71];
  CPG_Prim.X[72] = qoco_solver->sol->x[72];
  CPG_Prim.X[73] = qoco_solver->sol->x[73];
  CPG_Prim.X[74] = qoco_solver->sol->x[74];
  CPG_Prim.X[75] = qoco_solver->sol->x[75];
  CPG_Prim.X[76] = qoco_solver->sol->x[76];
  CPG_Prim.X[77] = qoco_solver->sol->x[77];
  CPG_Prim.X[78] = qoco_solver->sol->x[78];
  CPG_Prim.X[79] = qoco_solver->sol->x[79];
  CPG_Prim.X[80] = qoco_solver->sol->x[80];
  CPG_Prim.X[81] = qoco_solver->sol->x[81];
  CPG_Prim.X[82] = qoco_solver->sol->x[82];
  CPG_Prim.X[83] = qoco_solver->sol->x[83];
  CPG_Prim.X[84] = qoco_solver->sol->x[84];
  CPG_Prim.X[85] = qoco_solver->sol->x[85];
  CPG_Prim.X[86] = qoco_solver->sol->x[86];
  CPG_Prim.X[87] = qoco_solver->sol->x[87];
  CPG_Prim.X[88] = qoco_solver->sol->x[88];
  CPG_Prim.X[89] = qoco_solver->sol->x[89];
  CPG_Prim.X[90] = qoco_solver->sol->x[90];
  CPG_Prim.X[91] = qoco_solver->sol->x[91];
  CPG_Prim.X[92] = qoco_solver->sol->x[92];
  CPG_Prim.X[93] = qoco_solver->sol->x[93];
  CPG_Prim.X[94] = qoco_solver->sol->x[94];
  CPG_Prim.X[95] = qoco_solver->sol->x[95];
  CPG_Prim.X[96] = qoco_solver->sol->x[96];
  CPG_Prim.X[97] = qoco_solver->sol->x[97];
  CPG_Prim.X[98] = qoco_solver->sol->x[98];
  CPG_Prim.X[99] = qoco_solver->sol->x[99];
  CPG_Prim.X[100] = qoco_solver->sol->x[100];
  CPG_Prim.X[101] = qoco_solver->sol->x[101];
  CPG_Prim.X[102] = qoco_solver->sol->x[102];
  CPG_Prim.X[103] = qoco_solver->sol->x[103];
  CPG_Prim.X[104] = qoco_solver->sol->x[104];
  CPG_Prim.X[105] = qoco_solver->sol->x[105];
  CPG_Prim.X[106] = qoco_solver->sol->x[106];
  CPG_Prim.X[107] = qoco_solver->sol->x[107];
  CPG_Prim.X[108] = qoco_solver->sol->x[108];
  CPG_Prim.X[109] = qoco_solver->sol->x[109];
  CPG_Prim.X[110] = qoco_solver->sol->x[110];
  CPG_Prim.X[111] = qoco_solver->sol->x[111];
  CPG_Prim.X[112] = qoco_solver->sol->x[112];
  CPG_Prim.X[113] = qoco_solver->sol->x[113];
  CPG_Prim.X[114] = qoco_solver->sol->x[114];
  CPG_Prim.X[115] = qoco_solver->sol->x[115];
  CPG_Prim.X[116] = qoco_solver->sol->x[116];
  CPG_Prim.X[117] = qoco_solver->sol->x[117];
  CPG_Prim.X[118] = qoco_solver->sol->x[118];
  CPG_Prim.X[119] = qoco_solver->sol->x[119];
  CPG_Prim.X[120] = qoco_solver->sol->x[120];
  CPG_Prim.X[121] = qoco_solver->sol->x[121];
  CPG_Prim.X[122] = qoco_solver->sol->x[122];
  CPG_Prim.X[123] = qoco_solver->sol->x[123];
  CPG_Prim.X[124] = qoco_solver->sol->x[124];
  CPG_Prim.X[125] = qoco_solver->sol->x[125];
  CPG_Prim.X[126] = qoco_solver->sol->x[126];
  CPG_Prim.X[127] = qoco_solver->sol->x[127];
  CPG_Prim.X[128] = qoco_solver->sol->x[128];
  CPG_Prim.X[129] = qoco_solver->sol->x[129];
  CPG_Prim.X[130] = qoco_solver->sol->x[130];
  CPG_Prim.X[131] = qoco_solver->sol->x[131];
  CPG_Prim.X[132] = qoco_solver->sol->x[132];
  CPG_Prim.X[133] = qoco_solver->sol->x[133];
  CPG_Prim.X[134] = qoco_solver->sol->x[134];
  CPG_Prim.X[135] = qoco_solver->sol->x[135];
  CPG_Prim.X[136] = qoco_solver->sol->x[136];
  CPG_Prim.X[137] = qoco_solver->sol->x[137];
  CPG_Prim.X[138] = qoco_solver->sol->x[138];
  CPG_Prim.X[139] = qoco_solver->sol->x[139];
  CPG_Prim.X[140] = qoco_solver->sol->x[140];
  CPG_Prim.X[141] = qoco_solver->sol->x[141];
  CPG_Prim.X[142] = qoco_solver->sol->x[142];
  CPG_Prim.X[143] = qoco_solver->sol->x[143];
  CPG_Prim.X[144] = qoco_solver->sol->x[144];
  CPG_Prim.X[145] = qoco_solver->sol->x[145];
  CPG_Prim.X[146] = qoco_solver->sol->x[146];
  CPG_Prim.X[147] = qoco_solver->sol->x[147];
  CPG_Prim.X[148] = qoco_solver->sol->x[148];
  CPG_Prim.X[149] = qoco_solver->sol->x[149];
  CPG_Prim.X[150] = qoco_solver->sol->x[150];
  CPG_Prim.X[151] = qoco_solver->sol->x[151];
  CPG_Prim.X[152] = qoco_solver->sol->x[152];
  CPG_Prim.X[153] = qoco_solver->sol->x[153];
  CPG_Prim.X[154] = qoco_solver->sol->x[154];
  CPG_Prim.X[155] = qoco_solver->sol->x[155];
  CPG_Prim.X[156] = qoco_solver->sol->x[156];
  CPG_Prim.X[157] = qoco_solver->sol->x[157];
  CPG_Prim.X[158] = qoco_solver->sol->x[158];
  CPG_Prim.X[159] = qoco_solver->sol->x[159];
  CPG_Prim.X[160] = qoco_solver->sol->x[160];
  CPG_Prim.X[161] = qoco_solver->sol->x[161];
  CPG_Prim.X[162] = qoco_solver->sol->x[162];
  CPG_Prim.X[163] = qoco_solver->sol->x[163];
  CPG_Prim.X[164] = qoco_solver->sol->x[164];
  CPG_Prim.X[165] = qoco_solver->sol->x[165];
  CPG_Prim.X[166] = qoco_solver->sol->x[166];
  CPG_Prim.X[167] = qoco_solver->sol->x[167];
  CPG_Prim.X[168] = qoco_solver->sol->x[168];
  CPG_Prim.X[169] = qoco_solver->sol->x[169];
  CPG_Prim.X[170] = qoco_solver->sol->x[170];
  CPG_Prim.X[171] = qoco_solver->sol->x[171];
  CPG_Prim.X[172] = qoco_solver->sol->x[172];
  CPG_Prim.X[173] = qoco_solver->sol->x[173];
  CPG_Prim.X[174] = qoco_solver->sol->x[174];
  CPG_Prim.X[175] = qoco_solver->sol->x[175];
  CPG_Prim.X[176] = qoco_solver->sol->x[176];
  CPG_Prim.X[177] = qoco_solver->sol->x[177];
  CPG_Prim.X[178] = qoco_solver->sol->x[178];
  CPG_Prim.X[179] = qoco_solver->sol->x[179];
  CPG_Prim.X[180] = qoco_solver->sol->x[180];
  CPG_Prim.X[181] = qoco_solver->sol->x[181];
  CPG_Prim.X[182] = qoco_solver->sol->x[182];
  CPG_Prim.X[183] = qoco_solver->sol->x[183];
  CPG_Prim.X[184] = qoco_solver->sol->x[184];
  CPG_Prim.X[185] = qoco_solver->sol->x[185];
  CPG_Prim.X[186] = qoco_solver->sol->x[186];
  CPG_Prim.X[187] = qoco_solver->sol->x[187];
  CPG_Prim.X[188] = qoco_solver->sol->x[188];
  CPG_Prim.X[189] = qoco_solver->sol->x[189];
  CPG_Prim.X[190] = qoco_solver->sol->x[190];
  CPG_Prim.X[191] = qoco_solver->sol->x[191];
  CPG_Prim.X[192] = qoco_solver->sol->x[192];
  CPG_Prim.X[193] = qoco_solver->sol->x[193];
  CPG_Prim.X[194] = qoco_solver->sol->x[194];
  CPG_Prim.X[195] = qoco_solver->sol->x[195];
  CPG_Prim.X[196] = qoco_solver->sol->x[196];
  CPG_Prim.X[197] = qoco_solver->sol->x[197];
  CPG_Prim.X[198] = qoco_solver->sol->x[198];
  CPG_Prim.X[199] = qoco_solver->sol->x[199];
  CPG_Prim.X[200] = qoco_solver->sol->x[200];
  CPG_Prim.X[201] = qoco_solver->sol->x[201];
  CPG_Prim.X[202] = qoco_solver->sol->x[202];
  CPG_Prim.X[203] = qoco_solver->sol->x[203];
  CPG_Prim.X[204] = qoco_solver->sol->x[204];
  CPG_Prim.X[205] = qoco_solver->sol->x[205];
  CPG_Prim.X[206] = qoco_solver->sol->x[206];
  CPG_Prim.X[207] = qoco_solver->sol->x[207];
  CPG_Prim.X[208] = qoco_solver->sol->x[208];
  CPG_Prim.X[209] = qoco_solver->sol->x[209];
  CPG_Prim.U[0] = qoco_solver->sol->x[693];
  CPG_Prim.U[1] = qoco_solver->sol->x[694];
  CPG_Prim.U[2] = qoco_solver->sol->x[695];
  CPG_Prim.U[3] = qoco_solver->sol->x[696];
  CPG_Prim.U[4] = qoco_solver->sol->x[697];
  CPG_Prim.U[5] = qoco_solver->sol->x[698];
  CPG_Prim.U[6] = qoco_solver->sol->x[699];
  CPG_Prim.U[7] = qoco_solver->sol->x[700];
  CPG_Prim.U[8] = qoco_solver->sol->x[701];
  CPG_Prim.U[9] = qoco_solver->sol->x[702];
  CPG_Prim.U[10] = qoco_solver->sol->x[703];
  CPG_Prim.U[11] = qoco_solver->sol->x[704];
  CPG_Prim.U[12] = qoco_solver->sol->x[705];
  CPG_Prim.U[13] = qoco_solver->sol->x[706];
  CPG_Prim.U[14] = qoco_solver->sol->x[707];
  CPG_Prim.U[15] = qoco_solver->sol->x[708];
  CPG_Prim.U[16] = qoco_solver->sol->x[709];
  CPG_Prim.U[17] = qoco_solver->sol->x[710];
  CPG_Prim.U[18] = qoco_solver->sol->x[711];
  CPG_Prim.U[19] = qoco_solver->sol->x[712];
  CPG_Prim.U[20] = qoco_solver->sol->x[713];
  CPG_Prim.U[21] = qoco_solver->sol->x[714];
  CPG_Prim.U[22] = qoco_solver->sol->x[715];
  CPG_Prim.U[23] = qoco_solver->sol->x[716];
  CPG_Prim.U[24] = qoco_solver->sol->x[717];
  CPG_Prim.U[25] = qoco_solver->sol->x[718];
  CPG_Prim.U[26] = qoco_solver->sol->x[719];
  CPG_Prim.U[27] = qoco_solver->sol->x[720];
  CPG_Prim.U[28] = qoco_solver->sol->x[721];
  CPG_Prim.U[29] = qoco_solver->sol->x[722];
  CPG_Prim.U[30] = qoco_solver->sol->x[723];
  CPG_Prim.U[31] = qoco_solver->sol->x[724];
  CPG_Prim.U[32] = qoco_solver->sol->x[725];
  CPG_Prim.U[33] = qoco_solver->sol->x[726];
  CPG_Prim.U[34] = qoco_solver->sol->x[727];
  CPG_Prim.U[35] = qoco_solver->sol->x[728];
  CPG_Prim.U[36] = qoco_solver->sol->x[729];
  CPG_Prim.U[37] = qoco_solver->sol->x[730];
  CPG_Prim.U[38] = qoco_solver->sol->x[731];
  CPG_Prim.U[39] = qoco_solver->sol->x[732];
  CPG_Prim.U[40] = qoco_solver->sol->x[733];
  CPG_Prim.U[41] = qoco_solver->sol->x[734];
  CPG_Prim.U[42] = qoco_solver->sol->x[735];
  CPG_Prim.U[43] = qoco_solver->sol->x[736];
  CPG_Prim.U[44] = qoco_solver->sol->x[737];
  CPG_Prim.U[45] = qoco_solver->sol->x[738];
  CPG_Prim.U[46] = qoco_solver->sol->x[739];
  CPG_Prim.U[47] = qoco_solver->sol->x[740];
  CPG_Prim.U[48] = qoco_solver->sol->x[741];
  CPG_Prim.U[49] = qoco_solver->sol->x[742];
  CPG_Prim.U[50] = qoco_solver->sol->x[743];
  CPG_Prim.U[51] = qoco_solver->sol->x[744];
  CPG_Prim.U[52] = qoco_solver->sol->x[745];
  CPG_Prim.U[53] = qoco_solver->sol->x[746];
  CPG_Prim.U[54] = qoco_solver->sol->x[747];
  CPG_Prim.U[55] = qoco_solver->sol->x[748];
  CPG_Prim.U[56] = qoco_solver->sol->x[749];
  CPG_Prim.U[57] = qoco_solver->sol->x[750];
  CPG_Prim.U[58] = qoco_solver->sol->x[751];
  CPG_Prim.U[59] = qoco_solver->sol->x[752];
  CPG_Prim.V[0] = qoco_solver->sol->x[753];
  CPG_Prim.V[1] = qoco_solver->sol->x[754];
  CPG_Prim.V[2] = qoco_solver->sol->x[755];
  CPG_Prim.V[3] = qoco_solver->sol->x[756];
  CPG_Prim.V[4] = qoco_solver->sol->x[757];
  CPG_Prim.V[5] = qoco_solver->sol->x[758];
  CPG_Prim.V[6] = qoco_solver->sol->x[759];
  CPG_Prim.V[7] = qoco_solver->sol->x[760];
  CPG_Prim.V[8] = qoco_solver->sol->x[761];
  CPG_Prim.V[9] = qoco_solver->sol->x[762];
  CPG_Prim.V[10] = qoco_solver->sol->x[763];
  CPG_Prim.V[11] = qoco_solver->sol->x[764];
  CPG_Prim.V[12] = qoco_solver->sol->x[765];
  CPG_Prim.V[13] = qoco_solver->sol->x[766];
  CPG_Prim.V[14] = qoco_solver->sol->x[767];
  CPG_Prim.V[15] = qoco_solver->sol->x[768];
  CPG_Prim.V[16] = qoco_solver->sol->x[769];
  CPG_Prim.V[17] = qoco_solver->sol->x[770];
  CPG_Prim.V[18] = qoco_solver->sol->x[771];
  CPG_Prim.V[19] = qoco_solver->sol->x[772];
  CPG_Prim.V[20] = qoco_solver->sol->x[773];
  CPG_Prim.V[21] = qoco_solver->sol->x[774];
  CPG_Prim.V[22] = qoco_solver->sol->x[775];
  CPG_Prim.V[23] = qoco_solver->sol->x[776];
  CPG_Prim.V[24] = qoco_solver->sol->x[777];
  CPG_Prim.V[25] = qoco_solver->sol->x[778];
  CPG_Prim.V[26] = qoco_solver->sol->x[779];
  CPG_Prim.V[27] = qoco_solver->sol->x[780];
  CPG_Prim.V[28] = qoco_solver->sol->x[781];
  CPG_Prim.V[29] = qoco_solver->sol->x[782];
  CPG_Prim.V[30] = qoco_solver->sol->x[783];
  CPG_Prim.V[31] = qoco_solver->sol->x[784];
  CPG_Prim.V[32] = qoco_solver->sol->x[785];
  CPG_Prim.V[33] = qoco_solver->sol->x[786];
  CPG_Prim.V[34] = qoco_solver->sol->x[787];
  CPG_Prim.V[35] = qoco_solver->sol->x[788];
  CPG_Prim.V[36] = qoco_solver->sol->x[789];
  CPG_Prim.V[37] = qoco_solver->sol->x[790];
  CPG_Prim.V[38] = qoco_solver->sol->x[791];
  CPG_Prim.V[39] = qoco_solver->sol->x[792];
  CPG_Prim.V[40] = qoco_solver->sol->x[793];
  CPG_Prim.V[41] = qoco_solver->sol->x[794];
  CPG_Prim.V[42] = qoco_solver->sol->x[795];
  CPG_Prim.V[43] = qoco_solver->sol->x[796];
  CPG_Prim.V[44] = qoco_solver->sol->x[797];
  CPG_Prim.V[45] = qoco_solver->sol->x[798];
  CPG_Prim.V[46] = qoco_solver->sol->x[799];
  CPG_Prim.V[47] = qoco_solver->sol->x[800];
  CPG_Prim.V[48] = qoco_solver->sol->x[801];
  CPG_Prim.V[49] = qoco_solver->sol->x[802];
  CPG_Prim.V[50] = qoco_solver->sol->x[803];
  CPG_Prim.V[51] = qoco_solver->sol->x[804];
  CPG_Prim.V[52] = qoco_solver->sol->x[805];
  CPG_Prim.V[53] = qoco_solver->sol->x[806];
  CPG_Prim.V[54] = qoco_solver->sol->x[807];
  CPG_Prim.V[55] = qoco_solver->sol->x[808];
  CPG_Prim.V[56] = qoco_solver->sol->x[809];
  CPG_Prim.V[57] = qoco_solver->sol->x[810];
  CPG_Prim.V[58] = qoco_solver->sol->x[811];
  CPG_Prim.V[59] = qoco_solver->sol->x[812];
  CPG_Prim.V[60] = qoco_solver->sol->x[813];
  CPG_Prim.V[61] = qoco_solver->sol->x[814];
  CPG_Prim.V[62] = qoco_solver->sol->x[815];
  CPG_Prim.V[63] = qoco_solver->sol->x[816];
  CPG_Prim.V[64] = qoco_solver->sol->x[817];
  CPG_Prim.V[65] = qoco_solver->sol->x[818];
  CPG_Prim.V[66] = qoco_solver->sol->x[819];
  CPG_Prim.V[67] = qoco_solver->sol->x[820];
  CPG_Prim.V[68] = qoco_solver->sol->x[821];
  CPG_Prim.V[69] = qoco_solver->sol->x[822];
  CPG_Prim.V[70] = qoco_solver->sol->x[823];
  CPG_Prim.V[71] = qoco_solver->sol->x[824];
  CPG_Prim.V[72] = qoco_solver->sol->x[825];
  CPG_Prim.V[73] = qoco_solver->sol->x[826];
  CPG_Prim.V[74] = qoco_solver->sol->x[827];
  CPG_Prim.V[75] = qoco_solver->sol->x[828];
  CPG_Prim.V[76] = qoco_solver->sol->x[829];
  CPG_Prim.V[77] = qoco_solver->sol->x[830];
  CPG_Prim.V[78] = qoco_solver->sol->x[831];
  CPG_Prim.V[79] = qoco_solver->sol->x[832];
  CPG_Prim.V[80] = qoco_solver->sol->x[833];
  CPG_Prim.V[81] = qoco_solver->sol->x[834];
  CPG_Prim.V[82] = qoco_solver->sol->x[835];
  CPG_Prim.V[83] = qoco_solver->sol->x[836];
  CPG_Prim.V[84] = qoco_solver->sol->x[837];
  CPG_Prim.V[85] = qoco_solver->sol->x[838];
  CPG_Prim.V[86] = qoco_solver->sol->x[839];
  CPG_Prim.V[87] = qoco_solver->sol->x[840];
  CPG_Prim.V[88] = qoco_solver->sol->x[841];
  CPG_Prim.V[89] = qoco_solver->sol->x[842];
  CPG_Prim.V[90] = qoco_solver->sol->x[843];
  CPG_Prim.V[91] = qoco_solver->sol->x[844];
  CPG_Prim.V[92] = qoco_solver->sol->x[845];
  CPG_Prim.V[93] = qoco_solver->sol->x[846];
  CPG_Prim.V[94] = qoco_solver->sol->x[847];
  CPG_Prim.V[95] = qoco_solver->sol->x[848];
  CPG_Prim.V[96] = qoco_solver->sol->x[849];
  CPG_Prim.V[97] = qoco_solver->sol->x[850];
  CPG_Prim.V[98] = qoco_solver->sol->x[851];
  CPG_Prim.V[99] = qoco_solver->sol->x[852];
  CPG_Prim.V[100] = qoco_solver->sol->x[853];
  CPG_Prim.V[101] = qoco_solver->sol->x[854];
  CPG_Prim.V[102] = qoco_solver->sol->x[855];
  CPG_Prim.V[103] = qoco_solver->sol->x[856];
  CPG_Prim.V[104] = qoco_solver->sol->x[857];
  CPG_Prim.V[105] = qoco_solver->sol->x[858];
  CPG_Prim.V[106] = qoco_solver->sol->x[859];
  CPG_Prim.V[107] = qoco_solver->sol->x[860];
  CPG_Prim.V[108] = qoco_solver->sol->x[861];
  CPG_Prim.V[109] = qoco_solver->sol->x[862];
  CPG_Prim.V[110] = qoco_solver->sol->x[863];
  CPG_Prim.V[111] = qoco_solver->sol->x[864];
  CPG_Prim.V[112] = qoco_solver->sol->x[865];
  CPG_Prim.V[113] = qoco_solver->sol->x[866];
  CPG_Prim.V[114] = qoco_solver->sol->x[867];
  CPG_Prim.V[115] = qoco_solver->sol->x[868];
  CPG_Prim.V[116] = qoco_solver->sol->x[869];
  CPG_Prim.V[117] = qoco_solver->sol->x[870];
  CPG_Prim.V[118] = qoco_solver->sol->x[871];
  CPG_Prim.V[119] = qoco_solver->sol->x[872];
  CPG_Prim.V[120] = qoco_solver->sol->x[873];
  CPG_Prim.V[121] = qoco_solver->sol->x[874];
  CPG_Prim.V[122] = qoco_solver->sol->x[875];
  CPG_Prim.V[123] = qoco_solver->sol->x[876];
  CPG_Prim.V[124] = qoco_solver->sol->x[877];
  CPG_Prim.V[125] = qoco_solver->sol->x[878];
  CPG_Prim.V[126] = qoco_solver->sol->x[879];
  CPG_Prim.V[127] = qoco_solver->sol->x[880];
  CPG_Prim.V[128] = qoco_solver->sol->x[881];
  CPG_Prim.V[129] = qoco_solver->sol->x[882];
  CPG_Prim.V[130] = qoco_solver->sol->x[883];
  CPG_Prim.V[131] = qoco_solver->sol->x[884];
  CPG_Prim.V[132] = qoco_solver->sol->x[885];
  CPG_Prim.V[133] = qoco_solver->sol->x[886];
  CPG_Prim.V[134] = qoco_solver->sol->x[887];
  CPG_Prim.V[135] = qoco_solver->sol->x[888];
  CPG_Prim.V[136] = qoco_solver->sol->x[889];
  CPG_Prim.V[137] = qoco_solver->sol->x[890];
  CPG_Prim.V[138] = qoco_solver->sol->x[891];
  CPG_Prim.V[139] = qoco_solver->sol->x[892];
  CPG_Prim.V[140] = qoco_solver->sol->x[893];
  CPG_Prim.V[141] = qoco_solver->sol->x[894];
  CPG_Prim.V[142] = qoco_solver->sol->x[895];
  CPG_Prim.V[143] = qoco_solver->sol->x[896];
  CPG_Prim.V[144] = qoco_solver->sol->x[897];
  CPG_Prim.V[145] = qoco_solver->sol->x[898];
  CPG_Prim.V[146] = qoco_solver->sol->x[899];
  CPG_Prim.V[147] = qoco_solver->sol->x[900];
  CPG_Prim.V[148] = qoco_solver->sol->x[901];
  CPG_Prim.V[149] = qoco_solver->sol->x[902];
  CPG_Prim.V[150] = qoco_solver->sol->x[903];
  CPG_Prim.V[151] = qoco_solver->sol->x[904];
  CPG_Prim.V[152] = qoco_solver->sol->x[905];
  CPG_Prim.V[153] = qoco_solver->sol->x[906];
  CPG_Prim.V[154] = qoco_solver->sol->x[907];
  CPG_Prim.V[155] = qoco_solver->sol->x[908];
  CPG_Prim.V[156] = qoco_solver->sol->x[909];
  CPG_Prim.V[157] = qoco_solver->sol->x[910];
  CPG_Prim.V[158] = qoco_solver->sol->x[911];
  CPG_Prim.V[159] = qoco_solver->sol->x[912];
  CPG_Prim.V[160] = qoco_solver->sol->x[913];
  CPG_Prim.V[161] = qoco_solver->sol->x[914];
  CPG_Prim.V[162] = qoco_solver->sol->x[915];
  CPG_Prim.V[163] = qoco_solver->sol->x[916];
  CPG_Prim.V[164] = qoco_solver->sol->x[917];
  CPG_Prim.V[165] = qoco_solver->sol->x[918];
  CPG_Prim.V[166] = qoco_solver->sol->x[919];
  CPG_Prim.V[167] = qoco_solver->sol->x[920];
  CPG_Prim.V[168] = qoco_solver->sol->x[921];
  CPG_Prim.V[169] = qoco_solver->sol->x[922];
  CPG_Prim.V[170] = qoco_solver->sol->x[923];
  CPG_Prim.V[171] = qoco_solver->sol->x[924];
  CPG_Prim.V[172] = qoco_solver->sol->x[925];
  CPG_Prim.V[173] = qoco_solver->sol->x[926];
  CPG_Prim.V[174] = qoco_solver->sol->x[927];
  CPG_Prim.V[175] = qoco_solver->sol->x[928];
  CPG_Prim.V[176] = qoco_solver->sol->x[929];
  CPG_Prim.V[177] = qoco_solver->sol->x[930];
  CPG_Prim.V[178] = qoco_solver->sol->x[931];
  CPG_Prim.V[179] = qoco_solver->sol->x[932];
  CPG_Prim.V[180] = qoco_solver->sol->x[933];
  CPG_Prim.V[181] = qoco_solver->sol->x[934];
  CPG_Prim.V[182] = qoco_solver->sol->x[935];
  CPG_Prim.V[183] = qoco_solver->sol->x[936];
  CPG_Prim.V[184] = qoco_solver->sol->x[937];
  CPG_Prim.V[185] = qoco_solver->sol->x[938];
  CPG_Prim.V[186] = qoco_solver->sol->x[939];
  CPG_Prim.V[187] = qoco_solver->sol->x[940];
  CPG_Prim.V[188] = qoco_solver->sol->x[941];
  CPG_Prim.V[189] = qoco_solver->sol->x[942];
  CPG_Prim.V[190] = qoco_solver->sol->x[943];
  CPG_Prim.V[191] = qoco_solver->sol->x[944];
  CPG_Prim.V[192] = qoco_solver->sol->x[945];
  CPG_Prim.V[193] = qoco_solver->sol->x[946];
  CPG_Prim.V[194] = qoco_solver->sol->x[947];
  CPG_Prim.V[195] = qoco_solver->sol->x[948];
  CPG_Prim.v_0[0] = qoco_solver->sol->x[949];
  CPG_Prim.v_0[1] = qoco_solver->sol->x[950];
  CPG_Prim.v_0[2] = qoco_solver->sol->x[951];
  CPG_Prim.v_0[3] = qoco_solver->sol->x[952];
  CPG_Prim.v_0[4] = qoco_solver->sol->x[953];
  CPG_Prim.v_0[5] = qoco_solver->sol->x[954];
  CPG_Prim.v_0[6] = qoco_solver->sol->x[955];
  CPG_Prim.v_0[7] = qoco_solver->sol->x[956];
  CPG_Prim.v_0[8] = qoco_solver->sol->x[957];
  CPG_Prim.v_0[9] = qoco_solver->sol->x[958];
  CPG_Prim.v_0[10] = qoco_solver->sol->x[959];
  CPG_Prim.v_0[11] = qoco_solver->sol->x[960];
  CPG_Prim.v_0[12] = qoco_solver->sol->x[961];
  CPG_Prim.v_0[13] = qoco_solver->sol->x[962];
  CPG_Prim.v_N[0] = qoco_solver->sol->x[977];
  CPG_Prim.v_N[1] = qoco_solver->sol->x[978];
  CPG_Prim.v_N[2] = qoco_solver->sol->x[979];
  CPG_Prim.v_N[3] = qoco_solver->sol->x[980];
  CPG_Prim.v_N[4] = qoco_solver->sol->x[981];
  CPG_Prim.v_N[5] = qoco_solver->sol->x[982];
  CPG_Prim.v_N[6] = qoco_solver->sol->x[983];
  CPG_Prim.v_N[7] = qoco_solver->sol->x[984];
  CPG_Prim.v_N[8] = qoco_solver->sol->x[985];
  CPG_Prim.v_N[9] = qoco_solver->sol->x[986];
  CPG_Prim.v_N[10] = qoco_solver->sol->x[987];
  CPG_Prim.v_N[11] = qoco_solver->sol->x[988];
  CPG_Prim.v_N[12] = qoco_solver->sol->x[989];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = qoco_solver->sol->y[270];
  CPG_Dual.d0[1] = qoco_solver->sol->y[271];
  CPG_Dual.d0[2] = qoco_solver->sol->y[272];
  CPG_Dual.d0[3] = qoco_solver->sol->y[273];
  CPG_Dual.d0[4] = qoco_solver->sol->y[274];
  CPG_Dual.d0[5] = qoco_solver->sol->y[275];
  CPG_Dual.d0[6] = qoco_solver->sol->y[276];
  CPG_Dual.d0[7] = qoco_solver->sol->y[277];
  CPG_Dual.d0[8] = qoco_solver->sol->y[278];
  CPG_Dual.d0[9] = qoco_solver->sol->y[279];
  CPG_Dual.d0[10] = qoco_solver->sol->y[280];
  CPG_Dual.d0[11] = qoco_solver->sol->y[281];
  CPG_Dual.d0[12] = qoco_solver->sol->y[282];
  CPG_Dual.d0[13] = qoco_solver->sol->y[283];
  CPG_Dual.d1[0] = qoco_solver->sol->y[284];
  CPG_Dual.d1[1] = qoco_solver->sol->y[285];
  CPG_Dual.d1[2] = qoco_solver->sol->y[286];
  CPG_Dual.d1[3] = qoco_solver->sol->y[287];
  CPG_Dual.d1[4] = qoco_solver->sol->y[288];
  CPG_Dual.d1[5] = qoco_solver->sol->y[289];
  CPG_Dual.d1[6] = qoco_solver->sol->y[290];
  CPG_Dual.d1[7] = qoco_solver->sol->y[291];
  CPG_Dual.d1[8] = qoco_solver->sol->y[292];
  CPG_Dual.d1[9] = qoco_solver->sol->y[293];
  CPG_Dual.d1[10] = qoco_solver->sol->y[294];
  CPG_Dual.d1[11] = qoco_solver->sol->y[295];
  CPG_Dual.d1[12] = qoco_solver->sol->y[296];
  CPG_Dual.d1[13] = qoco_solver->sol->y[297];
  CPG_Dual.d2[0] = qoco_solver->sol->y[298];
  CPG_Dual.d2[1] = qoco_solver->sol->y[299];
  CPG_Dual.d2[2] = qoco_solver->sol->y[300];
  CPG_Dual.d2[3] = qoco_solver->sol->y[301];
  CPG_Dual.d2[4] = qoco_solver->sol->y[302];
  CPG_Dual.d2[5] = qoco_solver->sol->y[303];
  CPG_Dual.d2[6] = qoco_solver->sol->y[304];
  CPG_Dual.d2[7] = qoco_solver->sol->y[305];
  CPG_Dual.d2[8] = qoco_solver->sol->y[306];
  CPG_Dual.d2[9] = qoco_solver->sol->y[307];
  CPG_Dual.d2[10] = qoco_solver->sol->y[308];
  CPG_Dual.d2[11] = qoco_solver->sol->y[309];
  CPG_Dual.d2[12] = qoco_solver->sol->y[310];
  CPG_Dual.d2[13] = qoco_solver->sol->y[311];
  CPG_Dual.d3[0] = qoco_solver->sol->y[312];
  CPG_Dual.d3[1] = qoco_solver->sol->y[313];
  CPG_Dual.d3[2] = qoco_solver->sol->y[314];
  CPG_Dual.d3[3] = qoco_solver->sol->y[315];
  CPG_Dual.d3[4] = qoco_solver->sol->y[316];
  CPG_Dual.d3[5] = qoco_solver->sol->y[317];
  CPG_Dual.d3[6] = qoco_solver->sol->y[318];
  CPG_Dual.d3[7] = qoco_solver->sol->y[319];
  CPG_Dual.d3[8] = qoco_solver->sol->y[320];
  CPG_Dual.d3[9] = qoco_solver->sol->y[321];
  CPG_Dual.d3[10] = qoco_solver->sol->y[322];
  CPG_Dual.d3[11] = qoco_solver->sol->y[323];
  CPG_Dual.d3[12] = qoco_solver->sol->y[324];
  CPG_Dual.d3[13] = qoco_solver->sol->y[325];
  CPG_Dual.d4[0] = qoco_solver->sol->y[326];
  CPG_Dual.d4[1] = qoco_solver->sol->y[327];
  CPG_Dual.d4[2] = qoco_solver->sol->y[328];
  CPG_Dual.d4[3] = qoco_solver->sol->y[329];
  CPG_Dual.d4[4] = qoco_solver->sol->y[330];
  CPG_Dual.d4[5] = qoco_solver->sol->y[331];
  CPG_Dual.d4[6] = qoco_solver->sol->y[332];
  CPG_Dual.d4[7] = qoco_solver->sol->y[333];
  CPG_Dual.d4[8] = qoco_solver->sol->y[334];
  CPG_Dual.d4[9] = qoco_solver->sol->y[335];
  CPG_Dual.d4[10] = qoco_solver->sol->y[336];
  CPG_Dual.d4[11] = qoco_solver->sol->y[337];
  CPG_Dual.d4[12] = qoco_solver->sol->y[338];
  CPG_Dual.d4[13] = qoco_solver->sol->y[339];
  CPG_Dual.d5[0] = qoco_solver->sol->y[340];
  CPG_Dual.d5[1] = qoco_solver->sol->y[341];
  CPG_Dual.d5[2] = qoco_solver->sol->y[342];
  CPG_Dual.d5[3] = qoco_solver->sol->y[343];
  CPG_Dual.d5[4] = qoco_solver->sol->y[344];
  CPG_Dual.d5[5] = qoco_solver->sol->y[345];
  CPG_Dual.d5[6] = qoco_solver->sol->y[346];
  CPG_Dual.d5[7] = qoco_solver->sol->y[347];
  CPG_Dual.d5[8] = qoco_solver->sol->y[348];
  CPG_Dual.d5[9] = qoco_solver->sol->y[349];
  CPG_Dual.d5[10] = qoco_solver->sol->y[350];
  CPG_Dual.d5[11] = qoco_solver->sol->y[351];
  CPG_Dual.d5[12] = qoco_solver->sol->y[352];
  CPG_Dual.d5[13] = qoco_solver->sol->y[353];
  CPG_Dual.d6[0] = qoco_solver->sol->y[354];
  CPG_Dual.d6[1] = qoco_solver->sol->y[355];
  CPG_Dual.d6[2] = qoco_solver->sol->y[356];
  CPG_Dual.d6[3] = qoco_solver->sol->y[357];
  CPG_Dual.d6[4] = qoco_solver->sol->y[358];
  CPG_Dual.d6[5] = qoco_solver->sol->y[359];
  CPG_Dual.d6[6] = qoco_solver->sol->y[360];
  CPG_Dual.d6[7] = qoco_solver->sol->y[361];
  CPG_Dual.d6[8] = qoco_solver->sol->y[362];
  CPG_Dual.d6[9] = qoco_solver->sol->y[363];
  CPG_Dual.d6[10] = qoco_solver->sol->y[364];
  CPG_Dual.d6[11] = qoco_solver->sol->y[365];
  CPG_Dual.d6[12] = qoco_solver->sol->y[366];
  CPG_Dual.d6[13] = qoco_solver->sol->y[367];
  CPG_Dual.d7[0] = qoco_solver->sol->y[368];
  CPG_Dual.d7[1] = qoco_solver->sol->y[369];
  CPG_Dual.d7[2] = qoco_solver->sol->y[370];
  CPG_Dual.d7[3] = qoco_solver->sol->y[371];
  CPG_Dual.d7[4] = qoco_solver->sol->y[372];
  CPG_Dual.d7[5] = qoco_solver->sol->y[373];
  CPG_Dual.d7[6] = qoco_solver->sol->y[374];
  CPG_Dual.d7[7] = qoco_solver->sol->y[375];
  CPG_Dual.d7[8] = qoco_solver->sol->y[376];
  CPG_Dual.d7[9] = qoco_solver->sol->y[377];
  CPG_Dual.d7[10] = qoco_solver->sol->y[378];
  CPG_Dual.d7[11] = qoco_solver->sol->y[379];
  CPG_Dual.d7[12] = qoco_solver->sol->y[380];
  CPG_Dual.d7[13] = qoco_solver->sol->y[381];
  CPG_Dual.d8[0] = qoco_solver->sol->y[382];
  CPG_Dual.d8[1] = qoco_solver->sol->y[383];
  CPG_Dual.d8[2] = qoco_solver->sol->y[384];
  CPG_Dual.d8[3] = qoco_solver->sol->y[385];
  CPG_Dual.d8[4] = qoco_solver->sol->y[386];
  CPG_Dual.d8[5] = qoco_solver->sol->y[387];
  CPG_Dual.d8[6] = qoco_solver->sol->y[388];
  CPG_Dual.d8[7] = qoco_solver->sol->y[389];
  CPG_Dual.d8[8] = qoco_solver->sol->y[390];
  CPG_Dual.d8[9] = qoco_solver->sol->y[391];
  CPG_Dual.d8[10] = qoco_solver->sol->y[392];
  CPG_Dual.d8[11] = qoco_solver->sol->y[393];
  CPG_Dual.d8[12] = qoco_solver->sol->y[394];
  CPG_Dual.d8[13] = qoco_solver->sol->y[395];
  CPG_Dual.d9[0] = qoco_solver->sol->y[396];
  CPG_Dual.d9[1] = qoco_solver->sol->y[397];
  CPG_Dual.d9[2] = qoco_solver->sol->y[398];
  CPG_Dual.d9[3] = qoco_solver->sol->y[399];
  CPG_Dual.d9[4] = qoco_solver->sol->y[400];
  CPG_Dual.d9[5] = qoco_solver->sol->y[401];
  CPG_Dual.d9[6] = qoco_solver->sol->y[402];
  CPG_Dual.d9[7] = qoco_solver->sol->y[403];
  CPG_Dual.d9[8] = qoco_solver->sol->y[404];
  CPG_Dual.d9[9] = qoco_solver->sol->y[405];
  CPG_Dual.d9[10] = qoco_solver->sol->y[406];
  CPG_Dual.d9[11] = qoco_solver->sol->y[407];
  CPG_Dual.d9[12] = qoco_solver->sol->y[408];
  CPG_Dual.d9[13] = qoco_solver->sol->y[409];
  CPG_Dual.d10[0] = qoco_solver->sol->y[410];
  CPG_Dual.d10[1] = qoco_solver->sol->y[411];
  CPG_Dual.d10[2] = qoco_solver->sol->y[412];
  CPG_Dual.d10[3] = qoco_solver->sol->y[413];
  CPG_Dual.d10[4] = qoco_solver->sol->y[414];
  CPG_Dual.d10[5] = qoco_solver->sol->y[415];
  CPG_Dual.d10[6] = qoco_solver->sol->y[416];
  CPG_Dual.d10[7] = qoco_solver->sol->y[417];
  CPG_Dual.d10[8] = qoco_solver->sol->y[418];
  CPG_Dual.d10[9] = qoco_solver->sol->y[419];
  CPG_Dual.d10[10] = qoco_solver->sol->y[420];
  CPG_Dual.d10[11] = qoco_solver->sol->y[421];
  CPG_Dual.d10[12] = qoco_solver->sol->y[422];
  CPG_Dual.d10[13] = qoco_solver->sol->y[423];
  CPG_Dual.d11[0] = qoco_solver->sol->y[424];
  CPG_Dual.d11[1] = qoco_solver->sol->y[425];
  CPG_Dual.d11[2] = qoco_solver->sol->y[426];
  CPG_Dual.d11[3] = qoco_solver->sol->y[427];
  CPG_Dual.d11[4] = qoco_solver->sol->y[428];
  CPG_Dual.d11[5] = qoco_solver->sol->y[429];
  CPG_Dual.d11[6] = qoco_solver->sol->y[430];
  CPG_Dual.d11[7] = qoco_solver->sol->y[431];
  CPG_Dual.d11[8] = qoco_solver->sol->y[432];
  CPG_Dual.d11[9] = qoco_solver->sol->y[433];
  CPG_Dual.d11[10] = qoco_solver->sol->y[434];
  CPG_Dual.d11[11] = qoco_solver->sol->y[435];
  CPG_Dual.d11[12] = qoco_solver->sol->y[436];
  CPG_Dual.d11[13] = qoco_solver->sol->y[437];
  CPG_Dual.d12[0] = qoco_solver->sol->y[438];
  CPG_Dual.d12[1] = qoco_solver->sol->y[439];
  CPG_Dual.d12[2] = qoco_solver->sol->y[440];
  CPG_Dual.d12[3] = qoco_solver->sol->y[441];
  CPG_Dual.d12[4] = qoco_solver->sol->y[442];
  CPG_Dual.d12[5] = qoco_solver->sol->y[443];
  CPG_Dual.d12[6] = qoco_solver->sol->y[444];
  CPG_Dual.d12[7] = qoco_solver->sol->y[445];
  CPG_Dual.d12[8] = qoco_solver->sol->y[446];
  CPG_Dual.d12[9] = qoco_solver->sol->y[447];
  CPG_Dual.d12[10] = qoco_solver->sol->y[448];
  CPG_Dual.d12[11] = qoco_solver->sol->y[449];
  CPG_Dual.d12[12] = qoco_solver->sol->y[450];
  CPG_Dual.d12[13] = qoco_solver->sol->y[451];
  CPG_Dual.d13[0] = qoco_solver->sol->y[452];
  CPG_Dual.d13[1] = qoco_solver->sol->y[453];
  CPG_Dual.d13[2] = qoco_solver->sol->y[454];
  CPG_Dual.d13[3] = qoco_solver->sol->y[455];
  CPG_Dual.d13[4] = qoco_solver->sol->y[456];
  CPG_Dual.d13[5] = qoco_solver->sol->y[457];
  CPG_Dual.d13[6] = qoco_solver->sol->y[458];
  CPG_Dual.d13[7] = qoco_solver->sol->y[459];
  CPG_Dual.d13[8] = qoco_solver->sol->y[460];
  CPG_Dual.d13[9] = qoco_solver->sol->y[461];
  CPG_Dual.d13[10] = qoco_solver->sol->y[462];
  CPG_Dual.d13[11] = qoco_solver->sol->y[463];
  CPG_Dual.d13[12] = qoco_solver->sol->y[464];
  CPG_Dual.d13[13] = qoco_solver->sol->y[465];
  CPG_Dual.d14[0] = qoco_solver->sol->z[478];
  CPG_Dual.d14[1] = qoco_solver->sol->z[479];
  CPG_Dual.d14[2] = qoco_solver->sol->z[480];
  CPG_Dual.d14[3] = qoco_solver->sol->z[481];
  CPG_Dual.d14[4] = qoco_solver->sol->z[482];
  CPG_Dual.d14[5] = qoco_solver->sol->z[483];
  CPG_Dual.d14[6] = qoco_solver->sol->z[484];
  CPG_Dual.d14[7] = qoco_solver->sol->z[485];
  CPG_Dual.d14[8] = qoco_solver->sol->z[486];
  CPG_Dual.d14[9] = qoco_solver->sol->z[487];
  CPG_Dual.d14[10] = qoco_solver->sol->z[488];
  CPG_Dual.d14[11] = qoco_solver->sol->z[489];
  CPG_Dual.d14[12] = qoco_solver->sol->z[490];
  CPG_Dual.d14[13] = qoco_solver->sol->z[491];
  CPG_Dual.d14[14] = qoco_solver->sol->z[492];
  CPG_Dual.d15[0] = qoco_solver->sol->z[493];
  CPG_Dual.d15[1] = qoco_solver->sol->z[494];
  CPG_Dual.d15[2] = qoco_solver->sol->z[495];
  CPG_Dual.d15[3] = qoco_solver->sol->z[496];
  CPG_Dual.d15[4] = qoco_solver->sol->z[497];
  CPG_Dual.d15[5] = qoco_solver->sol->z[498];
  CPG_Dual.d15[6] = qoco_solver->sol->z[499];
  CPG_Dual.d15[7] = qoco_solver->sol->z[500];
  CPG_Dual.d15[8] = qoco_solver->sol->z[501];
  CPG_Dual.d15[9] = qoco_solver->sol->z[502];
  CPG_Dual.d15[10] = qoco_solver->sol->z[503];
  CPG_Dual.d15[11] = qoco_solver->sol->z[504];
  CPG_Dual.d15[12] = qoco_solver->sol->z[505];
  CPG_Dual.d15[13] = qoco_solver->sol->z[506];
  CPG_Dual.d15[14] = qoco_solver->sol->z[507];
  CPG_Dual.d16[0] = qoco_solver->sol->z[508];
  CPG_Dual.d16[1] = qoco_solver->sol->z[509];
  CPG_Dual.d16[2] = qoco_solver->sol->z[510];
  CPG_Dual.d16[3] = qoco_solver->sol->z[511];
  CPG_Dual.d16[4] = qoco_solver->sol->z[512];
  CPG_Dual.d16[5] = qoco_solver->sol->z[513];
  CPG_Dual.d16[6] = qoco_solver->sol->z[514];
  CPG_Dual.d16[7] = qoco_solver->sol->z[515];
  CPG_Dual.d16[8] = qoco_solver->sol->z[516];
  CPG_Dual.d16[9] = qoco_solver->sol->z[517];
  CPG_Dual.d16[10] = qoco_solver->sol->z[518];
  CPG_Dual.d16[11] = qoco_solver->sol->z[519];
  CPG_Dual.d16[12] = qoco_solver->sol->z[520];
  CPG_Dual.d16[13] = qoco_solver->sol->z[521];
  CPG_Dual.d16[14] = qoco_solver->sol->z[522];
  CPG_Dual.d17[0] = qoco_solver->sol->z[523];
  CPG_Dual.d17[1] = qoco_solver->sol->z[524];
  CPG_Dual.d17[2] = qoco_solver->sol->z[525];
  CPG_Dual.d17[3] = qoco_solver->sol->z[526];
  CPG_Dual.d17[4] = qoco_solver->sol->z[527];
  CPG_Dual.d17[5] = qoco_solver->sol->z[528];
  CPG_Dual.d17[6] = qoco_solver->sol->z[529];
  CPG_Dual.d17[7] = qoco_solver->sol->z[530];
  CPG_Dual.d17[8] = qoco_solver->sol->z[531];
  CPG_Dual.d17[9] = qoco_solver->sol->z[532];
  CPG_Dual.d17[10] = qoco_solver->sol->z[533];
  CPG_Dual.d17[11] = qoco_solver->sol->z[534];
  CPG_Dual.d17[12] = qoco_solver->sol->z[535];
  CPG_Dual.d17[13] = qoco_solver->sol->z[536];
  CPG_Dual.d17[14] = qoco_solver->sol->z[537];
  CPG_Dual.d18[0] = qoco_solver->sol->z[568];
  CPG_Dual.d18[1] = qoco_solver->sol->z[569];
  CPG_Dual.d18[2] = qoco_solver->sol->z[570];
  CPG_Dual.d18[3] = qoco_solver->sol->z[571];
  CPG_Dual.d18[4] = qoco_solver->sol->z[572];
  CPG_Dual.d18[5] = qoco_solver->sol->z[573];
  CPG_Dual.d18[6] = qoco_solver->sol->z[574];
  CPG_Dual.d18[7] = qoco_solver->sol->z[575];
  CPG_Dual.d18[8] = qoco_solver->sol->z[576];
  CPG_Dual.d18[9] = qoco_solver->sol->z[577];
  CPG_Dual.d18[10] = qoco_solver->sol->z[578];
  CPG_Dual.d18[11] = qoco_solver->sol->z[579];
  CPG_Dual.d18[12] = qoco_solver->sol->z[580];
  CPG_Dual.d18[13] = qoco_solver->sol->z[581];
  CPG_Dual.d18[14] = qoco_solver->sol->z[582];
  CPG_Dual.d19 = qoco_solver->sol->z[673];
  CPG_Dual.d20[0] = qoco_solver->sol->z[700];
  CPG_Dual.d20[1] = qoco_solver->sol->z[701];
  CPG_Dual.d20[2] = qoco_solver->sol->z[702];
  CPG_Dual.d20[3] = qoco_solver->sol->z[703];
  CPG_Dual.d20[4] = qoco_solver->sol->z[704];
  CPG_Dual.d20[5] = qoco_solver->sol->z[705];
  CPG_Dual.d20[6] = qoco_solver->sol->z[706];
  CPG_Dual.d20[7] = qoco_solver->sol->z[707];
  CPG_Dual.d20[8] = qoco_solver->sol->z[708];
  CPG_Dual.d20[9] = qoco_solver->sol->z[709];
  CPG_Dual.d20[10] = qoco_solver->sol->z[710];
  CPG_Dual.d20[11] = qoco_solver->sol->z[711];
  CPG_Dual.d20[12] = qoco_solver->sol->z[712];
  CPG_Dual.d21[0] = qoco_solver->sol->y[466];
  CPG_Dual.d21[1] = qoco_solver->sol->y[467];
  CPG_Dual.d21[2] = qoco_solver->sol->y[468];
  CPG_Dual.d21[3] = qoco_solver->sol->y[469];
  CPG_Dual.d21[4] = qoco_solver->sol->y[470];
  CPG_Dual.d21[5] = qoco_solver->sol->y[471];
  CPG_Dual.d21[6] = qoco_solver->sol->y[472];
  CPG_Dual.d21[7] = qoco_solver->sol->y[473];
  CPG_Dual.d21[8] = qoco_solver->sol->y[474];
  CPG_Dual.d21[9] = qoco_solver->sol->y[475];
  CPG_Dual.d21[10] = qoco_solver->sol->y[476];
  CPG_Dual.d21[11] = qoco_solver->sol->y[477];
  CPG_Dual.d21[12] = qoco_solver->sol->y[478];
  CPG_Dual.d21[13] = qoco_solver->sol->y[479];
  CPG_Dual.d21[14] = qoco_solver->sol->y[480];
  CPG_Dual.d21[15] = qoco_solver->sol->y[481];
  CPG_Dual.d21[16] = qoco_solver->sol->y[482];
  CPG_Dual.d21[17] = qoco_solver->sol->y[483];
  CPG_Dual.d21[18] = qoco_solver->sol->y[484];
  CPG_Dual.d21[19] = qoco_solver->sol->y[485];
  CPG_Dual.d21[20] = qoco_solver->sol->y[486];
  CPG_Dual.d21[21] = qoco_solver->sol->y[487];
  CPG_Dual.d21[22] = qoco_solver->sol->y[488];
  CPG_Dual.d21[23] = qoco_solver->sol->y[489];
  CPG_Dual.d21[24] = qoco_solver->sol->y[490];
  CPG_Dual.d21[25] = qoco_solver->sol->y[491];
  CPG_Dual.d21[26] = qoco_solver->sol->y[492];
  CPG_Dual.d21[27] = qoco_solver->sol->y[493];
  CPG_Dual.d21[28] = qoco_solver->sol->y[494];
  CPG_Dual.d21[29] = qoco_solver->sol->y[495];
  CPG_Dual.d21[30] = qoco_solver->sol->y[496];
  CPG_Dual.d21[31] = qoco_solver->sol->y[497];
  CPG_Dual.d21[32] = qoco_solver->sol->y[498];
  CPG_Dual.d21[33] = qoco_solver->sol->y[499];
  CPG_Dual.d21[34] = qoco_solver->sol->y[500];
  CPG_Dual.d21[35] = qoco_solver->sol->y[501];
  CPG_Dual.d21[36] = qoco_solver->sol->y[502];
  CPG_Dual.d21[37] = qoco_solver->sol->y[503];
  CPG_Dual.d21[38] = qoco_solver->sol->y[504];
  CPG_Dual.d21[39] = qoco_solver->sol->y[505];
  CPG_Dual.d21[40] = qoco_solver->sol->y[506];
  CPG_Dual.d21[41] = qoco_solver->sol->y[507];
  CPG_Dual.d21[42] = qoco_solver->sol->y[508];
  CPG_Dual.d21[43] = qoco_solver->sol->y[509];
  CPG_Dual.d21[44] = qoco_solver->sol->y[510];
  CPG_Dual.d21[45] = qoco_solver->sol->y[511];
  CPG_Dual.d21[46] = qoco_solver->sol->y[512];
  CPG_Dual.d21[47] = qoco_solver->sol->y[513];
  CPG_Dual.d21[48] = qoco_solver->sol->y[514];
  CPG_Dual.d21[49] = qoco_solver->sol->y[515];
  CPG_Dual.d21[50] = qoco_solver->sol->y[516];
  CPG_Dual.d21[51] = qoco_solver->sol->y[517];
  CPG_Dual.d21[52] = qoco_solver->sol->y[518];
  CPG_Dual.d21[53] = qoco_solver->sol->y[519];
  CPG_Dual.d21[54] = qoco_solver->sol->y[520];
  CPG_Dual.d21[55] = qoco_solver->sol->y[521];
  CPG_Dual.d21[56] = qoco_solver->sol->y[522];
  CPG_Dual.d21[57] = qoco_solver->sol->y[523];
  CPG_Dual.d21[58] = qoco_solver->sol->y[524];
  CPG_Dual.d21[59] = qoco_solver->sol->y[525];
  CPG_Dual.d21[60] = qoco_solver->sol->y[526];
  CPG_Dual.d21[61] = qoco_solver->sol->y[527];
  CPG_Dual.d21[62] = qoco_solver->sol->y[528];
  CPG_Dual.d21[63] = qoco_solver->sol->y[529];
  CPG_Dual.d21[64] = qoco_solver->sol->y[530];
  CPG_Dual.d21[65] = qoco_solver->sol->y[531];
  CPG_Dual.d21[66] = qoco_solver->sol->y[532];
  CPG_Dual.d21[67] = qoco_solver->sol->y[533];
  CPG_Dual.d21[68] = qoco_solver->sol->y[534];
  CPG_Dual.d21[69] = qoco_solver->sol->y[535];
  CPG_Dual.d21[70] = qoco_solver->sol->y[536];
  CPG_Dual.d21[71] = qoco_solver->sol->y[537];
  CPG_Dual.d21[72] = qoco_solver->sol->y[538];
  CPG_Dual.d21[73] = qoco_solver->sol->y[539];
  CPG_Dual.d21[74] = qoco_solver->sol->y[540];
  CPG_Dual.d21[75] = qoco_solver->sol->y[541];
  CPG_Dual.d21[76] = qoco_solver->sol->y[542];
  CPG_Dual.d21[77] = qoco_solver->sol->y[543];
  CPG_Dual.d21[78] = qoco_solver->sol->y[544];
  CPG_Dual.d21[79] = qoco_solver->sol->y[545];
  CPG_Dual.d21[80] = qoco_solver->sol->y[546];
  CPG_Dual.d21[81] = qoco_solver->sol->y[547];
  CPG_Dual.d21[82] = qoco_solver->sol->y[548];
  CPG_Dual.d21[83] = qoco_solver->sol->y[549];
  CPG_Dual.d21[84] = qoco_solver->sol->y[550];
  CPG_Dual.d21[85] = qoco_solver->sol->y[551];
  CPG_Dual.d21[86] = qoco_solver->sol->y[552];
  CPG_Dual.d21[87] = qoco_solver->sol->y[553];
  CPG_Dual.d21[88] = qoco_solver->sol->y[554];
  CPG_Dual.d21[89] = qoco_solver->sol->y[555];
  CPG_Dual.d21[90] = qoco_solver->sol->y[556];
  CPG_Dual.d21[91] = qoco_solver->sol->y[557];
  CPG_Dual.d21[92] = qoco_solver->sol->y[558];
  CPG_Dual.d21[93] = qoco_solver->sol->y[559];
  CPG_Dual.d21[94] = qoco_solver->sol->y[560];
  CPG_Dual.d21[95] = qoco_solver->sol->y[561];
  CPG_Dual.d21[96] = qoco_solver->sol->y[562];
  CPG_Dual.d21[97] = qoco_solver->sol->y[563];
  CPG_Dual.d21[98] = qoco_solver->sol->y[564];
  CPG_Dual.d21[99] = qoco_solver->sol->y[565];
  CPG_Dual.d21[100] = qoco_solver->sol->y[566];
  CPG_Dual.d21[101] = qoco_solver->sol->y[567];
  CPG_Dual.d21[102] = qoco_solver->sol->y[568];
  CPG_Dual.d21[103] = qoco_solver->sol->y[569];
  CPG_Dual.d21[104] = qoco_solver->sol->y[570];
  CPG_Dual.d21[105] = qoco_solver->sol->y[571];
  CPG_Dual.d21[106] = qoco_solver->sol->y[572];
  CPG_Dual.d21[107] = qoco_solver->sol->y[573];
  CPG_Dual.d21[108] = qoco_solver->sol->y[574];
  CPG_Dual.d21[109] = qoco_solver->sol->y[575];
  CPG_Dual.d21[110] = qoco_solver->sol->y[576];
  CPG_Dual.d21[111] = qoco_solver->sol->y[577];
  CPG_Dual.d21[112] = qoco_solver->sol->y[578];
  CPG_Dual.d21[113] = qoco_solver->sol->y[579];
  CPG_Dual.d21[114] = qoco_solver->sol->y[580];
  CPG_Dual.d21[115] = qoco_solver->sol->y[581];
  CPG_Dual.d21[116] = qoco_solver->sol->y[582];
  CPG_Dual.d21[117] = qoco_solver->sol->y[583];
  CPG_Dual.d21[118] = qoco_solver->sol->y[584];
  CPG_Dual.d21[119] = qoco_solver->sol->y[585];
  CPG_Dual.d21[120] = qoco_solver->sol->y[586];
  CPG_Dual.d21[121] = qoco_solver->sol->y[587];
  CPG_Dual.d21[122] = qoco_solver->sol->y[588];
  CPG_Dual.d21[123] = qoco_solver->sol->y[589];
  CPG_Dual.d21[124] = qoco_solver->sol->y[590];
  CPG_Dual.d21[125] = qoco_solver->sol->y[591];
  CPG_Dual.d21[126] = qoco_solver->sol->y[592];
  CPG_Dual.d21[127] = qoco_solver->sol->y[593];
  CPG_Dual.d21[128] = qoco_solver->sol->y[594];
  CPG_Dual.d21[129] = qoco_solver->sol->y[595];
  CPG_Dual.d21[130] = qoco_solver->sol->y[596];
  CPG_Dual.d21[131] = qoco_solver->sol->y[597];
  CPG_Dual.d21[132] = qoco_solver->sol->y[598];
  CPG_Dual.d21[133] = qoco_solver->sol->y[599];
  CPG_Dual.d21[134] = qoco_solver->sol->y[600];
  CPG_Dual.d21[135] = qoco_solver->sol->y[601];
  CPG_Dual.d21[136] = qoco_solver->sol->y[602];
  CPG_Dual.d21[137] = qoco_solver->sol->y[603];
  CPG_Dual.d21[138] = qoco_solver->sol->y[604];
  CPG_Dual.d21[139] = qoco_solver->sol->y[605];
  CPG_Dual.d21[140] = qoco_solver->sol->y[606];
  CPG_Dual.d21[141] = qoco_solver->sol->y[607];
  CPG_Dual.d21[142] = qoco_solver->sol->y[608];
  CPG_Dual.d21[143] = qoco_solver->sol->y[609];
  CPG_Dual.d21[144] = qoco_solver->sol->y[610];
  CPG_Dual.d21[145] = qoco_solver->sol->y[611];
  CPG_Dual.d21[146] = qoco_solver->sol->y[612];
  CPG_Dual.d21[147] = qoco_solver->sol->y[613];
  CPG_Dual.d21[148] = qoco_solver->sol->y[614];
  CPG_Dual.d21[149] = qoco_solver->sol->y[615];
  CPG_Dual.d21[150] = qoco_solver->sol->y[616];
  CPG_Dual.d21[151] = qoco_solver->sol->y[617];
  CPG_Dual.d21[152] = qoco_solver->sol->y[618];
  CPG_Dual.d21[153] = qoco_solver->sol->y[619];
  CPG_Dual.d21[154] = qoco_solver->sol->y[620];
  CPG_Dual.d21[155] = qoco_solver->sol->y[621];
  CPG_Dual.d21[156] = qoco_solver->sol->y[622];
  CPG_Dual.d21[157] = qoco_solver->sol->y[623];
  CPG_Dual.d21[158] = qoco_solver->sol->y[624];
  CPG_Dual.d21[159] = qoco_solver->sol->y[625];
  CPG_Dual.d21[160] = qoco_solver->sol->y[626];
  CPG_Dual.d21[161] = qoco_solver->sol->y[627];
  CPG_Dual.d21[162] = qoco_solver->sol->y[628];
  CPG_Dual.d21[163] = qoco_solver->sol->y[629];
  CPG_Dual.d21[164] = qoco_solver->sol->y[630];
  CPG_Dual.d21[165] = qoco_solver->sol->y[631];
  CPG_Dual.d21[166] = qoco_solver->sol->y[632];
  CPG_Dual.d21[167] = qoco_solver->sol->y[633];
  CPG_Dual.d21[168] = qoco_solver->sol->y[634];
  CPG_Dual.d21[169] = qoco_solver->sol->y[635];
  CPG_Dual.d21[170] = qoco_solver->sol->y[636];
  CPG_Dual.d21[171] = qoco_solver->sol->y[637];
  CPG_Dual.d21[172] = qoco_solver->sol->y[638];
  CPG_Dual.d21[173] = qoco_solver->sol->y[639];
  CPG_Dual.d21[174] = qoco_solver->sol->y[640];
  CPG_Dual.d21[175] = qoco_solver->sol->y[641];
  CPG_Dual.d21[176] = qoco_solver->sol->y[642];
  CPG_Dual.d21[177] = qoco_solver->sol->y[643];
  CPG_Dual.d21[178] = qoco_solver->sol->y[644];
  CPG_Dual.d21[179] = qoco_solver->sol->y[645];
  CPG_Dual.d21[180] = qoco_solver->sol->y[646];
  CPG_Dual.d21[181] = qoco_solver->sol->y[647];
  CPG_Dual.d21[182] = qoco_solver->sol->y[648];
  CPG_Dual.d21[183] = qoco_solver->sol->y[649];
  CPG_Dual.d21[184] = qoco_solver->sol->y[650];
  CPG_Dual.d21[185] = qoco_solver->sol->y[651];
  CPG_Dual.d21[186] = qoco_solver->sol->y[652];
  CPG_Dual.d21[187] = qoco_solver->sol->y[653];
  CPG_Dual.d21[188] = qoco_solver->sol->y[654];
  CPG_Dual.d21[189] = qoco_solver->sol->y[655];
  CPG_Dual.d21[190] = qoco_solver->sol->y[656];
  CPG_Dual.d21[191] = qoco_solver->sol->y[657];
  CPG_Dual.d21[192] = qoco_solver->sol->y[658];
  CPG_Dual.d21[193] = qoco_solver->sol->y[659];
  CPG_Dual.d21[194] = qoco_solver->sol->y[660];
  CPG_Dual.d21[195] = qoco_solver->sol->y[661];
  CPG_Dual.d22[0] = qoco_solver->sol->y[662];
  CPG_Dual.d22[1] = qoco_solver->sol->y[663];
  CPG_Dual.d22[2] = qoco_solver->sol->y[664];
  CPG_Dual.d22[3] = qoco_solver->sol->y[665];
  CPG_Dual.d22[4] = qoco_solver->sol->y[666];
  CPG_Dual.d22[5] = qoco_solver->sol->y[667];
  CPG_Dual.d22[6] = qoco_solver->sol->y[668];
  CPG_Dual.d22[7] = qoco_solver->sol->y[669];
  CPG_Dual.d22[8] = qoco_solver->sol->y[670];
  CPG_Dual.d22[9] = qoco_solver->sol->y[671];
  CPG_Dual.d22[10] = qoco_solver->sol->y[672];
  CPG_Dual.d22[11] = qoco_solver->sol->y[673];
  CPG_Dual.d22[12] = qoco_solver->sol->y[674];
  CPG_Dual.d22[13] = qoco_solver->sol->y[675];
  CPG_Dual.d22[14] = qoco_solver->sol->y[676];
  CPG_Dual.d22[15] = qoco_solver->sol->y[677];
  CPG_Dual.d22[16] = qoco_solver->sol->y[678];
  CPG_Dual.d22[17] = qoco_solver->sol->y[679];
  CPG_Dual.d22[18] = qoco_solver->sol->y[680];
  CPG_Dual.d22[19] = qoco_solver->sol->y[681];
  CPG_Dual.d22[20] = qoco_solver->sol->y[682];
  CPG_Dual.d22[21] = qoco_solver->sol->y[683];
  CPG_Dual.d22[22] = qoco_solver->sol->y[684];
  CPG_Dual.d22[23] = qoco_solver->sol->y[685];
  CPG_Dual.d22[24] = qoco_solver->sol->y[686];
  CPG_Dual.d22[25] = qoco_solver->sol->y[687];
  CPG_Dual.d22[26] = qoco_solver->sol->y[688];
  CPG_Dual.d22[27] = qoco_solver->sol->y[689];
  CPG_Dual.d22[28] = qoco_solver->sol->y[690];
  CPG_Dual.d22[29] = qoco_solver->sol->y[691];
  CPG_Dual.d22[30] = qoco_solver->sol->y[692];
  CPG_Dual.d22[31] = qoco_solver->sol->y[693];
  CPG_Dual.d22[32] = qoco_solver->sol->y[694];
  CPG_Dual.d22[33] = qoco_solver->sol->y[695];
  CPG_Dual.d22[34] = qoco_solver->sol->y[696];
  CPG_Dual.d22[35] = qoco_solver->sol->y[697];
  CPG_Dual.d22[36] = qoco_solver->sol->y[698];
  CPG_Dual.d22[37] = qoco_solver->sol->y[699];
  CPG_Dual.d22[38] = qoco_solver->sol->y[700];
  CPG_Dual.d22[39] = qoco_solver->sol->y[701];
  CPG_Dual.d22[40] = qoco_solver->sol->y[702];
  CPG_Dual.d22[41] = qoco_solver->sol->y[703];
  CPG_Dual.d22[42] = qoco_solver->sol->y[704];
  CPG_Dual.d22[43] = qoco_solver->sol->y[705];
  CPG_Dual.d22[44] = qoco_solver->sol->y[706];
  CPG_Dual.d22[45] = qoco_solver->sol->y[707];
  CPG_Dual.d22[46] = qoco_solver->sol->y[708];
  CPG_Dual.d22[47] = qoco_solver->sol->y[709];
  CPG_Dual.d22[48] = qoco_solver->sol->y[710];
  CPG_Dual.d22[49] = qoco_solver->sol->y[711];
  CPG_Dual.d22[50] = qoco_solver->sol->y[712];
  CPG_Dual.d22[51] = qoco_solver->sol->y[713];
  CPG_Dual.d22[52] = qoco_solver->sol->y[714];
  CPG_Dual.d22[53] = qoco_solver->sol->y[715];
  CPG_Dual.d22[54] = qoco_solver->sol->y[716];
  CPG_Dual.d22[55] = qoco_solver->sol->y[717];
  CPG_Dual.d22[56] = qoco_solver->sol->y[718];
  CPG_Dual.d22[57] = qoco_solver->sol->y[719];
  CPG_Dual.d22[58] = qoco_solver->sol->y[720];
  CPG_Dual.d22[59] = qoco_solver->sol->y[721];
  CPG_Dual.d22[60] = qoco_solver->sol->y[722];
  CPG_Dual.d22[61] = qoco_solver->sol->y[723];
  CPG_Dual.d22[62] = qoco_solver->sol->y[724];
  CPG_Dual.d22[63] = qoco_solver->sol->y[725];
  CPG_Dual.d22[64] = qoco_solver->sol->y[726];
  CPG_Dual.d22[65] = qoco_solver->sol->y[727];
  CPG_Dual.d22[66] = qoco_solver->sol->y[728];
  CPG_Dual.d22[67] = qoco_solver->sol->y[729];
  CPG_Dual.d22[68] = qoco_solver->sol->y[730];
  CPG_Dual.d22[69] = qoco_solver->sol->y[731];
  CPG_Dual.d22[70] = qoco_solver->sol->y[732];
  CPG_Dual.d22[71] = qoco_solver->sol->y[733];
  CPG_Dual.d22[72] = qoco_solver->sol->y[734];
  CPG_Dual.d22[73] = qoco_solver->sol->y[735];
  CPG_Dual.d22[74] = qoco_solver->sol->y[736];
  CPG_Dual.d22[75] = qoco_solver->sol->y[737];
  CPG_Dual.d22[76] = qoco_solver->sol->y[738];
  CPG_Dual.d22[77] = qoco_solver->sol->y[739];
  CPG_Dual.d22[78] = qoco_solver->sol->y[740];
  CPG_Dual.d22[79] = qoco_solver->sol->y[741];
  CPG_Dual.d22[80] = qoco_solver->sol->y[742];
  CPG_Dual.d22[81] = qoco_solver->sol->y[743];
  CPG_Dual.d22[82] = qoco_solver->sol->y[744];
  CPG_Dual.d22[83] = qoco_solver->sol->y[745];
  CPG_Dual.d22[84] = qoco_solver->sol->y[746];
  CPG_Dual.d22[85] = qoco_solver->sol->y[747];
  CPG_Dual.d22[86] = qoco_solver->sol->y[748];
  CPG_Dual.d22[87] = qoco_solver->sol->y[749];
  CPG_Dual.d22[88] = qoco_solver->sol->y[750];
  CPG_Dual.d22[89] = qoco_solver->sol->y[751];
  CPG_Dual.d22[90] = qoco_solver->sol->y[752];
  CPG_Dual.d22[91] = qoco_solver->sol->y[753];
  CPG_Dual.d22[92] = qoco_solver->sol->y[754];
  CPG_Dual.d22[93] = qoco_solver->sol->y[755];
  CPG_Dual.d22[94] = qoco_solver->sol->y[756];
  CPG_Dual.d22[95] = qoco_solver->sol->y[757];
  CPG_Dual.d22[96] = qoco_solver->sol->y[758];
  CPG_Dual.d22[97] = qoco_solver->sol->y[759];
  CPG_Dual.d22[98] = qoco_solver->sol->y[760];
  CPG_Dual.d22[99] = qoco_solver->sol->y[761];
  CPG_Dual.d22[100] = qoco_solver->sol->y[762];
  CPG_Dual.d22[101] = qoco_solver->sol->y[763];
  CPG_Dual.d22[102] = qoco_solver->sol->y[764];
  CPG_Dual.d22[103] = qoco_solver->sol->y[765];
  CPG_Dual.d22[104] = qoco_solver->sol->y[766];
  CPG_Dual.d22[105] = qoco_solver->sol->y[767];
  CPG_Dual.d22[106] = qoco_solver->sol->y[768];
  CPG_Dual.d22[107] = qoco_solver->sol->y[769];
  CPG_Dual.d22[108] = qoco_solver->sol->y[770];
  CPG_Dual.d22[109] = qoco_solver->sol->y[771];
  CPG_Dual.d22[110] = qoco_solver->sol->y[772];
  CPG_Dual.d22[111] = qoco_solver->sol->y[773];
  CPG_Dual.d22[112] = qoco_solver->sol->y[774];
  CPG_Dual.d22[113] = qoco_solver->sol->y[775];
  CPG_Dual.d22[114] = qoco_solver->sol->y[776];
  CPG_Dual.d22[115] = qoco_solver->sol->y[777];
  CPG_Dual.d22[116] = qoco_solver->sol->y[778];
  CPG_Dual.d22[117] = qoco_solver->sol->y[779];
  CPG_Dual.d22[118] = qoco_solver->sol->y[780];
  CPG_Dual.d22[119] = qoco_solver->sol->y[781];
  CPG_Dual.d22[120] = qoco_solver->sol->y[782];
  CPG_Dual.d22[121] = qoco_solver->sol->y[783];
  CPG_Dual.d22[122] = qoco_solver->sol->y[784];
  CPG_Dual.d22[123] = qoco_solver->sol->y[785];
  CPG_Dual.d22[124] = qoco_solver->sol->y[786];
  CPG_Dual.d22[125] = qoco_solver->sol->y[787];
  CPG_Dual.d22[126] = qoco_solver->sol->y[788];
  CPG_Dual.d22[127] = qoco_solver->sol->y[789];
  CPG_Dual.d22[128] = qoco_solver->sol->y[790];
  CPG_Dual.d22[129] = qoco_solver->sol->y[791];
  CPG_Dual.d22[130] = qoco_solver->sol->y[792];
  CPG_Dual.d22[131] = qoco_solver->sol->y[793];
  CPG_Dual.d22[132] = qoco_solver->sol->y[794];
  CPG_Dual.d22[133] = qoco_solver->sol->y[795];
  CPG_Dual.d22[134] = qoco_solver->sol->y[796];
  CPG_Dual.d22[135] = qoco_solver->sol->y[797];
  CPG_Dual.d22[136] = qoco_solver->sol->y[798];
  CPG_Dual.d22[137] = qoco_solver->sol->y[799];
  CPG_Dual.d22[138] = qoco_solver->sol->y[800];
  CPG_Dual.d22[139] = qoco_solver->sol->y[801];
  CPG_Dual.d22[140] = qoco_solver->sol->y[802];
  CPG_Dual.d22[141] = qoco_solver->sol->y[803];
  CPG_Dual.d22[142] = qoco_solver->sol->y[804];
  CPG_Dual.d22[143] = qoco_solver->sol->y[805];
  CPG_Dual.d22[144] = qoco_solver->sol->y[806];
  CPG_Dual.d22[145] = qoco_solver->sol->y[807];
  CPG_Dual.d22[146] = qoco_solver->sol->y[808];
  CPG_Dual.d22[147] = qoco_solver->sol->y[809];
  CPG_Dual.d22[148] = qoco_solver->sol->y[810];
  CPG_Dual.d22[149] = qoco_solver->sol->y[811];
  CPG_Dual.d22[150] = qoco_solver->sol->y[812];
  CPG_Dual.d22[151] = qoco_solver->sol->y[813];
  CPG_Dual.d22[152] = qoco_solver->sol->y[814];
  CPG_Dual.d22[153] = qoco_solver->sol->y[815];
  CPG_Dual.d22[154] = qoco_solver->sol->y[816];
  CPG_Dual.d22[155] = qoco_solver->sol->y[817];
  CPG_Dual.d22[156] = qoco_solver->sol->y[818];
  CPG_Dual.d22[157] = qoco_solver->sol->y[819];
  CPG_Dual.d22[158] = qoco_solver->sol->y[820];
  CPG_Dual.d22[159] = qoco_solver->sol->y[821];
  CPG_Dual.d22[160] = qoco_solver->sol->y[822];
  CPG_Dual.d22[161] = qoco_solver->sol->y[823];
  CPG_Dual.d22[162] = qoco_solver->sol->y[824];
  CPG_Dual.d22[163] = qoco_solver->sol->y[825];
  CPG_Dual.d22[164] = qoco_solver->sol->y[826];
  CPG_Dual.d22[165] = qoco_solver->sol->y[827];
  CPG_Dual.d22[166] = qoco_solver->sol->y[828];
  CPG_Dual.d22[167] = qoco_solver->sol->y[829];
  CPG_Dual.d22[168] = qoco_solver->sol->y[830];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_solver->sol->obj + Canon_Params.d);
  CPG_Info.iter = qoco_solver->sol->iters;
  CPG_Info.status = qoco_solver->sol->status;
  CPG_Info.pri_res = qoco_solver->sol->pres;
  CPG_Info.dua_res = qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_P(){
  for (i=0; i<270; i++){
    Canon_Params_conditioning.P->x[i] = Canon_Params.P->x[i];
  }
}

void cpg_copy_c(){
  for (i=0; i<1062; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<5974; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<831; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<1504; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<818; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_P();
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (!qoco_solver ) {
    cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   qoco_set_csc(P, 1062, 1062, Canon_Params.P->nnz, Canon_Params.P->x, Canon_Params.P->p, Canon_Params.P->i);
   qoco_set_csc(A, 831, 1062, Canon_Params.A->nnz, Canon_Params.A->x, Canon_Params.A->p, Canon_Params.A->i);
   qoco_set_csc(G, 818, 1062, Canon_Params.G->nnz, Canon_Params.G->x, Canon_Params.G->p, Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(qoco_solver, 1062, 818, 831, P, Canon_Params.c, A, Canon_Params.b, G, Canon_Params.h, 713, 30, (int *) &qoco_q, qoco_settings);
  }
  if (Canon_Outdated.A) {
    update_matrix_data(qoco_solver, NULL, Canon_Params.A->x, NULL);
  }
  if (Canon_Outdated.b) {
    update_vector_data(qoco_solver, NULL, Canon_Params.b, NULL);
  }
  qoco_solver->settings->max_iters = Canon_Settings.max_iters;
  qoco_solver->settings->bisect_iters = Canon_Settings.bisect_iters;
  qoco_solver->settings->ruiz_iters = Canon_Settings.ruiz_iters;
  qoco_solver->settings->iter_ref_iters = Canon_Settings.iter_ref_iters;
  qoco_solver->settings->kkt_static_reg = Canon_Settings.kkt_static_reg;
  qoco_solver->settings->kkt_dynamic_reg = Canon_Settings.kkt_dynamic_reg;
  qoco_solver->settings->abstol = Canon_Settings.abstol;
  qoco_solver->settings->reltol = Canon_Settings.reltol;
  qoco_solver->settings->abstol_inacc = Canon_Settings.abstol_inacc;
  qoco_solver->settings->reltol_inacc = Canon_Settings.reltol_inacc;
  qoco_solver->settings->verbose = Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(qoco_solver);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.max_iters = 200;
  Canon_Settings.bisect_iters = 5;
  Canon_Settings.ruiz_iters = 0;
  Canon_Settings.iter_ref_iters = 1;
  Canon_Settings.kkt_static_reg = 1e-8;
  Canon_Settings.kkt_dynamic_reg = 1e-8;
  Canon_Settings.abstol = 1e-7;
  Canon_Settings.reltol = 1e-7;
  Canon_Settings.abstol_inacc = 1e-5;
  Canon_Settings.reltol_inacc = 1e-5;
  Canon_Settings.verbose = 0;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  Canon_Settings.bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}
