
/*
Auto-generated by CVXPYgen on June 13, 2025 at 10:35:46.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Ak_0(0, 1.00000000000000000000);
  cpg_update_Bk_minus_0(0, -1.04203125768504234472);
  cpg_update_Bk_plus_0(0, -0.52142536835102704096);
  cpg_update_ck(0, 0.15576040630384122010);
  cpg_update_Ak_1(0, 1.00000000000000000000);
  cpg_update_Bk_minus_1(0, -1.04643340035365950413);
  cpg_update_Bk_plus_1(0, -0.52457688781250388921);
  cpg_update_Ak_2(0, 1.00000000000000000000);
  cpg_update_Bk_minus_2(0, -1.06334396605838565897);
  cpg_update_Bk_plus_2(0, -0.53471804611815132446);
  cpg_update_Ak_3(0, 1.00000000000000000000);
  cpg_update_Bk_minus_3(0, -1.08988093508226824291);
  cpg_update_Bk_plus_3(0, -0.54910826737803042352);
  cpg_update_Ak_4(0, 1.00000000000000000000);
  cpg_update_Bk_minus_4(0, -1.12663266161632558138);
  cpg_update_Bk_plus_4(0, -0.56946097235406611947);
  cpg_update_Ak_5(0, 1.00000000000000000000);
  cpg_update_Bk_minus_5(0, -1.18167895138918055409);
  cpg_update_Bk_plus_5(0, -0.60132522278501110424);
  cpg_update_Ak_6(0, 1.00000000000000000000);
  cpg_update_Bk_minus_6(0, -1.26705406759832328589);
  cpg_update_Bk_plus_6(0, -0.64224051202493925850);
  cpg_update_Ak_7(0, 1.00000000000000000000);
  cpg_update_Bk_minus_7(0, -1.42189502615755047898);
  cpg_update_Bk_plus_7(0, -0.70589524530102532029);
  cpg_update_Ak_8(0, 1.00000000000000000000);
  cpg_update_Bk_minus_8(0, -1.17025576073513604136);
  cpg_update_Bk_plus_8(0, -0.50266154383964223307);
  cpg_update_Ak_9(0, 1.00000000000000000000);
  cpg_update_Bk_minus_9(0, -0.08862658898713039746);
  cpg_update_Bk_plus_9(0, 0.11072956614118899255);
  cpg_update_Ak_10(0, 1.00000000000000000000);
  cpg_update_Bk_minus_10(0, 1.03445149680526227165);
  cpg_update_Bk_plus_10(0, 0.59638367837131711635);
  cpg_update_Ak_11(0, 1.00000000000000000000);
  cpg_update_Bk_minus_11(0, 1.39296690836728265239);
  cpg_update_Bk_plus_11(0, 0.68799920623779309281);
  cpg_update_Ak_12(0, 1.00000000000000000000);
  cpg_update_Bk_minus_12(0, 1.03530160868427123511);
  cpg_update_Bk_plus_12(0, 0.44296609575056089536);
  cpg_update_Ak_13(0, 1.00000000000000000000);
  cpg_update_Bk_minus_13(0, 0.27999170189471700443);
  cpg_update_Bk_plus_13(0, 0.08631037606938755935);
  cpg_update_x_0(0, 0.00000000000000000000);
  cpg_update_x_ref(0, 0.00000000000000000000);
  cpg_update_u_ref(0, 0.02943001070499082911);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<45; i++) {
    printf("U[%d] = %f\n", i, CPG_Result.prim->U[i]);
  }
  for(i=0; i<2; i++) {
    printf("var1376[%d] = %f\n", i, CPG_Result.prim->var1376[i]);
  }
  for(i=0; i<98; i++) {
    printf("V[%d] = %f\n", i, CPG_Result.prim->V[i]);
  }
  for(i=0; i<7; i++) {
    printf("v_0[%d] = %f\n", i, CPG_Result.prim->v_0[i]);
  }
  for(i=0; i<6; i++) {
    printf("v_N[%d] = %f\n", i, CPG_Result.prim->v_N[i]);
  }
  for(i=0; i<15; i++) {
    printf("eta[%d] = %f\n", i, CPG_Result.prim->eta[i]);
  }
  for(i=0; i<105; i++) {
    printf("X[%d] = %f\n", i, CPG_Result.prim->X[i]);
  }

  // Print dual solution
  for(i=0; i<7; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<7; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<7; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<7; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<7; i++) {
    printf("d4[%d] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<7; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<7; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<7; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<7; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<7; i++) {
    printf("d9[%d] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<7; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<7; i++) {
    printf("d11[%d] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<7; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  for(i=0; i<7; i++) {
    printf("d13[%d] = %f\n", i, CPG_Result.dual->d13[i]);
  }
  for(i=0; i<15; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  for(i=0; i<15; i++) {
    printf("d15[%d] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<15; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  for(i=0; i<15; i++) {
    printf("d17[%d] = %f\n", i, CPG_Result.dual->d17[i]);
  }
  for(i=0; i<15; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  for(i=0; i<15; i++) {
    printf("d19[%d] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<15; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  for(i=0; i<2; i++) {
    printf("d21[%d] = %f\n", i, CPG_Result.dual->d21[i]);
  }
  for(i=0; i<49; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  for(i=0; i<4; i++) {
    printf("d23[%d] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<4; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  printf("d25 = %f\n", CPG_Result.dual->d25);
  printf("d26 = %f\n", CPG_Result.dual->d26);
  for(i=0; i<15; i++) {
    printf("d27[%d] = %f\n", i, CPG_Result.dual->d27[i]);
  }

  return 0;

}
