
/*
Auto-generated by CVXPYgen on June 13, 2025 at 10:35:46.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_Ak_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+49] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+70] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_ck(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+91] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_Ak_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+189] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+238] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_1(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+259] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+280] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+329] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_2(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+350] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+371] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+420] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+441] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+462] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+511] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+532] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+553] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+602] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_5(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+623] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+644] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+693] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_6(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+714] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+735] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+784] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_7(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+805] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+826] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+875] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_8(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+896] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+917] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+966] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_9(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+987] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1008] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1057] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_10(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1078] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1099] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1148] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_11(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1169] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1190] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1239] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_12(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1260] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Ak_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1281] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_minus_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1330] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Bk_plus_13(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1351] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_x_0(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1372] = val;
  Canon_Outdated.b = 1;
}

void cpg_update_x_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1379] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_u_ref(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1484] = val;
  Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<1490; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_b(){
  for(i=0; i<157; i++){
    Canon_Params.b[i] = 0;
    for(j=canon_b_map.p[i]; j<canon_b_map.p[i+1]; j++){
      Canon_Params.b[i] += canon_b_map.x[j]*cpg_params_vec[canon_b_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<736; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.U[0] = qoco_solver->sol->x[0];
  CPG_Prim.U[1] = qoco_solver->sol->x[1];
  CPG_Prim.U[2] = qoco_solver->sol->x[2];
  CPG_Prim.U[3] = qoco_solver->sol->x[3];
  CPG_Prim.U[4] = qoco_solver->sol->x[4];
  CPG_Prim.U[5] = qoco_solver->sol->x[5];
  CPG_Prim.U[6] = qoco_solver->sol->x[6];
  CPG_Prim.U[7] = qoco_solver->sol->x[7];
  CPG_Prim.U[8] = qoco_solver->sol->x[8];
  CPG_Prim.U[9] = qoco_solver->sol->x[9];
  CPG_Prim.U[10] = qoco_solver->sol->x[10];
  CPG_Prim.U[11] = qoco_solver->sol->x[11];
  CPG_Prim.U[12] = qoco_solver->sol->x[12];
  CPG_Prim.U[13] = qoco_solver->sol->x[13];
  CPG_Prim.U[14] = qoco_solver->sol->x[14];
  CPG_Prim.U[15] = qoco_solver->sol->x[15];
  CPG_Prim.U[16] = qoco_solver->sol->x[16];
  CPG_Prim.U[17] = qoco_solver->sol->x[17];
  CPG_Prim.U[18] = qoco_solver->sol->x[18];
  CPG_Prim.U[19] = qoco_solver->sol->x[19];
  CPG_Prim.U[20] = qoco_solver->sol->x[20];
  CPG_Prim.U[21] = qoco_solver->sol->x[21];
  CPG_Prim.U[22] = qoco_solver->sol->x[22];
  CPG_Prim.U[23] = qoco_solver->sol->x[23];
  CPG_Prim.U[24] = qoco_solver->sol->x[24];
  CPG_Prim.U[25] = qoco_solver->sol->x[25];
  CPG_Prim.U[26] = qoco_solver->sol->x[26];
  CPG_Prim.U[27] = qoco_solver->sol->x[27];
  CPG_Prim.U[28] = qoco_solver->sol->x[28];
  CPG_Prim.U[29] = qoco_solver->sol->x[29];
  CPG_Prim.U[30] = qoco_solver->sol->x[30];
  CPG_Prim.U[31] = qoco_solver->sol->x[31];
  CPG_Prim.U[32] = qoco_solver->sol->x[32];
  CPG_Prim.U[33] = qoco_solver->sol->x[33];
  CPG_Prim.U[34] = qoco_solver->sol->x[34];
  CPG_Prim.U[35] = qoco_solver->sol->x[35];
  CPG_Prim.U[36] = qoco_solver->sol->x[36];
  CPG_Prim.U[37] = qoco_solver->sol->x[37];
  CPG_Prim.U[38] = qoco_solver->sol->x[38];
  CPG_Prim.U[39] = qoco_solver->sol->x[39];
  CPG_Prim.U[40] = qoco_solver->sol->x[40];
  CPG_Prim.U[41] = qoco_solver->sol->x[41];
  CPG_Prim.U[42] = qoco_solver->sol->x[42];
  CPG_Prim.U[43] = qoco_solver->sol->x[43];
  CPG_Prim.U[44] = qoco_solver->sol->x[44];
  CPG_Prim.var1376[0] = qoco_solver->sol->x[45];
  CPG_Prim.var1376[1] = qoco_solver->sol->x[46];
  CPG_Prim.V[0] = qoco_solver->sol->x[162];
  CPG_Prim.V[1] = qoco_solver->sol->x[163];
  CPG_Prim.V[2] = qoco_solver->sol->x[164];
  CPG_Prim.V[3] = qoco_solver->sol->x[165];
  CPG_Prim.V[4] = qoco_solver->sol->x[166];
  CPG_Prim.V[5] = qoco_solver->sol->x[167];
  CPG_Prim.V[6] = qoco_solver->sol->x[168];
  CPG_Prim.V[7] = qoco_solver->sol->x[169];
  CPG_Prim.V[8] = qoco_solver->sol->x[170];
  CPG_Prim.V[9] = qoco_solver->sol->x[171];
  CPG_Prim.V[10] = qoco_solver->sol->x[172];
  CPG_Prim.V[11] = qoco_solver->sol->x[173];
  CPG_Prim.V[12] = qoco_solver->sol->x[174];
  CPG_Prim.V[13] = qoco_solver->sol->x[175];
  CPG_Prim.V[14] = qoco_solver->sol->x[176];
  CPG_Prim.V[15] = qoco_solver->sol->x[177];
  CPG_Prim.V[16] = qoco_solver->sol->x[178];
  CPG_Prim.V[17] = qoco_solver->sol->x[179];
  CPG_Prim.V[18] = qoco_solver->sol->x[180];
  CPG_Prim.V[19] = qoco_solver->sol->x[181];
  CPG_Prim.V[20] = qoco_solver->sol->x[182];
  CPG_Prim.V[21] = qoco_solver->sol->x[183];
  CPG_Prim.V[22] = qoco_solver->sol->x[184];
  CPG_Prim.V[23] = qoco_solver->sol->x[185];
  CPG_Prim.V[24] = qoco_solver->sol->x[186];
  CPG_Prim.V[25] = qoco_solver->sol->x[187];
  CPG_Prim.V[26] = qoco_solver->sol->x[188];
  CPG_Prim.V[27] = qoco_solver->sol->x[189];
  CPG_Prim.V[28] = qoco_solver->sol->x[190];
  CPG_Prim.V[29] = qoco_solver->sol->x[191];
  CPG_Prim.V[30] = qoco_solver->sol->x[192];
  CPG_Prim.V[31] = qoco_solver->sol->x[193];
  CPG_Prim.V[32] = qoco_solver->sol->x[194];
  CPG_Prim.V[33] = qoco_solver->sol->x[195];
  CPG_Prim.V[34] = qoco_solver->sol->x[196];
  CPG_Prim.V[35] = qoco_solver->sol->x[197];
  CPG_Prim.V[36] = qoco_solver->sol->x[198];
  CPG_Prim.V[37] = qoco_solver->sol->x[199];
  CPG_Prim.V[38] = qoco_solver->sol->x[200];
  CPG_Prim.V[39] = qoco_solver->sol->x[201];
  CPG_Prim.V[40] = qoco_solver->sol->x[202];
  CPG_Prim.V[41] = qoco_solver->sol->x[203];
  CPG_Prim.V[42] = qoco_solver->sol->x[204];
  CPG_Prim.V[43] = qoco_solver->sol->x[205];
  CPG_Prim.V[44] = qoco_solver->sol->x[206];
  CPG_Prim.V[45] = qoco_solver->sol->x[207];
  CPG_Prim.V[46] = qoco_solver->sol->x[208];
  CPG_Prim.V[47] = qoco_solver->sol->x[209];
  CPG_Prim.V[48] = qoco_solver->sol->x[210];
  CPG_Prim.V[49] = qoco_solver->sol->x[211];
  CPG_Prim.V[50] = qoco_solver->sol->x[212];
  CPG_Prim.V[51] = qoco_solver->sol->x[213];
  CPG_Prim.V[52] = qoco_solver->sol->x[214];
  CPG_Prim.V[53] = qoco_solver->sol->x[215];
  CPG_Prim.V[54] = qoco_solver->sol->x[216];
  CPG_Prim.V[55] = qoco_solver->sol->x[217];
  CPG_Prim.V[56] = qoco_solver->sol->x[218];
  CPG_Prim.V[57] = qoco_solver->sol->x[219];
  CPG_Prim.V[58] = qoco_solver->sol->x[220];
  CPG_Prim.V[59] = qoco_solver->sol->x[221];
  CPG_Prim.V[60] = qoco_solver->sol->x[222];
  CPG_Prim.V[61] = qoco_solver->sol->x[223];
  CPG_Prim.V[62] = qoco_solver->sol->x[224];
  CPG_Prim.V[63] = qoco_solver->sol->x[225];
  CPG_Prim.V[64] = qoco_solver->sol->x[226];
  CPG_Prim.V[65] = qoco_solver->sol->x[227];
  CPG_Prim.V[66] = qoco_solver->sol->x[228];
  CPG_Prim.V[67] = qoco_solver->sol->x[229];
  CPG_Prim.V[68] = qoco_solver->sol->x[230];
  CPG_Prim.V[69] = qoco_solver->sol->x[231];
  CPG_Prim.V[70] = qoco_solver->sol->x[232];
  CPG_Prim.V[71] = qoco_solver->sol->x[233];
  CPG_Prim.V[72] = qoco_solver->sol->x[234];
  CPG_Prim.V[73] = qoco_solver->sol->x[235];
  CPG_Prim.V[74] = qoco_solver->sol->x[236];
  CPG_Prim.V[75] = qoco_solver->sol->x[237];
  CPG_Prim.V[76] = qoco_solver->sol->x[238];
  CPG_Prim.V[77] = qoco_solver->sol->x[239];
  CPG_Prim.V[78] = qoco_solver->sol->x[240];
  CPG_Prim.V[79] = qoco_solver->sol->x[241];
  CPG_Prim.V[80] = qoco_solver->sol->x[242];
  CPG_Prim.V[81] = qoco_solver->sol->x[243];
  CPG_Prim.V[82] = qoco_solver->sol->x[244];
  CPG_Prim.V[83] = qoco_solver->sol->x[245];
  CPG_Prim.V[84] = qoco_solver->sol->x[246];
  CPG_Prim.V[85] = qoco_solver->sol->x[247];
  CPG_Prim.V[86] = qoco_solver->sol->x[248];
  CPG_Prim.V[87] = qoco_solver->sol->x[249];
  CPG_Prim.V[88] = qoco_solver->sol->x[250];
  CPG_Prim.V[89] = qoco_solver->sol->x[251];
  CPG_Prim.V[90] = qoco_solver->sol->x[252];
  CPG_Prim.V[91] = qoco_solver->sol->x[253];
  CPG_Prim.V[92] = qoco_solver->sol->x[254];
  CPG_Prim.V[93] = qoco_solver->sol->x[255];
  CPG_Prim.V[94] = qoco_solver->sol->x[256];
  CPG_Prim.V[95] = qoco_solver->sol->x[257];
  CPG_Prim.V[96] = qoco_solver->sol->x[258];
  CPG_Prim.V[97] = qoco_solver->sol->x[259];
  CPG_Prim.v_0[0] = qoco_solver->sol->x[260];
  CPG_Prim.v_0[1] = qoco_solver->sol->x[261];
  CPG_Prim.v_0[2] = qoco_solver->sol->x[262];
  CPG_Prim.v_0[3] = qoco_solver->sol->x[263];
  CPG_Prim.v_0[4] = qoco_solver->sol->x[264];
  CPG_Prim.v_0[5] = qoco_solver->sol->x[265];
  CPG_Prim.v_0[6] = qoco_solver->sol->x[266];
  CPG_Prim.v_N[0] = qoco_solver->sol->x[274];
  CPG_Prim.v_N[1] = qoco_solver->sol->x[275];
  CPG_Prim.v_N[2] = qoco_solver->sol->x[276];
  CPG_Prim.v_N[3] = qoco_solver->sol->x[277];
  CPG_Prim.v_N[4] = qoco_solver->sol->x[278];
  CPG_Prim.v_N[5] = qoco_solver->sol->x[279];
  CPG_Prim.eta[0] = qoco_solver->sol->x[147];
  CPG_Prim.eta[1] = qoco_solver->sol->x[148];
  CPG_Prim.eta[2] = qoco_solver->sol->x[149];
  CPG_Prim.eta[3] = qoco_solver->sol->x[150];
  CPG_Prim.eta[4] = qoco_solver->sol->x[151];
  CPG_Prim.eta[5] = qoco_solver->sol->x[152];
  CPG_Prim.eta[6] = qoco_solver->sol->x[153];
  CPG_Prim.eta[7] = qoco_solver->sol->x[154];
  CPG_Prim.eta[8] = qoco_solver->sol->x[155];
  CPG_Prim.eta[9] = qoco_solver->sol->x[156];
  CPG_Prim.eta[10] = qoco_solver->sol->x[157];
  CPG_Prim.eta[11] = qoco_solver->sol->x[158];
  CPG_Prim.eta[12] = qoco_solver->sol->x[159];
  CPG_Prim.eta[13] = qoco_solver->sol->x[160];
  CPG_Prim.eta[14] = qoco_solver->sol->x[161];
  CPG_Prim.X[0] = qoco_solver->sol->x[286];
  CPG_Prim.X[1] = qoco_solver->sol->x[287];
  CPG_Prim.X[2] = qoco_solver->sol->x[288];
  CPG_Prim.X[3] = qoco_solver->sol->x[289];
  CPG_Prim.X[4] = qoco_solver->sol->x[290];
  CPG_Prim.X[5] = qoco_solver->sol->x[291];
  CPG_Prim.X[6] = qoco_solver->sol->x[292];
  CPG_Prim.X[7] = qoco_solver->sol->x[293];
  CPG_Prim.X[8] = qoco_solver->sol->x[294];
  CPG_Prim.X[9] = qoco_solver->sol->x[295];
  CPG_Prim.X[10] = qoco_solver->sol->x[296];
  CPG_Prim.X[11] = qoco_solver->sol->x[297];
  CPG_Prim.X[12] = qoco_solver->sol->x[298];
  CPG_Prim.X[13] = qoco_solver->sol->x[299];
  CPG_Prim.X[14] = qoco_solver->sol->x[300];
  CPG_Prim.X[15] = qoco_solver->sol->x[301];
  CPG_Prim.X[16] = qoco_solver->sol->x[302];
  CPG_Prim.X[17] = qoco_solver->sol->x[303];
  CPG_Prim.X[18] = qoco_solver->sol->x[304];
  CPG_Prim.X[19] = qoco_solver->sol->x[305];
  CPG_Prim.X[20] = qoco_solver->sol->x[306];
  CPG_Prim.X[21] = qoco_solver->sol->x[307];
  CPG_Prim.X[22] = qoco_solver->sol->x[308];
  CPG_Prim.X[23] = qoco_solver->sol->x[309];
  CPG_Prim.X[24] = qoco_solver->sol->x[310];
  CPG_Prim.X[25] = qoco_solver->sol->x[311];
  CPG_Prim.X[26] = qoco_solver->sol->x[312];
  CPG_Prim.X[27] = qoco_solver->sol->x[313];
  CPG_Prim.X[28] = qoco_solver->sol->x[314];
  CPG_Prim.X[29] = qoco_solver->sol->x[315];
  CPG_Prim.X[30] = qoco_solver->sol->x[316];
  CPG_Prim.X[31] = qoco_solver->sol->x[317];
  CPG_Prim.X[32] = qoco_solver->sol->x[318];
  CPG_Prim.X[33] = qoco_solver->sol->x[319];
  CPG_Prim.X[34] = qoco_solver->sol->x[320];
  CPG_Prim.X[35] = qoco_solver->sol->x[321];
  CPG_Prim.X[36] = qoco_solver->sol->x[322];
  CPG_Prim.X[37] = qoco_solver->sol->x[323];
  CPG_Prim.X[38] = qoco_solver->sol->x[324];
  CPG_Prim.X[39] = qoco_solver->sol->x[325];
  CPG_Prim.X[40] = qoco_solver->sol->x[326];
  CPG_Prim.X[41] = qoco_solver->sol->x[327];
  CPG_Prim.X[42] = qoco_solver->sol->x[328];
  CPG_Prim.X[43] = qoco_solver->sol->x[329];
  CPG_Prim.X[44] = qoco_solver->sol->x[330];
  CPG_Prim.X[45] = qoco_solver->sol->x[331];
  CPG_Prim.X[46] = qoco_solver->sol->x[332];
  CPG_Prim.X[47] = qoco_solver->sol->x[333];
  CPG_Prim.X[48] = qoco_solver->sol->x[334];
  CPG_Prim.X[49] = qoco_solver->sol->x[335];
  CPG_Prim.X[50] = qoco_solver->sol->x[336];
  CPG_Prim.X[51] = qoco_solver->sol->x[337];
  CPG_Prim.X[52] = qoco_solver->sol->x[338];
  CPG_Prim.X[53] = qoco_solver->sol->x[339];
  CPG_Prim.X[54] = qoco_solver->sol->x[340];
  CPG_Prim.X[55] = qoco_solver->sol->x[341];
  CPG_Prim.X[56] = qoco_solver->sol->x[342];
  CPG_Prim.X[57] = qoco_solver->sol->x[343];
  CPG_Prim.X[58] = qoco_solver->sol->x[344];
  CPG_Prim.X[59] = qoco_solver->sol->x[345];
  CPG_Prim.X[60] = qoco_solver->sol->x[346];
  CPG_Prim.X[61] = qoco_solver->sol->x[347];
  CPG_Prim.X[62] = qoco_solver->sol->x[348];
  CPG_Prim.X[63] = qoco_solver->sol->x[349];
  CPG_Prim.X[64] = qoco_solver->sol->x[350];
  CPG_Prim.X[65] = qoco_solver->sol->x[351];
  CPG_Prim.X[66] = qoco_solver->sol->x[352];
  CPG_Prim.X[67] = qoco_solver->sol->x[353];
  CPG_Prim.X[68] = qoco_solver->sol->x[354];
  CPG_Prim.X[69] = qoco_solver->sol->x[355];
  CPG_Prim.X[70] = qoco_solver->sol->x[356];
  CPG_Prim.X[71] = qoco_solver->sol->x[357];
  CPG_Prim.X[72] = qoco_solver->sol->x[358];
  CPG_Prim.X[73] = qoco_solver->sol->x[359];
  CPG_Prim.X[74] = qoco_solver->sol->x[360];
  CPG_Prim.X[75] = qoco_solver->sol->x[361];
  CPG_Prim.X[76] = qoco_solver->sol->x[362];
  CPG_Prim.X[77] = qoco_solver->sol->x[363];
  CPG_Prim.X[78] = qoco_solver->sol->x[364];
  CPG_Prim.X[79] = qoco_solver->sol->x[365];
  CPG_Prim.X[80] = qoco_solver->sol->x[366];
  CPG_Prim.X[81] = qoco_solver->sol->x[367];
  CPG_Prim.X[82] = qoco_solver->sol->x[368];
  CPG_Prim.X[83] = qoco_solver->sol->x[369];
  CPG_Prim.X[84] = qoco_solver->sol->x[370];
  CPG_Prim.X[85] = qoco_solver->sol->x[371];
  CPG_Prim.X[86] = qoco_solver->sol->x[372];
  CPG_Prim.X[87] = qoco_solver->sol->x[373];
  CPG_Prim.X[88] = qoco_solver->sol->x[374];
  CPG_Prim.X[89] = qoco_solver->sol->x[375];
  CPG_Prim.X[90] = qoco_solver->sol->x[376];
  CPG_Prim.X[91] = qoco_solver->sol->x[377];
  CPG_Prim.X[92] = qoco_solver->sol->x[378];
  CPG_Prim.X[93] = qoco_solver->sol->x[379];
  CPG_Prim.X[94] = qoco_solver->sol->x[380];
  CPG_Prim.X[95] = qoco_solver->sol->x[381];
  CPG_Prim.X[96] = qoco_solver->sol->x[382];
  CPG_Prim.X[97] = qoco_solver->sol->x[383];
  CPG_Prim.X[98] = qoco_solver->sol->x[384];
  CPG_Prim.X[99] = qoco_solver->sol->x[385];
  CPG_Prim.X[100] = qoco_solver->sol->x[386];
  CPG_Prim.X[101] = qoco_solver->sol->x[387];
  CPG_Prim.X[102] = qoco_solver->sol->x[388];
  CPG_Prim.X[103] = qoco_solver->sol->x[389];
  CPG_Prim.X[104] = qoco_solver->sol->x[390];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = qoco_solver->sol->y[0];
  CPG_Dual.d0[1] = qoco_solver->sol->y[1];
  CPG_Dual.d0[2] = qoco_solver->sol->y[2];
  CPG_Dual.d0[3] = qoco_solver->sol->y[3];
  CPG_Dual.d0[4] = qoco_solver->sol->y[4];
  CPG_Dual.d0[5] = qoco_solver->sol->y[5];
  CPG_Dual.d0[6] = qoco_solver->sol->y[6];
  CPG_Dual.d1[0] = qoco_solver->sol->y[7];
  CPG_Dual.d1[1] = qoco_solver->sol->y[8];
  CPG_Dual.d1[2] = qoco_solver->sol->y[9];
  CPG_Dual.d1[3] = qoco_solver->sol->y[10];
  CPG_Dual.d1[4] = qoco_solver->sol->y[11];
  CPG_Dual.d1[5] = qoco_solver->sol->y[12];
  CPG_Dual.d1[6] = qoco_solver->sol->y[13];
  CPG_Dual.d2[0] = qoco_solver->sol->y[14];
  CPG_Dual.d2[1] = qoco_solver->sol->y[15];
  CPG_Dual.d2[2] = qoco_solver->sol->y[16];
  CPG_Dual.d2[3] = qoco_solver->sol->y[17];
  CPG_Dual.d2[4] = qoco_solver->sol->y[18];
  CPG_Dual.d2[5] = qoco_solver->sol->y[19];
  CPG_Dual.d2[6] = qoco_solver->sol->y[20];
  CPG_Dual.d3[0] = qoco_solver->sol->y[21];
  CPG_Dual.d3[1] = qoco_solver->sol->y[22];
  CPG_Dual.d3[2] = qoco_solver->sol->y[23];
  CPG_Dual.d3[3] = qoco_solver->sol->y[24];
  CPG_Dual.d3[4] = qoco_solver->sol->y[25];
  CPG_Dual.d3[5] = qoco_solver->sol->y[26];
  CPG_Dual.d3[6] = qoco_solver->sol->y[27];
  CPG_Dual.d4[0] = qoco_solver->sol->y[28];
  CPG_Dual.d4[1] = qoco_solver->sol->y[29];
  CPG_Dual.d4[2] = qoco_solver->sol->y[30];
  CPG_Dual.d4[3] = qoco_solver->sol->y[31];
  CPG_Dual.d4[4] = qoco_solver->sol->y[32];
  CPG_Dual.d4[5] = qoco_solver->sol->y[33];
  CPG_Dual.d4[6] = qoco_solver->sol->y[34];
  CPG_Dual.d5[0] = qoco_solver->sol->y[35];
  CPG_Dual.d5[1] = qoco_solver->sol->y[36];
  CPG_Dual.d5[2] = qoco_solver->sol->y[37];
  CPG_Dual.d5[3] = qoco_solver->sol->y[38];
  CPG_Dual.d5[4] = qoco_solver->sol->y[39];
  CPG_Dual.d5[5] = qoco_solver->sol->y[40];
  CPG_Dual.d5[6] = qoco_solver->sol->y[41];
  CPG_Dual.d6[0] = qoco_solver->sol->y[42];
  CPG_Dual.d6[1] = qoco_solver->sol->y[43];
  CPG_Dual.d6[2] = qoco_solver->sol->y[44];
  CPG_Dual.d6[3] = qoco_solver->sol->y[45];
  CPG_Dual.d6[4] = qoco_solver->sol->y[46];
  CPG_Dual.d6[5] = qoco_solver->sol->y[47];
  CPG_Dual.d6[6] = qoco_solver->sol->y[48];
  CPG_Dual.d7[0] = qoco_solver->sol->y[49];
  CPG_Dual.d7[1] = qoco_solver->sol->y[50];
  CPG_Dual.d7[2] = qoco_solver->sol->y[51];
  CPG_Dual.d7[3] = qoco_solver->sol->y[52];
  CPG_Dual.d7[4] = qoco_solver->sol->y[53];
  CPG_Dual.d7[5] = qoco_solver->sol->y[54];
  CPG_Dual.d7[6] = qoco_solver->sol->y[55];
  CPG_Dual.d8[0] = qoco_solver->sol->y[56];
  CPG_Dual.d8[1] = qoco_solver->sol->y[57];
  CPG_Dual.d8[2] = qoco_solver->sol->y[58];
  CPG_Dual.d8[3] = qoco_solver->sol->y[59];
  CPG_Dual.d8[4] = qoco_solver->sol->y[60];
  CPG_Dual.d8[5] = qoco_solver->sol->y[61];
  CPG_Dual.d8[6] = qoco_solver->sol->y[62];
  CPG_Dual.d9[0] = qoco_solver->sol->y[63];
  CPG_Dual.d9[1] = qoco_solver->sol->y[64];
  CPG_Dual.d9[2] = qoco_solver->sol->y[65];
  CPG_Dual.d9[3] = qoco_solver->sol->y[66];
  CPG_Dual.d9[4] = qoco_solver->sol->y[67];
  CPG_Dual.d9[5] = qoco_solver->sol->y[68];
  CPG_Dual.d9[6] = qoco_solver->sol->y[69];
  CPG_Dual.d10[0] = qoco_solver->sol->y[70];
  CPG_Dual.d10[1] = qoco_solver->sol->y[71];
  CPG_Dual.d10[2] = qoco_solver->sol->y[72];
  CPG_Dual.d10[3] = qoco_solver->sol->y[73];
  CPG_Dual.d10[4] = qoco_solver->sol->y[74];
  CPG_Dual.d10[5] = qoco_solver->sol->y[75];
  CPG_Dual.d10[6] = qoco_solver->sol->y[76];
  CPG_Dual.d11[0] = qoco_solver->sol->y[77];
  CPG_Dual.d11[1] = qoco_solver->sol->y[78];
  CPG_Dual.d11[2] = qoco_solver->sol->y[79];
  CPG_Dual.d11[3] = qoco_solver->sol->y[80];
  CPG_Dual.d11[4] = qoco_solver->sol->y[81];
  CPG_Dual.d11[5] = qoco_solver->sol->y[82];
  CPG_Dual.d11[6] = qoco_solver->sol->y[83];
  CPG_Dual.d12[0] = qoco_solver->sol->y[84];
  CPG_Dual.d12[1] = qoco_solver->sol->y[85];
  CPG_Dual.d12[2] = qoco_solver->sol->y[86];
  CPG_Dual.d12[3] = qoco_solver->sol->y[87];
  CPG_Dual.d12[4] = qoco_solver->sol->y[88];
  CPG_Dual.d12[5] = qoco_solver->sol->y[89];
  CPG_Dual.d12[6] = qoco_solver->sol->y[90];
  CPG_Dual.d13[0] = qoco_solver->sol->y[91];
  CPG_Dual.d13[1] = qoco_solver->sol->y[92];
  CPG_Dual.d13[2] = qoco_solver->sol->y[93];
  CPG_Dual.d13[3] = qoco_solver->sol->y[94];
  CPG_Dual.d13[4] = qoco_solver->sol->y[95];
  CPG_Dual.d13[5] = qoco_solver->sol->y[96];
  CPG_Dual.d13[6] = qoco_solver->sol->y[97];
  CPG_Dual.d14[0] = qoco_solver->sol->z[254];
  CPG_Dual.d14[1] = qoco_solver->sol->z[255];
  CPG_Dual.d14[2] = qoco_solver->sol->z[256];
  CPG_Dual.d14[3] = qoco_solver->sol->z[257];
  CPG_Dual.d14[4] = qoco_solver->sol->z[258];
  CPG_Dual.d14[5] = qoco_solver->sol->z[259];
  CPG_Dual.d14[6] = qoco_solver->sol->z[260];
  CPG_Dual.d14[7] = qoco_solver->sol->z[261];
  CPG_Dual.d14[8] = qoco_solver->sol->z[262];
  CPG_Dual.d14[9] = qoco_solver->sol->z[263];
  CPG_Dual.d14[10] = qoco_solver->sol->z[264];
  CPG_Dual.d14[11] = qoco_solver->sol->z[265];
  CPG_Dual.d14[12] = qoco_solver->sol->z[266];
  CPG_Dual.d14[13] = qoco_solver->sol->z[267];
  CPG_Dual.d14[14] = qoco_solver->sol->z[268];
  CPG_Dual.d15[0] = qoco_solver->sol->z[269];
  CPG_Dual.d15[1] = qoco_solver->sol->z[270];
  CPG_Dual.d15[2] = qoco_solver->sol->z[271];
  CPG_Dual.d15[3] = qoco_solver->sol->z[272];
  CPG_Dual.d15[4] = qoco_solver->sol->z[273];
  CPG_Dual.d15[5] = qoco_solver->sol->z[274];
  CPG_Dual.d15[6] = qoco_solver->sol->z[275];
  CPG_Dual.d15[7] = qoco_solver->sol->z[276];
  CPG_Dual.d15[8] = qoco_solver->sol->z[277];
  CPG_Dual.d15[9] = qoco_solver->sol->z[278];
  CPG_Dual.d15[10] = qoco_solver->sol->z[279];
  CPG_Dual.d15[11] = qoco_solver->sol->z[280];
  CPG_Dual.d15[12] = qoco_solver->sol->z[281];
  CPG_Dual.d15[13] = qoco_solver->sol->z[282];
  CPG_Dual.d15[14] = qoco_solver->sol->z[283];
  CPG_Dual.d16[0] = qoco_solver->sol->z[284];
  CPG_Dual.d16[1] = qoco_solver->sol->z[285];
  CPG_Dual.d16[2] = qoco_solver->sol->z[286];
  CPG_Dual.d16[3] = qoco_solver->sol->z[287];
  CPG_Dual.d16[4] = qoco_solver->sol->z[288];
  CPG_Dual.d16[5] = qoco_solver->sol->z[289];
  CPG_Dual.d16[6] = qoco_solver->sol->z[290];
  CPG_Dual.d16[7] = qoco_solver->sol->z[291];
  CPG_Dual.d16[8] = qoco_solver->sol->z[292];
  CPG_Dual.d16[9] = qoco_solver->sol->z[293];
  CPG_Dual.d16[10] = qoco_solver->sol->z[294];
  CPG_Dual.d16[11] = qoco_solver->sol->z[295];
  CPG_Dual.d16[12] = qoco_solver->sol->z[296];
  CPG_Dual.d16[13] = qoco_solver->sol->z[297];
  CPG_Dual.d16[14] = qoco_solver->sol->z[298];
  CPG_Dual.d17[0] = qoco_solver->sol->z[299];
  CPG_Dual.d17[1] = qoco_solver->sol->z[300];
  CPG_Dual.d17[2] = qoco_solver->sol->z[301];
  CPG_Dual.d17[3] = qoco_solver->sol->z[302];
  CPG_Dual.d17[4] = qoco_solver->sol->z[303];
  CPG_Dual.d17[5] = qoco_solver->sol->z[304];
  CPG_Dual.d17[6] = qoco_solver->sol->z[305];
  CPG_Dual.d17[7] = qoco_solver->sol->z[306];
  CPG_Dual.d17[8] = qoco_solver->sol->z[307];
  CPG_Dual.d17[9] = qoco_solver->sol->z[308];
  CPG_Dual.d17[10] = qoco_solver->sol->z[309];
  CPG_Dual.d17[11] = qoco_solver->sol->z[310];
  CPG_Dual.d17[12] = qoco_solver->sol->z[311];
  CPG_Dual.d17[13] = qoco_solver->sol->z[312];
  CPG_Dual.d17[14] = qoco_solver->sol->z[313];
  CPG_Dual.d18[0] = qoco_solver->sol->z[314];
  CPG_Dual.d18[1] = qoco_solver->sol->z[315];
  CPG_Dual.d18[2] = qoco_solver->sol->z[316];
  CPG_Dual.d18[3] = qoco_solver->sol->z[317];
  CPG_Dual.d18[4] = qoco_solver->sol->z[318];
  CPG_Dual.d18[5] = qoco_solver->sol->z[319];
  CPG_Dual.d18[6] = qoco_solver->sol->z[320];
  CPG_Dual.d18[7] = qoco_solver->sol->z[321];
  CPG_Dual.d18[8] = qoco_solver->sol->z[322];
  CPG_Dual.d18[9] = qoco_solver->sol->z[323];
  CPG_Dual.d18[10] = qoco_solver->sol->z[324];
  CPG_Dual.d18[11] = qoco_solver->sol->z[325];
  CPG_Dual.d18[12] = qoco_solver->sol->z[326];
  CPG_Dual.d18[13] = qoco_solver->sol->z[327];
  CPG_Dual.d18[14] = qoco_solver->sol->z[328];
  CPG_Dual.d19[0] = qoco_solver->sol->z[329];
  CPG_Dual.d19[1] = qoco_solver->sol->z[330];
  CPG_Dual.d19[2] = qoco_solver->sol->z[331];
  CPG_Dual.d19[3] = qoco_solver->sol->z[332];
  CPG_Dual.d19[4] = qoco_solver->sol->z[333];
  CPG_Dual.d19[5] = qoco_solver->sol->z[334];
  CPG_Dual.d19[6] = qoco_solver->sol->z[335];
  CPG_Dual.d19[7] = qoco_solver->sol->z[336];
  CPG_Dual.d19[8] = qoco_solver->sol->z[337];
  CPG_Dual.d19[9] = qoco_solver->sol->z[338];
  CPG_Dual.d19[10] = qoco_solver->sol->z[339];
  CPG_Dual.d19[11] = qoco_solver->sol->z[340];
  CPG_Dual.d19[12] = qoco_solver->sol->z[341];
  CPG_Dual.d19[13] = qoco_solver->sol->z[342];
  CPG_Dual.d19[14] = qoco_solver->sol->z[343];
  CPG_Dual.d20[0] = qoco_solver->sol->z[344];
  CPG_Dual.d20[1] = qoco_solver->sol->z[345];
  CPG_Dual.d20[2] = qoco_solver->sol->z[346];
  CPG_Dual.d20[3] = qoco_solver->sol->z[347];
  CPG_Dual.d20[4] = qoco_solver->sol->z[348];
  CPG_Dual.d20[5] = qoco_solver->sol->z[349];
  CPG_Dual.d20[6] = qoco_solver->sol->z[350];
  CPG_Dual.d20[7] = qoco_solver->sol->z[351];
  CPG_Dual.d20[8] = qoco_solver->sol->z[352];
  CPG_Dual.d20[9] = qoco_solver->sol->z[353];
  CPG_Dual.d20[10] = qoco_solver->sol->z[354];
  CPG_Dual.d20[11] = qoco_solver->sol->z[355];
  CPG_Dual.d20[12] = qoco_solver->sol->z[356];
  CPG_Dual.d20[13] = qoco_solver->sol->z[357];
  CPG_Dual.d20[14] = qoco_solver->sol->z[358];
  CPG_Dual.d21[0] = qoco_solver->sol->z[359];
  CPG_Dual.d21[1] = qoco_solver->sol->z[360];
  CPG_Dual.d22[0] = qoco_solver->sol->y[98];
  CPG_Dual.d22[1] = qoco_solver->sol->y[99];
  CPG_Dual.d22[2] = qoco_solver->sol->y[100];
  CPG_Dual.d22[3] = qoco_solver->sol->y[101];
  CPG_Dual.d22[4] = qoco_solver->sol->y[102];
  CPG_Dual.d22[5] = qoco_solver->sol->y[103];
  CPG_Dual.d22[6] = qoco_solver->sol->y[104];
  CPG_Dual.d22[7] = qoco_solver->sol->y[105];
  CPG_Dual.d22[8] = qoco_solver->sol->y[106];
  CPG_Dual.d22[9] = qoco_solver->sol->y[107];
  CPG_Dual.d22[10] = qoco_solver->sol->y[108];
  CPG_Dual.d22[11] = qoco_solver->sol->y[109];
  CPG_Dual.d22[12] = qoco_solver->sol->y[110];
  CPG_Dual.d22[13] = qoco_solver->sol->y[111];
  CPG_Dual.d22[14] = qoco_solver->sol->y[112];
  CPG_Dual.d22[15] = qoco_solver->sol->y[113];
  CPG_Dual.d22[16] = qoco_solver->sol->y[114];
  CPG_Dual.d22[17] = qoco_solver->sol->y[115];
  CPG_Dual.d22[18] = qoco_solver->sol->y[116];
  CPG_Dual.d22[19] = qoco_solver->sol->y[117];
  CPG_Dual.d22[20] = qoco_solver->sol->y[118];
  CPG_Dual.d22[21] = qoco_solver->sol->y[119];
  CPG_Dual.d22[22] = qoco_solver->sol->y[120];
  CPG_Dual.d22[23] = qoco_solver->sol->y[121];
  CPG_Dual.d22[24] = qoco_solver->sol->y[122];
  CPG_Dual.d22[25] = qoco_solver->sol->y[123];
  CPG_Dual.d22[26] = qoco_solver->sol->y[124];
  CPG_Dual.d22[27] = qoco_solver->sol->y[125];
  CPG_Dual.d22[28] = qoco_solver->sol->y[126];
  CPG_Dual.d22[29] = qoco_solver->sol->y[127];
  CPG_Dual.d22[30] = qoco_solver->sol->y[128];
  CPG_Dual.d22[31] = qoco_solver->sol->y[129];
  CPG_Dual.d22[32] = qoco_solver->sol->y[130];
  CPG_Dual.d22[33] = qoco_solver->sol->y[131];
  CPG_Dual.d22[34] = qoco_solver->sol->y[132];
  CPG_Dual.d22[35] = qoco_solver->sol->y[133];
  CPG_Dual.d22[36] = qoco_solver->sol->y[134];
  CPG_Dual.d22[37] = qoco_solver->sol->y[135];
  CPG_Dual.d22[38] = qoco_solver->sol->y[136];
  CPG_Dual.d22[39] = qoco_solver->sol->y[137];
  CPG_Dual.d22[40] = qoco_solver->sol->y[138];
  CPG_Dual.d22[41] = qoco_solver->sol->y[139];
  CPG_Dual.d22[42] = qoco_solver->sol->y[140];
  CPG_Dual.d22[43] = qoco_solver->sol->y[141];
  CPG_Dual.d22[44] = qoco_solver->sol->y[142];
  CPG_Dual.d22[45] = qoco_solver->sol->y[143];
  CPG_Dual.d22[46] = qoco_solver->sol->y[144];
  CPG_Dual.d22[47] = qoco_solver->sol->y[145];
  CPG_Dual.d22[48] = qoco_solver->sol->y[146];
  CPG_Dual.d23[0] = qoco_solver->sol->y[147];
  CPG_Dual.d23[1] = qoco_solver->sol->y[148];
  CPG_Dual.d23[2] = qoco_solver->sol->y[149];
  CPG_Dual.d23[3] = qoco_solver->sol->y[150];
  CPG_Dual.d24[0] = qoco_solver->sol->y[151];
  CPG_Dual.d24[1] = qoco_solver->sol->y[152];
  CPG_Dual.d24[2] = qoco_solver->sol->y[153];
  CPG_Dual.d24[3] = qoco_solver->sol->y[154];
  CPG_Dual.d25 = qoco_solver->sol->y[155];
  CPG_Dual.d26 = qoco_solver->sol->y[156];
  CPG_Dual.d27[0] = qoco_solver->sol->z[361];
  CPG_Dual.d27[1] = qoco_solver->sol->z[362];
  CPG_Dual.d27[2] = qoco_solver->sol->z[363];
  CPG_Dual.d27[3] = qoco_solver->sol->z[364];
  CPG_Dual.d27[4] = qoco_solver->sol->z[365];
  CPG_Dual.d27[5] = qoco_solver->sol->z[366];
  CPG_Dual.d27[6] = qoco_solver->sol->z[367];
  CPG_Dual.d27[7] = qoco_solver->sol->z[368];
  CPG_Dual.d27[8] = qoco_solver->sol->z[369];
  CPG_Dual.d27[9] = qoco_solver->sol->z[370];
  CPG_Dual.d27[10] = qoco_solver->sol->z[371];
  CPG_Dual.d27[11] = qoco_solver->sol->z[372];
  CPG_Dual.d27[12] = qoco_solver->sol->z[373];
  CPG_Dual.d27[13] = qoco_solver->sol->z[374];
  CPG_Dual.d27[14] = qoco_solver->sol->z[375];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_solver->sol->obj);
  CPG_Info.iter = qoco_solver->sol->iters;
  CPG_Info.status = qoco_solver->sol->status;
  CPG_Info.pri_res = qoco_solver->sol->pres;
  CPG_Info.dua_res = qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_c(){
  for (i=0; i<496; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
  for (i=0; i<1490; i++){
    Canon_Params_conditioning.A->x[i] = Canon_Params.A->x[i];
  }
}

void cpg_copy_b(){
  for (i=0; i<157; i++){
    Canon_Params_conditioning.b[i] = Canon_Params.b[i];
  }
}

void cpg_copy_G(){
  for (i=0; i<1151; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<736; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
  }
  if (Canon_Outdated.b) {
    cpg_canonicalize_b();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!qoco_solver ) {
    cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   P = NULL;
   qoco_set_csc(A, 157, 496, Canon_Params.A->nnz, Canon_Params.A->x, Canon_Params.A->p, Canon_Params.A->i);
   qoco_set_csc(G, 736, 496, Canon_Params.G->nnz, Canon_Params.G->x, Canon_Params.G->p, Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(qoco_solver, 496, 736, 157, P, Canon_Params.c, A, Canon_Params.b, G, Canon_Params.h, 376, 90, (int *) &qoco_q, qoco_settings);
  }
  if (Canon_Outdated.h) {
    update_vector_data(qoco_solver, NULL, NULL, Canon_Params.h);
  }
  if (Canon_Outdated.b) {
    update_vector_data(qoco_solver, NULL, Canon_Params.b, NULL);
  }
  if (Canon_Outdated.A) {
    update_matrix_data(qoco_solver, NULL, Canon_Params.A->x, NULL);
  }
  qoco_solver->settings->max_iters = Canon_Settings.max_iters;
  qoco_solver->settings->bisect_iters = Canon_Settings.bisect_iters;
  qoco_solver->settings->ruiz_iters = Canon_Settings.ruiz_iters;
  qoco_solver->settings->iter_ref_iters = Canon_Settings.iter_ref_iters;
  qoco_solver->settings->kkt_static_reg = Canon_Settings.kkt_static_reg;
  qoco_solver->settings->kkt_dynamic_reg = Canon_Settings.kkt_dynamic_reg;
  qoco_solver->settings->abstol = Canon_Settings.abstol;
  qoco_solver->settings->reltol = Canon_Settings.reltol;
  qoco_solver->settings->abstol_inacc = Canon_Settings.abstol_inacc;
  qoco_solver->settings->reltol_inacc = Canon_Settings.reltol_inacc;
  qoco_solver->settings->verbose = Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(qoco_solver);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.A = 0;
  Canon_Outdated.b = 0;
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.max_iters = 200;
  Canon_Settings.bisect_iters = 5;
  Canon_Settings.ruiz_iters = 0;
  Canon_Settings.iter_ref_iters = 1;
  Canon_Settings.kkt_static_reg = 1e-8;
  Canon_Settings.kkt_dynamic_reg = 1e-8;
  Canon_Settings.abstol = 1e-7;
  Canon_Settings.reltol = 1e-7;
  Canon_Settings.abstol_inacc = 1e-5;
  Canon_Settings.reltol_inacc = 1e-5;
  Canon_Settings.verbose = 0;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  Canon_Settings.bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}
