function xdot = SymDynamics2DoF_linear_noumag(t,in2,in3,tf,alpha)
%SymDynamics2DoF_linear_noumag
%    XDOT = SymDynamics2DoF_linear_noumag(T,IN2,IN3,TF,ALPHA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-May-2025 17:06:56

thrust1 = in3(1,:);
thrust2 = in3(2,:);
v1 = in2(3,:);
v2 = in2(4,:);
xdot = [tf.*v1;tf.*v2;tf.*thrust1;tf.*(thrust2-9.81e-3);-alpha.*tf.*sqrt(abs(thrust1).^2+abs(thrust2).^2)];
end
