function [X_] = disc_prop(prob, X, U, p)
%DISC_PROP Summary of this function goes here
%   Detailed explanation goes here

if prob.u_hold == "ZOH"
    for k = 1:(prob.N - 1)
        X(:, k + 1) = prob.disc.A_k(:, :, k) * X(:, k) ...
                     + prob.disc.B_k(:, :, k) * U(:, k) ...
                     + prob.disc.E_k(:, :, k) * p ...
                     + prob.disc.c_k(:, :, k);
    end
elseif prob.u_hold == "FOH"
    for k = 1:(prob.N - 1)
        X(:, k + 1) = prob.disc.A_k(:, :, k) * X(:, k) ...
                     + prob.disc.B_minus_k(:, :, k) * U(:, k) ...
                     + prob.disc.B_plus_k(:, :, k) * U(:, k + 1) ...
                     + prob.disc.E_k(:, :, k) * p ...
                     + prob.disc.c_k(:, :, k);
    end
end
end

